// @generated by `cargo run -p nmp-codegen -- gen producer-consts`. DO NOT EDIT.
//
// Source of truth: crates/nmp-codegen/src/projection_contract.rs
//   (PROJECTION_CONTRACT entry for key "nmp.nip17.dm_inbox": schema_id / file_identifier /
//   version). Regenerate + verify drift via
//   `.github/workflows/codegen-drift.yml` (gen producer-consts --check).
/// Stable schema identifier carried in the typed-projection envelope. Equals the
/// snapshot key (ADR-0037 shared-keyspace contract).
pub const DM_INBOX_SCHEMA_ID: &str = "nmp.nip17.dm_inbox";
/// FlatBuffers file identifier embedded in every buffer this module emits.
pub const DM_INBOX_FILE_IDENTIFIER: &[u8; 4] = b"NDMI";
/// Wire schema version. Bump on any breaking change to this projection's `.fbs`.
pub const DM_INBOX_SCHEMA_VERSION: u32 = 2;
