//! Typed FlatBuffers wire codec for the `"nmp.nip17.dm_relay_list"` projection.
//!
//! The producer is the typed projection closure installed by
//! [`crate::register`]. This module encodes the `typed_projections`
//! sidecar payload for that runtime (ADR-0072).
//!
//! [`DmRelayList`] is the single read model the runtime and this codec share.
//! `active_pubkey: Option<String>` carries a `has_active_pubkey` flag + value so absent
//! (`None`/JSON `null`) round-trips distinctly from a present default.
//!
//! Honours D6 (no panics): decode returns `Err(String)` on any malformed input.

// The generated FlatBuffers bindings are intrinsically `unsafe`. This `allow`
// block scopes the relaxation to the single generated module.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/dm_relay_list_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use serde::Serialize;

use generated::nmp::nip_17 as fb;

// #1723 — `DM_RELAY_LIST_SCHEMA_ID` / `_FILE_IDENTIFIER` / `_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("dm_relay_list_producer_consts.generated.rs");

/// The `"nmp.nip17.dm_relay_list"` snapshot read model used by the runtime and
/// the typed FlatBuffers sidecar.
#[derive(Clone, Debug, Default, Eq, PartialEq, Serialize)]
pub struct DmRelayList {
    /// The active account's pubkey (hex), or `None` when not signed in — mirrors
    /// the producer's `active_pubkey: Option<String>` (JSON `null` when absent).
    pub active_pubkey: Option<String>,
    /// The active account's read-eligible DM relay URLs (kind:10050), in order.
    pub read_relay_urls: Vec<String>,
}

// --- encode ---------------------------------------------------------------

/// Encode a [`DmRelayList`] to typed FlatBuffers bytes (with the `NDRL` file
/// identifier). `read_relay_urls` order is preserved verbatim.
#[must_use]
pub fn encode_dm_relay_list(relay_list: &DmRelayList) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let active_pubkey = relay_list
        .active_pubkey
        .as_ref()
        .map(|s| fbb.create_string(s));
    let url_offsets: Vec<WIPOffset<&str>> = relay_list
        .read_relay_urls
        .iter()
        .map(|url| fbb.create_string(url))
        .collect();
    let read_relay_urls = fbb.create_vector(&url_offsets);

    let root = fb::DmRelayListSnapshot::create(
        &mut fbb,
        &fb::DmRelayListSnapshotArgs {
            has_active_pubkey: relay_list.active_pubkey.is_some(),
            active_pubkey,
            read_relay_urls: Some(read_relay_urls),
        },
    );
    fb::finish_dm_relay_list_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by [`encode_dm_relay_list`])
/// back into a [`DmRelayList`]. Returns an error string on any malformed input.
pub fn decode_dm_relay_list(bytes: &[u8]) -> Result<DmRelayList, String> {
    if bytes.len() < 8 || !fb::dm_relay_list_snapshot_buffer_has_identifier(bytes) {
        return Err("missing NDRL file identifier".to_string());
    }
    let root = fb::root_as_dm_relay_list_snapshot(bytes)
        .map_err(|e| format!("not a valid DmRelayListSnapshot buffer: {e}"))?;

    let mut read_relay_urls = Vec::new();
    if let Some(fb_urls) = root.read_relay_urls() {
        read_relay_urls.reserve(fb_urls.len());
        for url in fb_urls.iter() {
            read_relay_urls.push(url.to_string());
        }
    }

    Ok(DmRelayList {
        active_pubkey: if root.has_active_pubkey() {
            Some(root.active_pubkey().unwrap_or_default().to_string())
        } else {
            None
        },
        read_relay_urls,
    })
}

#[cfg(test)]
#[path = "dm_relay_list_fb_tests.rs"]
mod tests;
