// automatically generated by the FlatBuffers compiler, do not modify

package nmp.marmot

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * The most recent terminal op FAILURE (deferred-op expiry or a failed
 * retry). Mirrors `crate::projection::payload::LastOpError`. Raw data only
 * (aim.md §2): `reason` is the machine code, native maps it to a banner.
 */
@Suppress("unused")
class LastOpError : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LastOpError {
        __init(_i, _bb)
        return this
    }
    val op : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val opAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun opInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val reason : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val reasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun reasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val atSecs : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val correlationId : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val correlationIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun correlationIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsLastOpError(_bb: ByteBuffer): LastOpError = getRootAsLastOpError(_bb, LastOpError())
        fun getRootAsLastOpError(_bb: ByteBuffer, obj: LastOpError): LastOpError {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createLastOpError(builder: FlatBufferBuilder, opOffset: Int, reasonOffset: Int, atSecs: ULong, correlationIdOffset: Int) : Int {
            builder.startTable(4)
            addAtSecs(builder, atSecs)
            addCorrelationId(builder, correlationIdOffset)
            addReason(builder, reasonOffset)
            addOp(builder, opOffset)
            return endLastOpError(builder)
        }
        fun startLastOpError(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addOp(builder: FlatBufferBuilder, op: Int) = builder.addOffset(0, op, 0)
        fun addReason(builder: FlatBufferBuilder, reason: Int) = builder.addOffset(1, reason, 0)
        fun addAtSecs(builder: FlatBufferBuilder, atSecs: ULong) = builder.addLong(2, atSecs.toLong(), 0)
        fun addCorrelationId(builder: FlatBufferBuilder, correlationId: Int) = builder.addOffset(3, correlationId, 0)
        fun endLastOpError(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
