// automatically generated by the FlatBuffers compiler, do not modify

package nmp.marmot

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MarmotGroupRow : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MarmotGroupRow {
        __init(_i, _bb)
        return this
    }
    val idHex : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idHexAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idHexInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val name : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    fun members(j: Int) : String? {
        val o = __offset(8)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val membersLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val memberCount : UInt
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val hasUnreadCount : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val unreadCount : UInt
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val hasLastMsgAt : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lastMsgAt : ULong
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMarmotGroupRow(_bb: ByteBuffer): MarmotGroupRow = getRootAsMarmotGroupRow(_bb, MarmotGroupRow())
        fun getRootAsMarmotGroupRow(_bb: ByteBuffer, obj: MarmotGroupRow): MarmotGroupRow {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMarmotGroupRow(builder: FlatBufferBuilder, idHexOffset: Int, nameOffset: Int, membersOffset: Int, memberCount: UInt, hasUnreadCount: Boolean, unreadCount: UInt, hasLastMsgAt: Boolean, lastMsgAt: ULong) : Int {
            builder.startTable(8)
            addLastMsgAt(builder, lastMsgAt)
            addUnreadCount(builder, unreadCount)
            addMemberCount(builder, memberCount)
            addMembers(builder, membersOffset)
            addName(builder, nameOffset)
            addIdHex(builder, idHexOffset)
            addHasLastMsgAt(builder, hasLastMsgAt)
            addHasUnreadCount(builder, hasUnreadCount)
            return endMarmotGroupRow(builder)
        }
        fun startMarmotGroupRow(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addIdHex(builder: FlatBufferBuilder, idHex: Int) = builder.addOffset(0, idHex, 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(1, name, 0)
        fun addMembers(builder: FlatBufferBuilder, members: Int) = builder.addOffset(2, members, 0)
        fun createMembersVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startMembersVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addMemberCount(builder: FlatBufferBuilder, memberCount: UInt) = builder.addInt(3, memberCount.toInt(), 0)
        fun addHasUnreadCount(builder: FlatBufferBuilder, hasUnreadCount: Boolean) = builder.addBoolean(4, hasUnreadCount, false)
        fun addUnreadCount(builder: FlatBufferBuilder, unreadCount: UInt) = builder.addInt(5, unreadCount.toInt(), 0)
        fun addHasLastMsgAt(builder: FlatBufferBuilder, hasLastMsgAt: Boolean) = builder.addBoolean(6, hasLastMsgAt, false)
        fun addLastMsgAt(builder: FlatBufferBuilder, lastMsgAt: ULong) = builder.addLong(7, lastMsgAt.toLong(), 0)
        fun endMarmotGroupRow(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
