// automatically generated by the FlatBuffers compiler, do not modify

package nmp.marmot

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MarmotSnapshot : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MarmotSnapshot {
        __init(_i, _bb)
        return this
    }
    val schemaVersion : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 2u
        }
    fun groups(j: Int) : nmp.marmot.MarmotGroupRow? = groups(nmp.marmot.MarmotGroupRow(), j)
    fun groups(obj: nmp.marmot.MarmotGroupRow, j: Int) : nmp.marmot.MarmotGroupRow? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val groupsLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    fun pendingWelcomes(j: Int) : nmp.marmot.PendingWelcomeRow? = pendingWelcomes(nmp.marmot.PendingWelcomeRow(), j)
    fun pendingWelcomes(obj: nmp.marmot.PendingWelcomeRow, j: Int) : nmp.marmot.PendingWelcomeRow? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val pendingWelcomesLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    val keyPackage : nmp.marmot.KeyPackageStatus? get() = keyPackage(nmp.marmot.KeyPackageStatus())
    fun keyPackage(obj: nmp.marmot.KeyPackageStatus) : nmp.marmot.KeyPackageStatus? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun cachedKpPubkeys(j: Int) : String? {
        val o = __offset(12)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val cachedKpPubkeysLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    val isRegistered : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val orphanedCommitCount : UInt
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val initErrorKind : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val initErrorKindAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(18, 1)
    fun initErrorKindInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 18, 1)
    val initErrorDetail : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val initErrorDetailAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(20, 1)
    fun initErrorDetailInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 20, 1)
    fun pendingOps(j: Int) : nmp.marmot.PendingOpRow? = pendingOps(nmp.marmot.PendingOpRow(), j)
    fun pendingOps(obj: nmp.marmot.PendingOpRow, j: Int) : nmp.marmot.PendingOpRow? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val pendingOpsLength : Int
        get() {
            val o = __offset(22); return if (o != 0) __vector_len(o) else 0
        }
    val lastOpError : nmp.marmot.LastOpError? get() = lastOpError(nmp.marmot.LastOpError())
    fun lastOpError(obj: nmp.marmot.LastOpError) : nmp.marmot.LastOpError? {
        val o = __offset(24)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMarmotSnapshot(_bb: ByteBuffer): MarmotSnapshot = getRootAsMarmotSnapshot(_bb, MarmotSnapshot())
        fun getRootAsMarmotSnapshot(_bb: ByteBuffer, obj: MarmotSnapshot): MarmotSnapshot {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun MarmotSnapshotBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "NMMS")
        fun createMarmotSnapshot(builder: FlatBufferBuilder, schemaVersion: UInt, groupsOffset: Int, pendingWelcomesOffset: Int, keyPackageOffset: Int, cachedKpPubkeysOffset: Int, isRegistered: Boolean, orphanedCommitCount: UInt, initErrorKindOffset: Int, initErrorDetailOffset: Int, pendingOpsOffset: Int, lastOpErrorOffset: Int) : Int {
            builder.startTable(11)
            addLastOpError(builder, lastOpErrorOffset)
            addPendingOps(builder, pendingOpsOffset)
            addInitErrorDetail(builder, initErrorDetailOffset)
            addInitErrorKind(builder, initErrorKindOffset)
            addOrphanedCommitCount(builder, orphanedCommitCount)
            addCachedKpPubkeys(builder, cachedKpPubkeysOffset)
            addKeyPackage(builder, keyPackageOffset)
            addPendingWelcomes(builder, pendingWelcomesOffset)
            addGroups(builder, groupsOffset)
            addSchemaVersion(builder, schemaVersion)
            addIsRegistered(builder, isRegistered)
            return endMarmotSnapshot(builder)
        }
        fun startMarmotSnapshot(builder: FlatBufferBuilder) = builder.startTable(11)
        fun addSchemaVersion(builder: FlatBufferBuilder, schemaVersion: UInt) = builder.addInt(0, schemaVersion.toInt(), 2)
        fun addGroups(builder: FlatBufferBuilder, groups: Int) = builder.addOffset(1, groups, 0)
        fun createGroupsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startGroupsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addPendingWelcomes(builder: FlatBufferBuilder, pendingWelcomes: Int) = builder.addOffset(2, pendingWelcomes, 0)
        fun createPendingWelcomesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPendingWelcomesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addKeyPackage(builder: FlatBufferBuilder, keyPackage: Int) = builder.addOffset(3, keyPackage, 0)
        fun addCachedKpPubkeys(builder: FlatBufferBuilder, cachedKpPubkeys: Int) = builder.addOffset(4, cachedKpPubkeys, 0)
        fun createCachedKpPubkeysVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startCachedKpPubkeysVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addIsRegistered(builder: FlatBufferBuilder, isRegistered: Boolean) = builder.addBoolean(5, isRegistered, false)
        fun addOrphanedCommitCount(builder: FlatBufferBuilder, orphanedCommitCount: UInt) = builder.addInt(6, orphanedCommitCount.toInt(), 0)
        fun addInitErrorKind(builder: FlatBufferBuilder, initErrorKind: Int) = builder.addOffset(7, initErrorKind, 0)
        fun addInitErrorDetail(builder: FlatBufferBuilder, initErrorDetail: Int) = builder.addOffset(8, initErrorDetail, 0)
        fun addPendingOps(builder: FlatBufferBuilder, pendingOps: Int) = builder.addOffset(9, pendingOps, 0)
        fun createPendingOpsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startPendingOpsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addLastOpError(builder: FlatBufferBuilder, lastOpError: Int) = builder.addOffset(10, lastOpError, 0)
        fun endMarmotSnapshot(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishMarmotSnapshotBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "NMMS")
        fun finishSizePrefixedMarmotSnapshotBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "NMMS")
    }
}
