//! Client-initiated (`bunker://` URI) handshake entry point.
//!
//! [`start_bunker`] is the single entry point for the client-initiated
//! flow: it builds the initial protocol effects (subscribe, send `connect`
//! RPC, emit progress) and returns a [`SessionState`] ready to process
//! inbound events via [`SessionState::on_relay_event`].
//!
//! The blocking `run_handshake` that existed here in STEP 1 is removed.
//! The broker drives the reducer from its own thread via the `drive` helper
//! in `nmp-signer-broker::broker::drive`.

use nostr::{Keys, PublicKey};

use crate::effect::Effect;
use crate::error::HandshakeError;
use crate::progress_codes;
use crate::reducer::{Phase, SessionState};
use crate::rpc::{build_connect_params, build_event_frame_at, build_req_frame};

/// Per-handshake step deadline — kept as a public const so tests can
/// reference the same 60s value.
pub const STEP_TIMEOUT_SECS: u64 = 60;

/// Start a client-initiated (`bunker://`) handshake session.
///
/// Returns the initial `SessionState` and the first batch of effects the
/// caller must execute in order:
///
/// 1. [`Effect::Subscribe`] — install the REQ frame on the relay
///    (use `relay.subscribe()` so it survives reconnects, V-14).
/// 2. [`Effect::Progress`] — emit `"connecting"` progress to the host UI.
/// 3. [`Effect::SendFrame`] — publish the `connect` RPC to the bunker.
///
/// If the `connect` frame cannot be built (crypto/signing failure), the
/// third element is [`Effect::Error`] instead.
///
/// # Parameters
///
/// - `sub_id` — the subscription id to use in the `["REQ", ...]` frame.
///   The broker passes `BUNKER_SUB_ID` from `relay_client.rs`.
/// - `local_keys` — ephemeral keypair for this session (generated by the
///   broker; the bunker addresses responses to the local public key).
/// - `remote_pubkey` — the bunker's public key from the `bunker://` URI.
/// - `relay_url` — the relay URL (used in Subscribe/SendFrame effects and
///   stored for replay via `on_relay_connected`).
/// - `secret` — optional pre-shared secret from the bunker URI.
/// - `perms` — optional permission string from the bunker URI.
/// - `now` — caller-provided Unix-second timestamp (`SystemTime::now()`
///   on native; injected by the broker so no SystemTime appears in the
///   reducer on the wasm path).
#[allow(clippy::too_many_arguments)]
pub fn start_bunker(
    sub_id: &str,
    local_keys: Keys,
    remote_pubkey: PublicKey,
    relay_url: String,
    secret: Option<&str>,
    perms: Option<&str>,
    now: u64,
) -> (SessionState, Vec<Effect>) {
    let local_pubkey_hex = local_keys.public_key().to_hex();
    let req_frame = build_req_frame(sub_id, &local_pubkey_hex, now);

    // Build the connect RPC body.
    let connect_params = build_connect_params(remote_pubkey, secret, perms);
    // Counter starts at 0; connect uses "00000000000", gpk uses "00000000001".
    let connect_id = format!("{:011x}", 0u64);
    let connect_envelope = serde_json::json!({
        "id": &connect_id,
        "method": "connect",
        "params": connect_params,
    })
    .to_string();

    let connect_frame_result =
        build_event_frame_at(&local_keys, remote_pubkey, &connect_envelope, now);

    let state = SessionState::new(
        Phase::BunkerWaitConnectAck { connect_id, remote_pubkey },
        local_keys,
        relay_url.clone(),
        sub_id.to_string(),
        perms.map(str::to_string),
        1, // req_counter: 0 used for connect_id above
        now + STEP_TIMEOUT_SECS,
    );

    let effects = match connect_frame_result {
        Ok(frame) => vec![
            Effect::Subscribe { relay_url: relay_url.clone(), frame: req_frame },
            Effect::Progress {
                stage: "connecting".to_string(),
                code: Some(progress_codes::SENDING_CONNECT_TO_BUNKER.to_string()),
                detail: Some("Sending connect to bunker".to_string()),
            },
            Effect::SendFrame { relay_url, text: frame },
        ],
        Err(e) => vec![
            Effect::Subscribe { relay_url: relay_url.clone(), frame: req_frame },
            Effect::Error {
                error: HandshakeError::Protocol(e.to_string()),
            },
        ],
    };

    (state, effects)
}
