//! Signer-initiated (`nostrconnect://`) handshake entry point.
//!
//! [`start_nostrconnect`] is the single entry point for the signer-initiated
//! flow: it builds the `nostrconnect://` URI, the initial subscribe effect,
//! and the initial progress effect, then returns a [`SessionState`] ready to
//! receive the signer's `connect` event.
//!
//! The blocking `run_nostrconnect_handshake` that existed here in STEP 1 is
//! removed. The broker drives the reducer from its own thread via the `drive`
//! helper in `nmp-signer-broker::broker::drive`.
//!
//! ## Protocol (signer-initiated)
//!
//! 1. The client generates a URI (`nostrconnect://<local_pubkey>?...`) and
//!    subscribes to the relay.  The URI is returned synchronously so the host
//!    can render a QR code immediately.
//! 2. The signer scans the QR, connects to the relay, and sends an encrypted
//!    kind:24133 `{method:"connect", params:[signer_pubkey, secret]}` event.
//!    Handled by [`crate::reducer::SessionState::on_relay_event`].
//! 3. The client validates the secret, sends `ack`, then sends
//!    `get_public_key`.
//! 4. The signer replies with the user pubkey.

use nostr::Keys;

use crate::effect::Effect;
use crate::progress_codes;
use crate::reducer::{Phase, SessionState};
use crate::rpc::build_req_frame;
use crate::uri_encode::percent_encode_query_value;

/// Start a signer-initiated (`nostrconnect://`) handshake session.
///
/// Returns a tuple of:
/// - The `nostrconnect://` URI to display as a QR code.
/// - The [`SessionState`] ready to drive via [`SessionState::on_relay_event`].
/// - The initial effects to execute in order:
///   1. [`Effect::Subscribe`] — install the REQ frame on the relay.
///   2. [`Effect::Progress`] — emit `"connecting"` progress to the host UI.
///
/// # Parameters
///
/// - `sub_id` — the subscription id for the `["REQ", ...]` frame.
/// - `local_keys` — ephemeral keypair generated by the broker (the signer
///   addresses its `connect` event to the local public key).
/// - `relay_url` — the relay URL the client is listening on.
/// - `expected_secret` — the randomly-generated secret embedded in the URI
///   (generated by the broker with `rand`; validated on the signer's connect
///   frame).
/// - `perms` — optional permission string to embed in the URI.
/// - `name` — the client name to advertise in the URI (e.g. `"nmp"`).
/// - `now` — caller-provided Unix-second timestamp.
pub fn start_nostrconnect(
    sub_id: &str,
    local_keys: Keys,
    relay_url: String,
    expected_secret: String,
    perms: Option<String>,
    name: &str,
    now: u64,
) -> (String, SessionState, Vec<Effect>) {
    let pubkey_hex = local_keys.public_key().to_hex();
    let encoded_relay = percent_encode_query_value(&relay_url);
    let mut uri = format!(
        "nostrconnect://{pubkey_hex}?relay={encoded_relay}&secret={expected_secret}&name={name}"
    );
    if let Some(perms_str) = &perms {
        uri.push_str("&perms=");
        uri.push_str(&percent_encode_query_value(perms_str));
    }

    let req_frame = build_req_frame(sub_id, &pubkey_hex, now);

    let state = SessionState::new(
        Phase::NostrConnectWaitConnect { expected_secret },
        local_keys,
        relay_url.clone(),
        sub_id.to_string(),
        perms,
        0,
        now + crate::bunker::STEP_TIMEOUT_SECS,
    );

    let effects = vec![
        Effect::Subscribe { relay_url, frame: req_frame },
        Effect::Progress {
            stage: "connecting".to_string(),
            code: Some(progress_codes::NOSTRCONNECT_SCAN_QR.to_string()),
            detail: Some("Waiting for signer to scan QR code".to_string()),
        },
    ];

    (uri, state, effects)
}
