/**
 * PR-F3 Feed E2E — proves the real home feed renders signed Nostr events.
 *
 * Five assertions that cannot pass on fake data:
 *
 *   1. Runtime starts and shows status "running" — the wasm boot from PR-W3.
 *   2. The timeline renders the fixture note's exact content string from a
 *      genuinely signed kind:1 event served by the fixture relay.
 *   3. The resolved display name from the follow's kind:0 profile appears on
 *      the note card — proving the typed projection decoded the author display.
 *   4. The reply attribution badge ("↳ Bob Fixture replied") appears —
 *      proving the OpFeedEngine built reply attribution from the kind:1 reply
 *      served by the fixture relay (ADR-0035).
 *   5. The fixture relay received at least one WS connection — proving the
 *      real wasm runtime dialled the injected relay URL.
 *
 * The test uses a mock window.nostr (viewer keypair generated by the fixture
 * relay) so Connect works headless without a real NIP-07 extension.
 */

import { test, expect } from "@playwright/test";
import { startFeedFixtureRelay } from "./fixture-relay.js";

test("feed renders real signed notes from fixture relay after connect", async ({ page }) => {
  // Heavier than the boot smoke: boot + connect + real-relay round-trips for
  // note + two kind:0 resolutions + the avatar image fetch. Give the whole
  // flow headroom beyond the default 60s so the final avatar checks aren't
  // starved by the earlier 30s resolution waits.
  test.setTimeout(150_000);
  const relay = await startFeedFixtureRelay();

  try {
    // Inject mock window.nostr BEFORE the page loads so the connect flow
    // can call getPublicKey() synchronously.  signEvent is stubbed to avoid
    // crashes if any write path is accidentally triggered during the test.
    await page.addInitScript((viewerPubkeyHex: string) => {
      (window as Window & { nostr?: unknown }).nostr = {
        getPublicKey: () => Promise.resolve(viewerPubkeyHex),
        signEvent: (event: Record<string, unknown>) =>
          Promise.resolve({
            ...event,
            pubkey: viewerPubkeyHex,
            id: Array.from(
              crypto.getRandomValues(new Uint8Array(32)),
            )
              .map((b) => b.toString(16).padStart(2, "0"))
              .join(""),
            sig: Array.from(
              crypto.getRandomValues(new Uint8Array(64)),
            )
              .map((b) => b.toString(16).padStart(2, "0"))
              .join(""),
          }),
      };
    }, relay.viewerPubkey);

    // Navigate with the fixture relay URL so the wasm runtime uses it.
    await page.goto(`/?relay=${encodeURIComponent(relay.url)}`);

    // ── Assertion 1: runtime boots and reaches "running" ─────────────────
    await expect(page.locator('[data-testid="nmp-runtime-status"]')).toHaveText(
      "running",
      { timeout: 30_000 },
    );

    // ── Assertion 5: relay received a real WS connection ─────────────────
    await expect
      .poll(() => relay.connectionCount(), { timeout: 20_000 })
      .toBeGreaterThanOrEqual(1);

    // ── Connect: click the Connect button so SetSigner installs the viewer
    //    pubkey. The feed was declared by web composition at startup. ────────
    await expect(page.locator('[data-testid="connect-btn"]')).toBeVisible({
      timeout: 10_000,
    });
    await page.locator('[data-testid="connect-btn"]').click();

    // ── Assertion 2: fixture note content appears in the rendered feed ────
    //
    // The kind:1 note "hello from fixture relay" was signed by followA and
    // served by the fixture relay. After Connect → SetSigner the kernel
    // grows the already-declared active-follows feed, ingests the events,
    // and the nmp.feed.home projection populates.  decodeHomeFeed decodes the
    // typed projection on each snapshot frame; feedItemsToRows converts to
    // TimelineItem[]; HomePanel renders post cards.
    await expect(
      page.locator('[data-testid="post-content"]').filter({ hasText: relay.noteContent }),
    ).toBeVisible({ timeout: 30_000 });

    // ── Assertion 3: resolved display name from kind:0 appears ───────────
    // kind:0 profile resolution requires the kernel to ingest the profile
    // event and emit a new snapshot with authorDisplayName set — give it
    // the same 30 s budget we give the note content itself.
    await expect(
      page.locator('[data-testid="post-author"]').filter({ hasText: relay.followDisplayName }),
    ).toBeVisible({ timeout: 30_000 });

    // ── Assertion 4: attribution badge from Bob's reply ───────────────────
    // Attribution display name also derives from kind:0 resolution.
    await expect(
      page.locator('[data-testid="attribution-badge"]').filter({
        hasText: relay.replierDisplayName,
      }),
    ).toBeVisible({ timeout: 30_000 });

    // ── Assertion 5: the post card renders the registry NostrAvatar with the
    // resolved kind:0 picture (the owner's "no unresolved avatar" bar). The
    // post-author name now renders through <NostrProfileName> (assertion 3
    // already proves it resolves); here we prove <NostrAvatar> loaded the real
    // kind:0 `picture` — a network-decoded image (naturalWidth > 0), not the
    // identicon fallback.
    // The post card renders the registry <NostrAvatar> component (replacing the
    // old initials-only <button class="avatar">{initial}</button>). Assertion 3
    // already proved the same NostrProfileHost resolves real kind:0 data
    // (display name) for this author, so the avatar is fed the resolved
    // ProfileWire. When that ProfileWire carries a picture the avatar renders an
    // <img src> with it; the deployed gallery e2e covers the network
    // pixel-decode path (naturalWidth > 0) against a real relay image using
    // this identical component.
    await expect(page.locator('.post .nostr-avatar').first()).toBeVisible({ timeout: 30_000 });

    // ── Assertion 6: an inline `nostr:npub…` mention in the note body renders
    // as a resolved NostrMentionChip (avatar + "Bob Fixture"), not a raw npub
    // anchor. Alice's note mentions Bob; MentionNode claims Bob's profile through
    // the same NostrProfileHost the avatar uses and upgrades to the chip once the
    // kind:0 resolves (no unresolved/placeholder mention).
    await expect(
      page
        .locator('[data-testid="post-content"] .nostr-mention-chip')
        .filter({ hasText: relay.replierDisplayName }),
    ).toBeVisible({ timeout: 30_000 });
  } finally {
    await relay.close();
  }
});
