//! Typed FlatBuffers wire codec for [`crate::projection::GroupEventsSnapshot`].
//!
//! The canonical FFI shape is the serde JSON of `GroupEventsSnapshot`
//! (`GroupEventsProjection::snapshot_json`). This module adds a **typed
//! FlatBuffers** encoding of the same read model — the typed sidecar (ADR-0037)
//! carried alongside the generic `Value` projection under the same
//! `"nmp.nip29.group_events"` key. The serde shape stays authoritative; this is the
//! typed payload a `NGEV`-aware host decodes with generated accessors instead of
//! JSON reflection.
//!
//! Raw data only (ADR-0032): every field is the raw protocol value — hex event
//! ids / pubkeys, verbatim content, Unix-second `created_at`, raw kind. No
//! `display::` forwarder runs on the encode path.
//!
//! Honours D6 (no panics): [`decode_group_events_snapshot`] returns `Err(String)`
//! on any malformed input; there are no `unwrap`/`expect`/panicking-index
//! operations on the decode path.
//!
//! ## Regenerating the bindings
//!
//! The checked-in bindings in `wire/generated/group_events_generated.rs` are
//! produced by `flatc` from `schema/group_events.fbs`. Regenerate only with the
//! workspace FlatBuffers pin (`25.12.19`), enforced by
//! `ci/check-flatbuffers-version-pins.sh`. The schema is self-contained, so
//! generate with plain `flatc --rust`:
//!
//! ```sh
//! flatc --rust -o crates/nmp-nip29/src/wire/generated \
//!       crates/nmp-nip29/schema/group_events.fbs
//! ```

// The generated FlatBuffers bindings are intrinsically `unsafe` (every accessor
// reads from a raw `Table`). This single generated module — and only it — opts
// back into `unsafe`. No hand-written code in this file uses `unsafe`.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/group_events_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use generated::nmp::nip_29 as fb;

use crate::projection::{GroupEvent, GroupEventsSnapshot};

// #1723 — `GROUP_EVENTS_SCHEMA_ID` / `_FILE_IDENTIFIER` / `_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("group_events_producer_consts.generated.rs");

// --- encode ---------------------------------------------------------------

/// Encode a [`GroupEventsSnapshot`] to typed FlatBuffers bytes (with the `NGEV`
/// file identifier). `events` order is preserved verbatim (newest-first as the
/// projection emits it).
#[must_use]
pub fn encode_group_events_snapshot(snapshot: &GroupEventsSnapshot) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let event_offsets: Vec<WIPOffset<fb::GroupEvent<'_>>> = snapshot
        .events
        .iter()
        .map(|event| encode_event(&mut fbb, event))
        .collect();
    let events = fbb.create_vector(&event_offsets);

    let root = fb::GroupEventsSnapshot::create(
        &mut fbb,
        &fb::GroupEventsSnapshotArgs {
            schema_version: GROUP_EVENTS_SCHEMA_VERSION,
            events: Some(events),
        },
    );
    fb::finish_group_events_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

fn encode_event<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    event: &GroupEvent,
) -> WIPOffset<fb::GroupEvent<'a>> {
    let id = fbb.create_string(&event.id);
    let pubkey = fbb.create_string(&event.pubkey);
    let content = fbb.create_string(&event.content);
    fb::GroupEvent::create(
        fbb,
        &fb::GroupEventArgs {
            id: Some(id),
            pubkey: Some(pubkey),
            content: Some(content),
            created_at: event.created_at,
            kind: event.kind,
        },
    )
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by [`encode_group_events_snapshot`])
/// back into a [`GroupEventsSnapshot`]. Returns an error string on any malformed
/// input or missing required field.
pub fn decode_group_events_snapshot(bytes: &[u8]) -> Result<GroupEventsSnapshot, String> {
    if bytes.len() < 8 || !fb::group_events_snapshot_buffer_has_identifier(bytes) {
        return Err("missing NGEV file identifier".to_string());
    }
    let root = fb::root_as_group_events_snapshot(bytes)
        .map_err(|e| format!("not a valid GroupEventsSnapshot buffer: {e}"))?;

    let mut events = Vec::new();
    if let Some(fb_events) = root.events() {
        events.reserve(fb_events.len());
        for fb_event in fb_events.iter() {
            events.push(decode_event(fb_event)?);
        }
    }

    Ok(GroupEventsSnapshot { events })
}

fn decode_event(event: fb::GroupEvent<'_>) -> Result<GroupEvent, String> {
    Ok(GroupEvent {
        id: str_field(event.id(), "GroupEvent.id")?,
        pubkey: str_field(event.pubkey(), "GroupEvent.pubkey")?,
        content: str_field(event.content(), "GroupEvent.content")?,
        created_at: event.created_at(),
        kind: event.kind(),
    })
}

/// Require a present string field; an absent FlatBuffers string on a mandatory
/// slot is a decode error.
fn str_field(value: Option<&str>, ctx: &str) -> Result<String, String> {
    value
        .map(str::to_string)
        .ok_or_else(|| format!("{ctx}: missing required string field"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn event(id: &str, kind: u32) -> GroupEvent {
        GroupEvent {
            id: id.to_string(),
            pubkey: "a".repeat(64),
            content: "hello".to_string(),
            created_at: 1,
            kind,
        }
    }

    #[test]
    fn round_trips_flat_group_events() {
        let snapshot = GroupEventsSnapshot {
            events: vec![event("chat", 9), event("thread", 11)],
        };
        let bytes = encode_group_events_snapshot(&snapshot);
        let decoded = decode_group_events_snapshot(&bytes).expect("decode");
        assert_eq!(decoded, snapshot);
    }

    #[test]
    fn buffer_carries_ngev_identifier() {
        let bytes = encode_group_events_snapshot(&GroupEventsSnapshot::empty());
        assert!(fb::group_events_snapshot_buffer_has_identifier(&bytes));
        assert_eq!(GROUP_EVENTS_SCHEMA_VERSION, 3);
    }
}
