//! Typed FlatBuffers wire codec for [`crate::projection::GroupChatSnapshot`].
//!
//! The canonical FFI shape is the serde JSON of `GroupChatSnapshot`
//! (`GroupChatProjection::snapshot_json`). This module adds a **typed
//! FlatBuffers** encoding of the same read model — the typed sidecar (ADR-0037)
//! carried alongside the generic `Value` projection under the same
//! `"nmp.nip29.group_chat"` key. The serde shape stays authoritative; this is the
//! typed payload a `NGCS`-aware host decodes with generated accessors instead of
//! JSON reflection.
//!
//! Raw data only (ADR-0032): every field is the raw protocol value — hex event
//! ids / pubkeys, verbatim content, Unix-second `created_at`, raw kind. No
//! `display::` forwarder runs on the encode path.
//!
//! Honours D6 (no panics): [`decode_group_chat_snapshot`] returns `Err(String)`
//! on any malformed input; there are no `unwrap`/`expect`/panicking-index
//! operations on the decode path.
//!
//! ## Regenerating the bindings
//!
//! The checked-in bindings in `wire/generated/group_chat_generated.rs` are
//! produced by `flatc` from `schema/group_chat.fbs`. Regenerate only with the
//! workspace FlatBuffers pin (`25.12.19`), enforced by
//! `ci/check-flatbuffers-version-pins.sh`. The schema is self-contained, so
//! generate with plain `flatc --rust`:
//!
//! ```sh
//! flatc --rust -o crates/nmp-nip29/src/wire/generated \
//!       crates/nmp-nip29/schema/group_chat.fbs
//! ```

// The generated FlatBuffers bindings are intrinsically `unsafe` (every accessor
// reads from a raw `Table`). This single generated module — and only it — opts
// back into `unsafe`. No hand-written code in this file uses `unsafe`.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/group_chat_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use generated::nmp::nip_29 as fb;

use crate::projection::{GroupChatMessage, GroupChatSnapshot};

// #1723 — `GROUP_CHAT_SCHEMA_ID` / `_FILE_IDENTIFIER` / `_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("group_chat_producer_consts.generated.rs");

// --- encode ---------------------------------------------------------------

/// Encode a [`GroupChatSnapshot`] to typed FlatBuffers bytes (with the `NGCS`
/// file identifier). `messages` order is preserved verbatim (newest-first as the
/// projection emits it).
#[must_use]
pub fn encode_group_chat_snapshot(snapshot: &GroupChatSnapshot) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let message_offsets: Vec<WIPOffset<fb::GroupChatMessage<'_>>> = snapshot
        .messages
        .iter()
        .map(|message| encode_message(&mut fbb, message))
        .collect();
    let messages = fbb.create_vector(&message_offsets);

    let root = fb::GroupChatSnapshot::create(
        &mut fbb,
        &fb::GroupChatSnapshotArgs {
            schema_version: GROUP_CHAT_SCHEMA_VERSION,
            messages: Some(messages),
        },
    );
    fb::finish_group_chat_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

fn encode_message<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    message: &GroupChatMessage,
) -> WIPOffset<fb::GroupChatMessage<'a>> {
    let id = fbb.create_string(&message.id);
    let pubkey = fbb.create_string(&message.pubkey);
    let content = fbb.create_string(&message.content);
    fb::GroupChatMessage::create(
        fbb,
        &fb::GroupChatMessageArgs {
            id: Some(id),
            pubkey: Some(pubkey),
            content: Some(content),
            created_at: message.created_at,
            kind: message.kind,
        },
    )
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by [`encode_group_chat_snapshot`])
/// back into a [`GroupChatSnapshot`]. Returns an error string on any malformed
/// input or missing required field.
pub fn decode_group_chat_snapshot(bytes: &[u8]) -> Result<GroupChatSnapshot, String> {
    if bytes.len() < 8 || !fb::group_chat_snapshot_buffer_has_identifier(bytes) {
        return Err("missing NGCS file identifier".to_string());
    }
    let root = fb::root_as_group_chat_snapshot(bytes)
        .map_err(|e| format!("not a valid GroupChatSnapshot buffer: {e}"))?;

    let mut messages = Vec::new();
    if let Some(fb_messages) = root.messages() {
        messages.reserve(fb_messages.len());
        for fb_message in fb_messages.iter() {
            messages.push(decode_message(fb_message)?);
        }
    }

    Ok(GroupChatSnapshot { messages })
}

fn decode_message(message: fb::GroupChatMessage<'_>) -> Result<GroupChatMessage, String> {
    Ok(GroupChatMessage {
        id: str_field(message.id(), "GroupChatMessage.id")?,
        pubkey: str_field(message.pubkey(), "GroupChatMessage.pubkey")?,
        content: str_field(message.content(), "GroupChatMessage.content")?,
        created_at: message.created_at(),
        kind: message.kind(),
    })
}

/// Require a present string field; an absent FlatBuffers string on a mandatory
/// slot is a decode error.
fn str_field(value: Option<&str>, ctx: &str) -> Result<String, String> {
    value
        .map(str::to_string)
        .ok_or_else(|| format!("{ctx}: missing required string field"))
}
