//! Typed FlatBuffers wire codec for [`crate::projection::GroupTimelineSnapshot`].
//!
//! The canonical FFI shape is the serde JSON of `GroupTimelineSnapshot`
//! (`GroupTimelineProjection::snapshot_json`). This module adds a **typed
//! FlatBuffers** encoding of the same read model — the typed sidecar (ADR-0037)
//! carried alongside the generic `Value` projection under the same
//! `"nmp.nip29.group_timeline"` key. The serde shape stays authoritative; this is the
//! typed payload a `NGTL`-aware host decodes with generated accessors instead of
//! JSON reflection.
//!
//! Raw data only (ADR-0032): every field is the raw protocol value — hex event
//! ids / pubkeys, verbatim content, Unix-second `created_at`, raw kind. No
//! `display::` forwarder runs on the encode path.
//!
//! Honours D6 (no panics): [`decode_group_timeline_snapshot`] returns `Err(String)`
//! on any malformed input; there are no `unwrap`/`expect`/panicking-index
//! operations on the decode path.
//!
//! ## Regenerating the bindings
//!
//! The checked-in bindings in `wire/generated/group_timeline_generated.rs` are
//! produced by `flatc` from `schema/group_timeline.fbs`. Regenerate only with the
//! workspace FlatBuffers pin (`25.12.19`), enforced by
//! `ci/check-flatbuffers-version-pins.sh`. The schema is self-contained, so
//! generate with plain `flatc --rust`:
//!
//! ```sh
//! flatc --rust -o crates/nmp-nip29/src/wire/generated \
//!       crates/nmp-nip29/schema/group_timeline.fbs
//! ```

// The generated FlatBuffers bindings are intrinsically `unsafe` (every accessor
// reads from a raw `Table`). This single generated module — and only it — opts
// back into `unsafe`. No hand-written code in this file uses `unsafe`.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/group_timeline_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use generated::nmp::nip_29 as fb;

use crate::projection::{GroupTimelineEvent, GroupTimelineSnapshot};

// #1723 — `GROUP_TIMELINE_SCHEMA_ID` / `_FILE_IDENTIFIER` / `_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("group_timeline_producer_consts.generated.rs");

// --- encode ---------------------------------------------------------------

/// Encode a [`GroupTimelineSnapshot`] to typed FlatBuffers bytes (with the `NGTL`
/// file identifier). `events` order is preserved verbatim (newest-first as the
/// projection emits it).
#[must_use]
pub fn encode_group_timeline_snapshot(snapshot: &GroupTimelineSnapshot) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let event_offsets: Vec<WIPOffset<fb::GroupTimelineEvent<'_>>> = snapshot
        .events
        .iter()
        .map(|event| encode_event(&mut fbb, event))
        .collect();
    let events = fbb.create_vector(&event_offsets);

    let root = fb::GroupTimelineSnapshot::create(
        &mut fbb,
        &fb::GroupTimelineSnapshotArgs {
            schema_version: GROUP_TIMELINE_SCHEMA_VERSION,
            events: Some(events),
        },
    );
    fb::finish_group_timeline_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

fn encode_event<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    event: &GroupTimelineEvent,
) -> WIPOffset<fb::GroupTimelineEvent<'a>> {
    let id = fbb.create_string(&event.id);
    let pubkey = fbb.create_string(&event.pubkey);
    let content = fbb.create_string(&event.content);
    fb::GroupTimelineEvent::create(
        fbb,
        &fb::GroupTimelineEventArgs {
            id: Some(id),
            pubkey: Some(pubkey),
            content: Some(content),
            created_at: event.created_at,
            kind: event.kind,
        },
    )
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by [`encode_group_timeline_snapshot`])
/// back into a [`GroupTimelineSnapshot`]. Returns an error string on any malformed
/// input or missing required field.
pub fn decode_group_timeline_snapshot(bytes: &[u8]) -> Result<GroupTimelineSnapshot, String> {
    if bytes.len() < 8 || !fb::group_timeline_snapshot_buffer_has_identifier(bytes) {
        return Err("missing NGTL file identifier".to_string());
    }
    let root = fb::root_as_group_timeline_snapshot(bytes)
        .map_err(|e| format!("not a valid GroupTimelineSnapshot buffer: {e}"))?;

    let mut events = Vec::new();
    if let Some(fb_events) = root.events() {
        events.reserve(fb_events.len());
        for fb_event in fb_events.iter() {
            events.push(decode_event(fb_event)?);
        }
    }

    Ok(GroupTimelineSnapshot { events })
}

fn decode_event(event: fb::GroupTimelineEvent<'_>) -> Result<GroupTimelineEvent, String> {
    Ok(GroupTimelineEvent {
        id: str_field(event.id(), "GroupTimelineEvent.id")?,
        pubkey: str_field(event.pubkey(), "GroupTimelineEvent.pubkey")?,
        content: str_field(event.content(), "GroupTimelineEvent.content")?,
        created_at: event.created_at(),
        kind: event.kind(),
    })
}

/// Require a present string field; an absent FlatBuffers string on a mandatory
/// slot is a decode error.
fn str_field(value: Option<&str>, ctx: &str) -> Result<String, String> {
    value
        .map(str::to_string)
        .ok_or_else(|| format!("{ctx}: missing required string field"))
}
