//! Typed FlatBuffers wire codec for [`crate::projection::GroupRosterSnapshot`].
//!
//! The canonical FFI shape is the serde JSON of `GroupRosterSnapshot`
//! (`GroupRosterProjection::snapshot_json`). This module adds a **typed
//! FlatBuffers** encoding of the same read model — the typed sidecar (ADR-0072)
//! carried under the `"nmp.nip29.group_roster"` key. The serde shape stays
//! authoritative; this is the typed payload a `NGRS`-aware host decodes with
//! generated accessors instead of JSON reflection.
//!
//! Raw data only (ADR-0072): every field is the raw protocol value — hex
//! pubkeys and verbatim role tokens. No `display::` forwarder runs on the
//! encode path.
//!
//! Honours D6 (no panics): [`decode_group_roster_snapshot`] returns
//! `Err(String)` on any malformed input; there are no `unwrap`/`expect`/
//! panicking-index operations on the decode path.
//!
//! ## Regenerating the bindings
//!
//! The checked-in bindings in `wire/generated/group_roster_generated.rs` are
//! produced by `flatc` from `schema/group_roster.fbs`. Regenerate only with the
//! workspace FlatBuffers pin (`25.12.19`):
//!
//! ```sh
//! flatc --rust -o crates/nmp-nip29/src/wire/generated \
//!       crates/nmp-nip29/schema/group_roster.fbs
//! ```

#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/group_roster_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use generated::nmp::nip_29 as fb;

use crate::projection::{GroupRole, GroupRosterMember, GroupRosterSnapshot};

// #1723 — `GROUP_ROSTER_SCHEMA_ID` / `_FILE_IDENTIFIER` / `_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("group_roster_producer_consts.generated.rs");

// --- encode ---------------------------------------------------------------

/// Encode a [`GroupRosterSnapshot`] to typed FlatBuffers bytes (with the `NGRS`
/// file identifier). `members` / `roles` order is preserved verbatim.
#[must_use]
pub fn encode_group_roster_snapshot(snapshot: &GroupRosterSnapshot) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let member_offsets: Vec<WIPOffset<fb::GroupRosterMember<'_>>> = snapshot
        .members
        .iter()
        .map(|member| encode_member(&mut fbb, member))
        .collect();
    let members = fbb.create_vector(&member_offsets);

    let role_offsets: Vec<WIPOffset<fb::GroupRole<'_>>> = snapshot
        .roles
        .iter()
        .map(|role| encode_role(&mut fbb, role))
        .collect();
    let roles = fbb.create_vector(&role_offsets);

    let host_relay_url = fbb.create_string(&snapshot.host_relay_url);
    let group_id = fbb.create_string(&snapshot.group_id);

    let root = fb::GroupRosterSnapshot::create(
        &mut fbb,
        &fb::GroupRosterSnapshotArgs {
            schema_version: GROUP_ROSTER_SCHEMA_VERSION,
            host_relay_url: Some(host_relay_url),
            group_id: Some(group_id),
            members: Some(members),
            roles: Some(roles),
        },
    );
    fb::finish_group_roster_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

fn encode_member<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    member: &GroupRosterMember,
) -> WIPOffset<fb::GroupRosterMember<'a>> {
    let pubkey = fbb.create_string(&member.pubkey);
    let roles = if member.roles.is_empty() {
        None
    } else {
        let offsets: Vec<_> = member.roles.iter().map(|s| fbb.create_string(s)).collect();
        Some(fbb.create_vector(&offsets))
    };
    fb::GroupRosterMember::create(
        fbb,
        &fb::GroupRosterMemberArgs {
            pubkey: Some(pubkey),
            roles,
            is_admin: member.is_admin,
            is_member: member.is_member,
        },
    )
}

fn encode_role<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    role: &GroupRole,
) -> WIPOffset<fb::GroupRole<'a>> {
    let name = fbb.create_string(&role.name);
    let description = role.description.as_ref().map(|s| fbb.create_string(s));
    fb::GroupRole::create(
        fbb,
        &fb::GroupRoleArgs {
            name: Some(name),
            description,
        },
    )
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by
/// [`encode_group_roster_snapshot`]) back into a [`GroupRosterSnapshot`].
/// Returns an error string on any malformed input or missing required field.
pub fn decode_group_roster_snapshot(bytes: &[u8]) -> Result<GroupRosterSnapshot, String> {
    if bytes.len() < 8 || !fb::group_roster_snapshot_buffer_has_identifier(bytes) {
        return Err("missing NGRS file identifier".to_string());
    }
    let root = fb::root_as_group_roster_snapshot(bytes)
        .map_err(|e| format!("not a valid GroupRosterSnapshot buffer: {e}"))?;

    let host_relay_url = str_field(root.host_relay_url(), "GroupRosterSnapshot.host_relay_url")?;
    let group_id = str_field(root.group_id(), "GroupRosterSnapshot.group_id")?;

    let mut members = Vec::new();
    if let Some(fb_members) = root.members() {
        members.reserve(fb_members.len());
        for fb_member in fb_members.iter() {
            members.push(decode_member(fb_member)?);
        }
    }

    let mut roles = Vec::new();
    if let Some(fb_roles) = root.roles() {
        roles.reserve(fb_roles.len());
        for fb_role in fb_roles.iter() {
            roles.push(decode_role(fb_role)?);
        }
    }

    Ok(GroupRosterSnapshot {
        host_relay_url,
        group_id,
        members,
        roles,
    })
}

fn decode_member(member: fb::GroupRosterMember<'_>) -> Result<GroupRosterMember, String> {
    let roles = member
        .roles()
        .map(|v| v.iter().map(str::to_string).collect())
        .unwrap_or_default();
    Ok(GroupRosterMember {
        pubkey: str_field(member.pubkey(), "GroupRosterMember.pubkey")?,
        roles,
        is_admin: member.is_admin(),
        is_member: member.is_member(),
    })
}

fn decode_role(role: fb::GroupRole<'_>) -> Result<GroupRole, String> {
    Ok(GroupRole {
        name: str_field(role.name(), "GroupRole.name")?,
        description: role.description().map(str::to_string),
    })
}

/// Require a present string field; an absent FlatBuffers string on a mandatory
/// slot is a decode error.
fn str_field(value: Option<&str>, ctx: &str) -> Result<String, String> {
    value
        .map(str::to_string)
        .ok_or_else(|| format!("{ctx}: missing required string field"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn group_roster_round_trips() {
        let snapshot = GroupRosterSnapshot {
            host_relay_url: "wss://groups.example.com".to_string(),
            group_id: "rust-nostr".to_string(),
            members: vec![
                GroupRosterMember {
                    pubkey: "a".repeat(64),
                    roles: vec!["king".to_string(), "moderator".to_string()],
                    is_admin: true,
                    is_member: true,
                },
                GroupRosterMember {
                    pubkey: "b".repeat(64),
                    roles: Vec::new(),
                    is_admin: false,
                    is_member: true,
                },
            ],
            roles: vec![
                GroupRole {
                    name: "king".to_string(),
                    description: Some("the founder".to_string()),
                },
                GroupRole {
                    name: "moderator".to_string(),
                    description: None,
                },
            ],
        };

        let bytes = encode_group_roster_snapshot(&snapshot);
        let decoded = decode_group_roster_snapshot(&bytes).expect("NGRS decodes");
        assert_eq!(decoded, snapshot);
    }

    #[test]
    fn bad_identifier_is_rejected() {
        assert!(decode_group_roster_snapshot(b"not-a-buffer").is_err());
    }
}
