//! Typed FlatBuffers wire codec for [`crate::projection::ThreadingSnapshot`].
//!
//! The canonical FFI shape is the serde JSON of `ThreadingSnapshot`
//! (`ThreadingProjection::snapshot`). This module adds a **typed FlatBuffers**
//! encoding of the same read model — the typed sidecar (ADR-0037) carried
//! alongside the generic `Value` projection under the same
//! `"nmp.threading.graph"` key. The serde shape stays authoritative; this is
//! the typed payload an `NTHR`-aware host decodes with generated accessors
//! instead of JSON reflection.
//!
//! Raw data only (ADR-0032): pointer ids, coordinates, URIs, and pubkeys are
//! verbatim. No `display::` forwarder runs on the encode path.
//!
//! Honours D6 (no panics): [`decode_threading_snapshot`] returns `Err(String)`
//! on any malformed input; there are no `unwrap`/`expect`/panicking-index
//! operations on the decode path.
//!
//! ## Regenerating the bindings
//!
//! The checked-in bindings in `wire/generated/threading_graph_generated.rs`
//! are produced by `flatc` from `schema/threading_graph.fbs`. Regenerate only
//! with the workspace FlatBuffers pin (`25.12.19`), enforced by
//! `ci/check-flatbuffers-version-pins.sh`. The schema is self-contained, so
//! generate with plain `flatc --rust`:
//!
//! ```sh
//! flatc --rust -o crates/nmp-threading/src/wire/generated \
//!       crates/nmp-threading/schema/threading_graph.fbs
//! ```

// The generated FlatBuffers bindings are intrinsically `unsafe` (every accessor
// reads from a raw `Table`). This single generated module — and only it — opts
// back into `unsafe`. No hand-written code in this file uses `unsafe`.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/threading_graph_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use generated::nmp::threading as fb;

use crate::projection::{ThreadEdge, ThreadingSnapshot};
use crate::{ThreadPointer, TimelineBlock};

// #2719 — `THREADING_GRAPH_SCHEMA_ID` / `_FILE_IDENTIFIER` / `_SCHEMA_VERSION`
// are derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("threading_graph_producer_consts.generated.rs");

// --- encode ---------------------------------------------------------------

/// Encode a [`ThreadingSnapshot`] to typed FlatBuffers bytes (with the `NTHR`
/// file identifier). `edges` order is preserved verbatim (event id ascending,
/// as the projection emits it).
#[must_use]
pub fn encode_threading_snapshot(snapshot: &ThreadingSnapshot) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let edge_offsets: Vec<WIPOffset<fb::ThreadEdge<'_>>> = snapshot
        .edges
        .iter()
        .map(|edge| encode_edge(&mut fbb, edge))
        .collect();
    let edges = fbb.create_vector(&edge_offsets);

    let block_offsets: Vec<WIPOffset<fb::TimelineBlockEntry<'_>>> = snapshot
        .blocks
        .iter()
        .map(|block| encode_block(&mut fbb, block))
        .collect();
    let blocks = fbb.create_vector(&block_offsets);

    let pending_offsets: Vec<WIPOffset<&str>> = snapshot
        .pending_ancestor_ids
        .iter()
        .map(|id| fbb.create_string(id))
        .collect();
    let pending_ancestor_ids = fbb.create_vector(&pending_offsets);

    let root = fb::ThreadingSnapshot::create(
        &mut fbb,
        &fb::ThreadingSnapshotArgs {
            schema_version: THREADING_GRAPH_SCHEMA_VERSION,
            edges: Some(edges),
            blocks: Some(blocks),
            pending_ancestor_ids: Some(pending_ancestor_ids),
        },
    );
    fb::finish_threading_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

fn encode_edge<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    edge: &ThreadEdge,
) -> WIPOffset<fb::ThreadEdge<'a>> {
    let event_id = fbb.create_string(&edge.event_id);
    let author_pubkey = fbb.create_string(&edge.author_pubkey);
    let parent = edge.parent.as_ref().map(|p| encode_pointer(fbb, p));
    let root = edge.root.as_ref().map(|p| encode_pointer(fbb, p));
    let parent_author_pubkey = edge
        .parent_author_pubkey
        .as_deref()
        .map(|s| fbb.create_string(s));

    fb::ThreadEdge::create(
        fbb,
        &fb::ThreadEdgeArgs {
            event_id: Some(event_id),
            author_pubkey: Some(author_pubkey),
            kind: edge.kind,
            created_at: edge.created_at,
            parent,
            root,
            parent_author_pubkey,
        },
    )
}

fn encode_pointer<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    pointer: &ThreadPointer,
) -> WIPOffset<fb::ThreadPointer<'a>> {
    match pointer {
        ThreadPointer::Event { id, relay, kind } => {
            let id = fbb.create_string(id);
            let relay = relay.as_deref().map(|s| fbb.create_string(s));
            fb::ThreadPointer::create(
                fbb,
                &fb::ThreadPointerArgs {
                    kind: fb::ThreadPointerKind::Event,
                    id: Some(id),
                    relay,
                    has_kind_hint: kind.is_some(),
                    kind_hint: kind.unwrap_or(0),
                    ..Default::default()
                },
            )
        }
        ThreadPointer::Address { coord, relay, kind } => {
            let coord = fbb.create_string(coord);
            let relay = relay.as_deref().map(|s| fbb.create_string(s));
            fb::ThreadPointer::create(
                fbb,
                &fb::ThreadPointerArgs {
                    kind: fb::ThreadPointerKind::Address,
                    coord: Some(coord),
                    relay,
                    has_kind_hint: kind.is_some(),
                    kind_hint: kind.unwrap_or(0),
                    ..Default::default()
                },
            )
        }
        ThreadPointer::External { uri } => {
            let uri = fbb.create_string(uri);
            fb::ThreadPointer::create(
                fbb,
                &fb::ThreadPointerArgs {
                    kind: fb::ThreadPointerKind::External,
                    uri: Some(uri),
                    ..Default::default()
                },
            )
        }
    }
}

fn encode_block<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    block: &TimelineBlock,
) -> WIPOffset<fb::TimelineBlockEntry<'a>> {
    match block {
        TimelineBlock::Standalone { id, root } => {
            let standalone_id = fbb.create_string(id);
            let root = root.as_ref().map(|p| encode_pointer(fbb, p));
            fb::TimelineBlockEntry::create(
                fbb,
                &fb::TimelineBlockEntryArgs {
                    kind: fb::TimelineBlockKind::Standalone,
                    standalone_id: Some(standalone_id),
                    root,
                    ..Default::default()
                },
            )
        }
        TimelineBlock::Module {
            events,
            has_gap,
            root,
        } => {
            let id_offsets: Vec<WIPOffset<&str>> =
                events.iter().map(|id| fbb.create_string(id)).collect();
            let event_ids = fbb.create_vector(&id_offsets);
            let root = root.as_ref().map(|p| encode_pointer(fbb, p));
            fb::TimelineBlockEntry::create(
                fbb,
                &fb::TimelineBlockEntryArgs {
                    kind: fb::TimelineBlockKind::Module,
                    event_ids: Some(event_ids),
                    has_gap: *has_gap,
                    root,
                    ..Default::default()
                },
            )
        }
    }
}

// --- decode -----------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by
/// [`encode_threading_snapshot`]) back into a [`ThreadingSnapshot`]. Returns
/// an error string on any malformed input or missing required field.
pub fn decode_threading_snapshot(bytes: &[u8]) -> Result<ThreadingSnapshot, String> {
    if bytes.len() < 8 || !fb::threading_snapshot_buffer_has_identifier(bytes) {
        return Err("missing NTHR file identifier".to_string());
    }
    let root = fb::root_as_threading_snapshot(bytes)
        .map_err(|e| format!("not a valid ThreadingSnapshot buffer: {e}"))?;

    let mut edges = Vec::new();
    if let Some(fb_edges) = root.edges() {
        edges.reserve(fb_edges.len());
        for edge in fb_edges.iter() {
            edges.push(decode_edge(edge)?);
        }
    }

    let mut blocks = Vec::new();
    if let Some(fb_blocks) = root.blocks() {
        blocks.reserve(fb_blocks.len());
        for block in fb_blocks.iter() {
            blocks.push(decode_block(block)?);
        }
    }

    let mut pending_ancestor_ids = Vec::new();
    if let Some(fb_pending) = root.pending_ancestor_ids() {
        pending_ancestor_ids.reserve(fb_pending.len());
        for id in fb_pending.iter() {
            pending_ancestor_ids.push(id.to_string());
        }
    }

    Ok(ThreadingSnapshot {
        edges,
        blocks,
        pending_ancestor_ids,
    })
}

fn decode_edge(edge: fb::ThreadEdge<'_>) -> Result<ThreadEdge, String> {
    Ok(ThreadEdge {
        event_id: str_field(edge.event_id(), "ThreadEdge.event_id")?,
        author_pubkey: str_field(edge.author_pubkey(), "ThreadEdge.author_pubkey")?,
        kind: edge.kind(),
        created_at: edge.created_at(),
        parent: edge.parent().map(decode_pointer).transpose()?,
        root: edge.root().map(decode_pointer).transpose()?,
        parent_author_pubkey: edge.parent_author_pubkey().map(str::to_string),
    })
}

fn decode_pointer(pointer: fb::ThreadPointer<'_>) -> Result<ThreadPointer, String> {
    let kind_hint = pointer.has_kind_hint().then(|| pointer.kind_hint());
    match pointer.kind() {
        fb::ThreadPointerKind::Event => Ok(ThreadPointer::Event {
            id: str_field(pointer.id(), "ThreadPointer.id")?,
            relay: pointer.relay().map(str::to_string),
            kind: kind_hint,
        }),
        fb::ThreadPointerKind::Address => Ok(ThreadPointer::Address {
            coord: str_field(pointer.coord(), "ThreadPointer.coord")?,
            relay: pointer.relay().map(str::to_string),
            kind: kind_hint,
        }),
        fb::ThreadPointerKind::External => Ok(ThreadPointer::External {
            uri: str_field(pointer.uri(), "ThreadPointer.uri")?,
        }),
        other => Err(format!("ThreadPointer: unknown kind tag {other:?}")),
    }
}

fn decode_block(block: fb::TimelineBlockEntry<'_>) -> Result<TimelineBlock, String> {
    let root = block.root().map(decode_pointer).transpose()?;
    match block.kind() {
        fb::TimelineBlockKind::Standalone => Ok(TimelineBlock::Standalone {
            id: str_field(block.standalone_id(), "TimelineBlockEntry.standalone_id")?,
            root,
        }),
        fb::TimelineBlockKind::Module => {
            let mut events = Vec::new();
            if let Some(fb_events) = block.event_ids() {
                events.reserve(fb_events.len());
                for id in fb_events.iter() {
                    events.push(id.to_string());
                }
            }
            Ok(TimelineBlock::Module {
                events,
                has_gap: block.has_gap(),
                root,
            })
        }
        other => Err(format!("TimelineBlockEntry: unknown kind tag {other:?}")),
    }
}

/// Require a present string field; an absent FlatBuffers string on a mandatory
/// slot is a decode error.
fn str_field(value: Option<&str>, ctx: &str) -> Result<String, String> {
    value
        .map(str::to_string)
        .ok_or_else(|| format!("{ctx}: missing required string field"))
}

#[cfg(test)]
#[path = "threading_graph_fb_tests.rs"]
mod tests;
