// @generated by `cargo run -p nmp-codegen -- gen builtin-keys`. DO NOT EDIT.
//
// Source of truth: crates/nmp-codegen/src/swift_projections_registry.rs
//   (SNAPSHOT_PROJECTIONS entries tagged ProjectionTier::KernelBuiltin, unioned
//    with KERNEL_BUILTINS_WITHOUT_SHELL_DECODER). Regenerate + verify drift via
//   `.github/workflows/codegen-drift.yml` (nmp gen builtin-keys --check).
//
// The kernel's `builtin_projection_keys_const_matches_runtime` test pins this
// const against the actual `make_update` emission, so the generated list, the
// registry, and the producer cannot diverge.
pub const KERNEL_BUILTIN_PROJECTION_KEYS: &[&str] = &[
    "accounts",
    "action_lifecycle",
    "action_results",
    "action_stages",
    "active_account",
    "claimed_events",
    "configured_relays",
    "outbox_summary",
    "profile",
    "publish_outbox",
    "publish_queue",
    "refs.event",
    "refs.profile",
    "relay_diagnostics",
    "relay_role_options",
    "settings_hub",
    "signed_events",
];
