//! ADR-0064 §3 (#1783 / #2197) — the component-registered flat-table builders.
//!
//! Split out of the sibling [`super::table`] (`registry/table.rs`) as a
//! size-management seam (AGENTS.md / V-12): the parent `ACTION_BUILDERS` slice
//! together with these would exceed the 500-LOC ceiling. These builders are the
//! `ActionDefaultTier::ComponentRegistered` rows — namespaces that an app-
//! component crate (`nmp-blossom`, `nmp-relations`) wires at app-assembly time
//! rather than `nmp-defaults`. They are otherwise ordinary flat-table builders
//! and render through the same emitter `render_one` path as
//! [`super::ACTION_BUILDERS`]; the emitters iterate them in a separate pass.
//!
//! The native action-boundary gate (`ci/check_native_action_boundary.py`) scans
//! `registry/*.rs`, so these namespace literals stay visible to the gate.

use super::{ActionBuilder, FieldKind, PayloadField};

/// Component-registered flat-table builders (tier `ComponentRegistered`).
///
/// Emitted by the platform emitters in a dedicated pass right after
/// [`super::ACTION_BUILDERS`] (and before the publish/marmot union builders), so
/// the generated byte output is identical to listing them at the tail of the
/// flat table.
pub const COMPONENT_BUILDERS: &[ActionBuilder] = &[
    // nmp-blossom — BUD-02 file upload (upload.fbs / UploadPayload).
    // ComponentRegistered (not wired by nmp-defaults).
    ActionBuilder {
        namespace: "nmp.blossom.upload",
        method: "blossomUpload",
        fields: &[
            PayloadField {
                name: "filePath",
                kind: FieldKind::Str,
                optional: false,
            },
            PayloadField {
                name: "contentType",
                kind: FieldKind::Str,
                optional: true,
            },
            PayloadField {
                name: "servers",
                kind: FieldKind::StrVec,
                optional: true,
            },
            PayloadField {
                name: "signerPubkey",
                kind: FieldKind::Str,
                optional: true,
            },
        ],
        doc: "Upload a file via BUD-02 to one or more Blossom servers.",
    },
    // nmp-relations — claim/release tailing interest for a note's visible relations
    // (visible_note_relations_action.fbs / VisibleNoteRelationsPayload).
    // ComponentRegistered (not wired by nmp-defaults).
    ActionBuilder {
        namespace: "nmp.nip01.visible_note_relations",
        method: "visibleNoteRelations",
        fields: &[
            PayloadField {
                name: "op",
                kind: FieldKind::Ubyte,
                optional: false,
            },
            PayloadField {
                name: "eventId",
                kind: FieldKind::Str,
                optional: false,
            },
            PayloadField {
                name: "consumerId",
                kind: FieldKind::Str,
                optional: false,
            },
        ],
        doc: "Claim or release the tailing interest for a note's visible relations (NIP-01).",
    },
];
