// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip17

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DmInboxSnapshot : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DmInboxSnapshot {
        __init(_i, _bb)
        return this
    }
    fun conversations(j: Int) : nmp.nip17.DmConversation? = conversations(nmp.nip17.DmConversation(), j)
    fun conversations(obj: nmp.nip17.DmConversation, j: Int) : nmp.nip17.DmConversation? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val conversationsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val decryptState : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val decryptStateAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun decryptStateInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val undecryptedCount : Int
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDmInboxSnapshot(_bb: ByteBuffer): DmInboxSnapshot = getRootAsDmInboxSnapshot(_bb, DmInboxSnapshot())
        fun getRootAsDmInboxSnapshot(_bb: ByteBuffer, obj: DmInboxSnapshot): DmInboxSnapshot {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun DmInboxSnapshotBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "NDMI")
        fun createDmInboxSnapshot(builder: FlatBufferBuilder, conversationsOffset: Int, decryptStateOffset: Int, undecryptedCount: Int) : Int {
            builder.startTable(3)
            addUndecryptedCount(builder, undecryptedCount)
            addDecryptState(builder, decryptStateOffset)
            addConversations(builder, conversationsOffset)
            return endDmInboxSnapshot(builder)
        }
        fun startDmInboxSnapshot(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addConversations(builder: FlatBufferBuilder, conversations: Int) = builder.addOffset(0, conversations, 0)
        fun createConversationsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startConversationsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addDecryptState(builder: FlatBufferBuilder, decryptState: Int) = builder.addOffset(1, decryptState, 0)
        fun addUndecryptedCount(builder: FlatBufferBuilder, undecryptedCount: Int) = builder.addInt(2, undecryptedCount, 0)
        fun endDmInboxSnapshot(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishDmInboxSnapshotBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "NDMI")
        fun finishSizePrefixedDmInboxSnapshotBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "NDMI")
    }
}
