// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip17

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DmMessage : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DmMessage {
        __init(_i, _bb)
        return this
    }
    val id : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val senderPubkey : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val senderPubkeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun senderPubkeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val content : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val contentAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun contentInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val createdAt : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val hasReplyTo : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val replyTo : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val replyToAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun replyToInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val isOutgoing : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun sourceRelays(j: Int) : String? {
        val o = __offset(18)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val sourceRelaysLength : Int
        get() {
            val o = __offset(18); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDmMessage(_bb: ByteBuffer): DmMessage = getRootAsDmMessage(_bb, DmMessage())
        fun getRootAsDmMessage(_bb: ByteBuffer, obj: DmMessage): DmMessage {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDmMessage(builder: FlatBufferBuilder, idOffset: Int, senderPubkeyOffset: Int, contentOffset: Int, createdAt: ULong, hasReplyTo: Boolean, replyToOffset: Int, isOutgoing: Boolean, sourceRelaysOffset: Int) : Int {
            builder.startTable(8)
            addCreatedAt(builder, createdAt)
            addSourceRelays(builder, sourceRelaysOffset)
            addReplyTo(builder, replyToOffset)
            addContent(builder, contentOffset)
            addSenderPubkey(builder, senderPubkeyOffset)
            addId(builder, idOffset)
            addIsOutgoing(builder, isOutgoing)
            addHasReplyTo(builder, hasReplyTo)
            return endDmMessage(builder)
        }
        fun startDmMessage(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addOffset(0, id, 0)
        fun addSenderPubkey(builder: FlatBufferBuilder, senderPubkey: Int) = builder.addOffset(1, senderPubkey, 0)
        fun addContent(builder: FlatBufferBuilder, content: Int) = builder.addOffset(2, content, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: ULong) = builder.addLong(3, createdAt.toLong(), 0)
        fun addHasReplyTo(builder: FlatBufferBuilder, hasReplyTo: Boolean) = builder.addBoolean(4, hasReplyTo, false)
        fun addReplyTo(builder: FlatBufferBuilder, replyTo: Int) = builder.addOffset(5, replyTo, 0)
        fun addIsOutgoing(builder: FlatBufferBuilder, isOutgoing: Boolean) = builder.addBoolean(6, isOutgoing, false)
        fun addSourceRelays(builder: FlatBufferBuilder, sourceRelays: Int) = builder.addOffset(7, sourceRelays, 0)
        fun createSourceRelaysVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startSourceRelaysVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endDmMessage(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
