// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ActionStageEntry : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ActionStageEntry {
        __init(_i, _bb)
        return this
    }
    val stage : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stageAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun stageInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val hasReason : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val reason : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val reasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun reasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val atMs : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val hasDetail : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val detail : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val detailAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun detailInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsActionStageEntry(_bb: ByteBuffer): ActionStageEntry = getRootAsActionStageEntry(_bb, ActionStageEntry())
        fun getRootAsActionStageEntry(_bb: ByteBuffer, obj: ActionStageEntry): ActionStageEntry {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createActionStageEntry(builder: FlatBufferBuilder, stageOffset: Int, hasReason: Boolean, reasonOffset: Int, atMs: ULong, hasDetail: Boolean, detailOffset: Int) : Int {
            builder.startTable(6)
            addAtMs(builder, atMs)
            addDetail(builder, detailOffset)
            addReason(builder, reasonOffset)
            addStage(builder, stageOffset)
            addHasDetail(builder, hasDetail)
            addHasReason(builder, hasReason)
            return endActionStageEntry(builder)
        }
        fun startActionStageEntry(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addStage(builder: FlatBufferBuilder, stage: Int) = builder.addOffset(0, stage, 0)
        fun addHasReason(builder: FlatBufferBuilder, hasReason: Boolean) = builder.addBoolean(1, hasReason, false)
        fun addReason(builder: FlatBufferBuilder, reason: Int) = builder.addOffset(2, reason, 0)
        fun addAtMs(builder: FlatBufferBuilder, atMs: ULong) = builder.addLong(3, atMs.toLong(), 0)
        fun addHasDetail(builder: FlatBufferBuilder, hasDetail: Boolean) = builder.addBoolean(4, hasDetail, false)
        fun addDetail(builder: FlatBufferBuilder, detail: Int) = builder.addOffset(5, detail, 0)
        fun endActionStageEntry(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
