// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ActionResult : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ActionResult {
        __init(_i, _bb)
        return this
    }
    val correlationId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val correlationIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun correlationIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val status : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val statusAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun statusInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val hasError : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val error : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val errorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun errorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val hasResult : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val result : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val resultAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun resultInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val hasEventId : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val eventId : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val eventIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(18, 1)
    fun eventIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 18, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsActionResult(_bb: ByteBuffer): ActionResult = getRootAsActionResult(_bb, ActionResult())
        fun getRootAsActionResult(_bb: ByteBuffer, obj: ActionResult): ActionResult {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createActionResult(builder: FlatBufferBuilder, correlationIdOffset: Int, statusOffset: Int, hasError: Boolean, errorOffset: Int, hasResult: Boolean, resultOffset: Int, hasEventId: Boolean, eventIdOffset: Int) : Int {
            builder.startTable(8)
            addEventId(builder, eventIdOffset)
            addResult(builder, resultOffset)
            addError(builder, errorOffset)
            addStatus(builder, statusOffset)
            addCorrelationId(builder, correlationIdOffset)
            addHasEventId(builder, hasEventId)
            addHasResult(builder, hasResult)
            addHasError(builder, hasError)
            return endActionResult(builder)
        }
        fun startActionResult(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addCorrelationId(builder: FlatBufferBuilder, correlationId: Int) = builder.addOffset(0, correlationId, 0)
        fun addStatus(builder: FlatBufferBuilder, status: Int) = builder.addOffset(1, status, 0)
        fun addHasError(builder: FlatBufferBuilder, hasError: Boolean) = builder.addBoolean(2, hasError, false)
        fun addError(builder: FlatBufferBuilder, error: Int) = builder.addOffset(3, error, 0)
        fun addHasResult(builder: FlatBufferBuilder, hasResult: Boolean) = builder.addBoolean(4, hasResult, false)
        fun addResult(builder: FlatBufferBuilder, result: Int) = builder.addOffset(5, result, 0)
        fun addHasEventId(builder: FlatBufferBuilder, hasEventId: Boolean) = builder.addBoolean(6, hasEventId, false)
        fun addEventId(builder: FlatBufferBuilder, eventId: Int) = builder.addOffset(7, eventId, 0)
        fun endActionResult(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
