// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class LifecycleEntry : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LifecycleEntry {
        __init(_i, _bb)
        return this
    }
    val correlationId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val correlationIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun correlationIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val stage : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val stageAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun stageInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val hasReason : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val reason : String?
        get() {
            val o = __offset(10)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val reasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun reasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsLifecycleEntry(_bb: ByteBuffer): LifecycleEntry = getRootAsLifecycleEntry(_bb, LifecycleEntry())
        fun getRootAsLifecycleEntry(_bb: ByteBuffer, obj: LifecycleEntry): LifecycleEntry {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun LifecycleEntryBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "KALC")
        fun createLifecycleEntry(builder: FlatBufferBuilder, correlationIdOffset: Int, stageOffset: Int, hasReason: Boolean, reasonOffset: Int) : Int {
            builder.startTable(4)
            addReason(builder, reasonOffset)
            addStage(builder, stageOffset)
            addCorrelationId(builder, correlationIdOffset)
            addHasReason(builder, hasReason)
            return endLifecycleEntry(builder)
        }
        fun startLifecycleEntry(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addCorrelationId(builder: FlatBufferBuilder, correlationId: Int) = builder.addOffset(0, correlationId, 0)
        fun addStage(builder: FlatBufferBuilder, stage: Int) = builder.addOffset(1, stage, 0)
        fun addHasReason(builder: FlatBufferBuilder, hasReason: Boolean) = builder.addBoolean(2, hasReason, false)
        fun addReason(builder: FlatBufferBuilder, reason: Int) = builder.addOffset(3, reason, 0)
        fun endLifecycleEntry(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
