// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RelayDiagnosticsInfo : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelayDiagnosticsInfo {
        __init(_i, _bb)
        return this
    }
    val hasName : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val name : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val hasDescription : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val description : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val descriptionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun descriptionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val hasIcon : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val icon : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val iconAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun iconInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val hasPubkey : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val pubkey : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val pubkeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(18, 1)
    fun pubkeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 18, 1)
    val hasContact : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val contact : String?
        get() {
            val o = __offset(22)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val contactAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(22, 1)
    fun contactInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 22, 1)
    val hasSoftware : Boolean
        get() {
            val o = __offset(24)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val software : String?
        get() {
            val o = __offset(26)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val softwareAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(26, 1)
    fun softwareInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 26, 1)
    val hasVersion : Boolean
        get() {
            val o = __offset(28)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val version : String?
        get() {
            val o = __offset(30)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val versionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(30, 1)
    fun versionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 30, 1)
    fun supportedNips(j: Int) : UInt {
        val o = __offset(32)
        return if (o != 0) {
            bb.getInt(__vector(o) + j * 4).toUInt()
        } else {
            0u
        }
    }
    val supportedNipsLength : Int
        get() {
            val o = __offset(32); return if (o != 0) __vector_len(o) else 0
        }
    val supportedNipsAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(32, 4)
    fun supportedNipsInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 32, 4)
    val hasPaymentRequired : Boolean
        get() {
            val o = __offset(34)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val paymentRequired : Boolean
        get() {
            val o = __offset(36)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hasAuthRequired : Boolean
        get() {
            val o = __offset(38)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val authRequired : Boolean
        get() {
            val o = __offset(40)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hasRestrictedWrites : Boolean
        get() {
            val o = __offset(42)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val restrictedWrites : Boolean
        get() {
            val o = __offset(44)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelayDiagnosticsInfo(_bb: ByteBuffer): RelayDiagnosticsInfo = getRootAsRelayDiagnosticsInfo(_bb, RelayDiagnosticsInfo())
        fun getRootAsRelayDiagnosticsInfo(_bb: ByteBuffer, obj: RelayDiagnosticsInfo): RelayDiagnosticsInfo {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRelayDiagnosticsInfo(builder: FlatBufferBuilder, hasName: Boolean, nameOffset: Int, hasDescription: Boolean, descriptionOffset: Int, hasIcon: Boolean, iconOffset: Int, hasPubkey: Boolean, pubkeyOffset: Int, hasContact: Boolean, contactOffset: Int, hasSoftware: Boolean, softwareOffset: Int, hasVersion: Boolean, versionOffset: Int, supportedNipsOffset: Int, hasPaymentRequired: Boolean, paymentRequired: Boolean, hasAuthRequired: Boolean, authRequired: Boolean, hasRestrictedWrites: Boolean, restrictedWrites: Boolean) : Int {
            builder.startTable(21)
            addSupportedNips(builder, supportedNipsOffset)
            addVersion(builder, versionOffset)
            addSoftware(builder, softwareOffset)
            addContact(builder, contactOffset)
            addPubkey(builder, pubkeyOffset)
            addIcon(builder, iconOffset)
            addDescription(builder, descriptionOffset)
            addName(builder, nameOffset)
            addRestrictedWrites(builder, restrictedWrites)
            addHasRestrictedWrites(builder, hasRestrictedWrites)
            addAuthRequired(builder, authRequired)
            addHasAuthRequired(builder, hasAuthRequired)
            addPaymentRequired(builder, paymentRequired)
            addHasPaymentRequired(builder, hasPaymentRequired)
            addHasVersion(builder, hasVersion)
            addHasSoftware(builder, hasSoftware)
            addHasContact(builder, hasContact)
            addHasPubkey(builder, hasPubkey)
            addHasIcon(builder, hasIcon)
            addHasDescription(builder, hasDescription)
            addHasName(builder, hasName)
            return endRelayDiagnosticsInfo(builder)
        }
        fun startRelayDiagnosticsInfo(builder: FlatBufferBuilder) = builder.startTable(21)
        fun addHasName(builder: FlatBufferBuilder, hasName: Boolean) = builder.addBoolean(0, hasName, false)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(1, name, 0)
        fun addHasDescription(builder: FlatBufferBuilder, hasDescription: Boolean) = builder.addBoolean(2, hasDescription, false)
        fun addDescription(builder: FlatBufferBuilder, description: Int) = builder.addOffset(3, description, 0)
        fun addHasIcon(builder: FlatBufferBuilder, hasIcon: Boolean) = builder.addBoolean(4, hasIcon, false)
        fun addIcon(builder: FlatBufferBuilder, icon: Int) = builder.addOffset(5, icon, 0)
        fun addHasPubkey(builder: FlatBufferBuilder, hasPubkey: Boolean) = builder.addBoolean(6, hasPubkey, false)
        fun addPubkey(builder: FlatBufferBuilder, pubkey: Int) = builder.addOffset(7, pubkey, 0)
        fun addHasContact(builder: FlatBufferBuilder, hasContact: Boolean) = builder.addBoolean(8, hasContact, false)
        fun addContact(builder: FlatBufferBuilder, contact: Int) = builder.addOffset(9, contact, 0)
        fun addHasSoftware(builder: FlatBufferBuilder, hasSoftware: Boolean) = builder.addBoolean(10, hasSoftware, false)
        fun addSoftware(builder: FlatBufferBuilder, software: Int) = builder.addOffset(11, software, 0)
        fun addHasVersion(builder: FlatBufferBuilder, hasVersion: Boolean) = builder.addBoolean(12, hasVersion, false)
        fun addVersion(builder: FlatBufferBuilder, version: Int) = builder.addOffset(13, version, 0)
        fun addSupportedNips(builder: FlatBufferBuilder, supportedNips: Int) = builder.addOffset(14, supportedNips, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createSupportedNipsVector(builder: FlatBufferBuilder, data: UIntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addInt(data[i].toInt())
            }
            return builder.endVector()
        }
        fun startSupportedNipsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addHasPaymentRequired(builder: FlatBufferBuilder, hasPaymentRequired: Boolean) = builder.addBoolean(15, hasPaymentRequired, false)
        fun addPaymentRequired(builder: FlatBufferBuilder, paymentRequired: Boolean) = builder.addBoolean(16, paymentRequired, false)
        fun addHasAuthRequired(builder: FlatBufferBuilder, hasAuthRequired: Boolean) = builder.addBoolean(17, hasAuthRequired, false)
        fun addAuthRequired(builder: FlatBufferBuilder, authRequired: Boolean) = builder.addBoolean(18, authRequired, false)
        fun addHasRestrictedWrites(builder: FlatBufferBuilder, hasRestrictedWrites: Boolean) = builder.addBoolean(19, hasRestrictedWrites, false)
        fun addRestrictedWrites(builder: FlatBufferBuilder, restrictedWrites: Boolean) = builder.addBoolean(20, restrictedWrites, false)
        fun endRelayDiagnosticsInfo(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
