// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RelayRoleOption : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelayRoleOption {
        __init(_i, _bb)
        return this
    }
    val value : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val valueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun valueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val tint : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val tintAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun tintInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val isDefault : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelayRoleOption(_bb: ByteBuffer): RelayRoleOption = getRootAsRelayRoleOption(_bb, RelayRoleOption())
        fun getRootAsRelayRoleOption(_bb: ByteBuffer, obj: RelayRoleOption): RelayRoleOption {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRelayRoleOption(builder: FlatBufferBuilder, valueOffset: Int, tintOffset: Int, isDefault: Boolean) : Int {
            builder.startTable(4)
            addTint(builder, tintOffset)
            addValue(builder, valueOffset)
            addIsDefault(builder, isDefault)
            return endRelayRoleOption(builder)
        }
        fun startRelayRoleOption(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(0, value, 0)
        fun addTint(builder: FlatBufferBuilder, tint: Int) = builder.addOffset(2, tint, 0)
        fun addIsDefault(builder: FlatBufferBuilder, isDefault: Boolean) = builder.addBoolean(3, isDefault, false)
        fun endRelayRoleOption(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
