// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RelayDiagnosticsWireSub : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelayDiagnosticsWireSub {
        __init(_i, _bb)
        return this
    }
    val wireId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val wireIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun wireIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val shortWireId : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val shortWireIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun shortWireIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val relayUrl : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val relayUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun relayUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val filterSummary : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val filterSummaryAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun filterSummaryInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val stateLabel : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stateLabelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun stateLabelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val stateTone : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stateToneAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun stateToneInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val consumerCountLabel : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val consumerCountLabelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun consumerCountLabelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val hasEventsRxDisplay : Boolean
        get() {
            val o = __offset(18)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val eventsRxDisplay : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val eventsRxDisplayAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(20, 1)
    fun eventsRxDisplayInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 20, 1)
    val eoseObserved : Boolean
        get() {
            val o = __offset(22)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val openedDisplay : String?
        get() {
            val o = __offset(24)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val openedDisplayAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(24, 1)
    fun openedDisplayInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 24, 1)
    val hasLastEventDisplay : Boolean
        get() {
            val o = __offset(26)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lastEventDisplay : String?
        get() {
            val o = __offset(28)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lastEventDisplayAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(28, 1)
    fun lastEventDisplayInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 28, 1)
    val hasEoseDisplay : Boolean
        get() {
            val o = __offset(30)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val eoseDisplay : String?
        get() {
            val o = __offset(32)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val eoseDisplayAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(32, 1)
    fun eoseDisplayInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 32, 1)
    val hasCloseReason : Boolean
        get() {
            val o = __offset(34)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val closeReason : String?
        get() {
            val o = __offset(36)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val closeReasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(36, 1)
    fun closeReasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 36, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelayDiagnosticsWireSub(_bb: ByteBuffer): RelayDiagnosticsWireSub = getRootAsRelayDiagnosticsWireSub(_bb, RelayDiagnosticsWireSub())
        fun getRootAsRelayDiagnosticsWireSub(_bb: ByteBuffer, obj: RelayDiagnosticsWireSub): RelayDiagnosticsWireSub {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRelayDiagnosticsWireSub(builder: FlatBufferBuilder, wireIdOffset: Int, shortWireIdOffset: Int, relayUrlOffset: Int, filterSummaryOffset: Int, stateLabelOffset: Int, stateToneOffset: Int, consumerCountLabelOffset: Int, hasEventsRxDisplay: Boolean, eventsRxDisplayOffset: Int, eoseObserved: Boolean, openedDisplayOffset: Int, hasLastEventDisplay: Boolean, lastEventDisplayOffset: Int, hasEoseDisplay: Boolean, eoseDisplayOffset: Int, hasCloseReason: Boolean, closeReasonOffset: Int) : Int {
            builder.startTable(17)
            addCloseReason(builder, closeReasonOffset)
            addEoseDisplay(builder, eoseDisplayOffset)
            addLastEventDisplay(builder, lastEventDisplayOffset)
            addOpenedDisplay(builder, openedDisplayOffset)
            addEventsRxDisplay(builder, eventsRxDisplayOffset)
            addConsumerCountLabel(builder, consumerCountLabelOffset)
            addStateTone(builder, stateToneOffset)
            addStateLabel(builder, stateLabelOffset)
            addFilterSummary(builder, filterSummaryOffset)
            addRelayUrl(builder, relayUrlOffset)
            addShortWireId(builder, shortWireIdOffset)
            addWireId(builder, wireIdOffset)
            addHasCloseReason(builder, hasCloseReason)
            addHasEoseDisplay(builder, hasEoseDisplay)
            addHasLastEventDisplay(builder, hasLastEventDisplay)
            addEoseObserved(builder, eoseObserved)
            addHasEventsRxDisplay(builder, hasEventsRxDisplay)
            return endRelayDiagnosticsWireSub(builder)
        }
        fun startRelayDiagnosticsWireSub(builder: FlatBufferBuilder) = builder.startTable(17)
        fun addWireId(builder: FlatBufferBuilder, wireId: Int) = builder.addOffset(0, wireId, 0)
        fun addShortWireId(builder: FlatBufferBuilder, shortWireId: Int) = builder.addOffset(1, shortWireId, 0)
        fun addRelayUrl(builder: FlatBufferBuilder, relayUrl: Int) = builder.addOffset(2, relayUrl, 0)
        fun addFilterSummary(builder: FlatBufferBuilder, filterSummary: Int) = builder.addOffset(3, filterSummary, 0)
        fun addStateLabel(builder: FlatBufferBuilder, stateLabel: Int) = builder.addOffset(4, stateLabel, 0)
        fun addStateTone(builder: FlatBufferBuilder, stateTone: Int) = builder.addOffset(5, stateTone, 0)
        fun addConsumerCountLabel(builder: FlatBufferBuilder, consumerCountLabel: Int) = builder.addOffset(6, consumerCountLabel, 0)
        fun addHasEventsRxDisplay(builder: FlatBufferBuilder, hasEventsRxDisplay: Boolean) = builder.addBoolean(7, hasEventsRxDisplay, false)
        fun addEventsRxDisplay(builder: FlatBufferBuilder, eventsRxDisplay: Int) = builder.addOffset(8, eventsRxDisplay, 0)
        fun addEoseObserved(builder: FlatBufferBuilder, eoseObserved: Boolean) = builder.addBoolean(9, eoseObserved, false)
        fun addOpenedDisplay(builder: FlatBufferBuilder, openedDisplay: Int) = builder.addOffset(10, openedDisplay, 0)
        fun addHasLastEventDisplay(builder: FlatBufferBuilder, hasLastEventDisplay: Boolean) = builder.addBoolean(11, hasLastEventDisplay, false)
        fun addLastEventDisplay(builder: FlatBufferBuilder, lastEventDisplay: Int) = builder.addOffset(12, lastEventDisplay, 0)
        fun addHasEoseDisplay(builder: FlatBufferBuilder, hasEoseDisplay: Boolean) = builder.addBoolean(13, hasEoseDisplay, false)
        fun addEoseDisplay(builder: FlatBufferBuilder, eoseDisplay: Int) = builder.addOffset(14, eoseDisplay, 0)
        fun addHasCloseReason(builder: FlatBufferBuilder, hasCloseReason: Boolean) = builder.addBoolean(15, hasCloseReason, false)
        fun addCloseReason(builder: FlatBufferBuilder, closeReason: Int) = builder.addOffset(16, closeReason, 0)
        fun endRelayDiagnosticsWireSub(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
