// automatically generated by the FlatBuffers compiler, do not modify
// Schema updated for issue #1493: removed presentation-formatting fields
// (shortUrl, roleLabel, connectionLabel, authLabel, totalEventsDisplay,
//  hasBytesRxDisplay/bytesRxDisplay, hasBytesTxDisplay/bytesTxDisplay,
//  discoveryKindsLabel); added raw fields (role, connection, auth as strings;
//  bytesRx, bytesTx as ulong; discoveryKinds as [ulong]).

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RelayDiagnosticsRow : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelayDiagnosticsRow {
        __init(_i, _bb)
        return this
    }
    val relayUrl : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val relayUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun relayUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    /** Raw role string from Rust (e.g. "content", "indexer", "both"). Shell formats. */
    val role : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val roleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun roleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val roleTone : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val roleToneAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun roleToneInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    /** Raw connection string from Rust (e.g. "connected", "closed"). Shell formats. */
    val connection : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val connectionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun connectionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val connectionTone : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val connectionToneAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun connectionToneInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    /** Raw auth string from Rust (e.g. "ok", "pending", "—"). Shell formats. */
    val auth : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun authInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val authTone : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authToneAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun authToneInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val totalSubCount : UInt
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val activeSubCount : UInt
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val eosedSubCount : UInt
        get() {
            val o = __offset(22)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val totalEventsRx : ULong
        get() {
            val o = __offset(24)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val reconnectCount : UInt
        get() {
            val o = __offset(26)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    /** Raw bytes received counter. Shell derives display string. */
    val bytesRx : ULong
        get() {
            val o = __offset(28)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    /** Raw bytes transmitted counter. Shell derives display string. */
    val bytesTx : ULong
        get() {
            val o = __offset(30)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val lastConnectedMs : ULong
        get() {
            val o = __offset(32)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val lastEventMs : ULong
        get() {
            val o = __offset(34)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val hasLastNotice : Boolean
        get() {
            val o = __offset(36)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lastNotice : String?
        get() {
            val o = __offset(38)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lastNoticeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(38, 1)
    fun lastNoticeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 38, 1)
    val noticeCount : ULong
        get() {
            val o = __offset(40)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    fun notices(j: Int) : nmp.kernel.RelayDiagnosticsNotice? = notices(nmp.kernel.RelayDiagnosticsNotice(), j)
    fun notices(obj: nmp.kernel.RelayDiagnosticsNotice, j: Int) : nmp.kernel.RelayDiagnosticsNotice? {
        val o = __offset(42)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val noticesLength : Int
        get() {
            val o = __offset(42); return if (o != 0) __vector_len(o) else 0
        }
    val hasLastError : Boolean
        get() {
            val o = __offset(44)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lastError : String?
        get() {
            val o = __offset(46)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lastErrorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(46, 1)
    fun lastErrorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 46, 1)
    fun wireSubs(j: Int) : nmp.kernel.RelayDiagnosticsWireSub? = wireSubs(nmp.kernel.RelayDiagnosticsWireSub(), j)
    fun wireSubs(obj: nmp.kernel.RelayDiagnosticsWireSub, j: Int) : nmp.kernel.RelayDiagnosticsWireSub? {
        val o = __offset(48)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val wireSubsLength : Int
        get() {
            val o = __offset(48); return if (o != 0) __vector_len(o) else 0
        }
    val info : nmp.kernel.RelayDiagnosticsInfo? get() = info(nmp.kernel.RelayDiagnosticsInfo())
    fun info(obj: nmp.kernel.RelayDiagnosticsInfo) : nmp.kernel.RelayDiagnosticsInfo? {
        val o = __offset(50)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    /** Raw kind numbers for discovery (NIP-65 etc). Shell formats for display. */
    fun discoveryKinds(j: Int) : ULong {
        val o = __offset(52)
        return if (o != 0) {
            __vector(o).let { bb.getLong(it + j * 8).toULong() }
        } else {
            0UL
        }
    }
    val discoveryKindsLength : Int
        get() {
            val o = __offset(52); return if (o != 0) __vector_len(o) else 0
        }
    fun reasons(j: Int) : nmp.kernel.RelayConnectionReason? = reasons(nmp.kernel.RelayConnectionReason(), j)
    fun reasons(obj: nmp.kernel.RelayConnectionReason, j: Int) : nmp.kernel.RelayConnectionReason? {
        val o = __offset(54)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val reasonsLength : Int
        get() {
            val o = __offset(54); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelayDiagnosticsRow(_bb: ByteBuffer): RelayDiagnosticsRow = getRootAsRelayDiagnosticsRow(_bb, RelayDiagnosticsRow())
        fun getRootAsRelayDiagnosticsRow(_bb: ByteBuffer, obj: RelayDiagnosticsRow): RelayDiagnosticsRow {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRelayDiagnosticsRow(builder: FlatBufferBuilder, relayUrlOffset: Int, roleOffset: Int, roleToneOffset: Int, connectionOffset: Int, connectionToneOffset: Int, authOffset: Int, authToneOffset: Int, totalSubCount: UInt, activeSubCount: UInt, eosedSubCount: UInt, totalEventsRx: ULong, reconnectCount: UInt, bytesRx: ULong, bytesTx: ULong, lastConnectedMs: ULong, lastEventMs: ULong, hasLastNotice: Boolean, lastNoticeOffset: Int, noticeCount: ULong, noticesOffset: Int, hasLastError: Boolean, lastErrorOffset: Int, wireSubsOffset: Int, infoOffset: Int, discoveryKindsOffset: Int, reasonsOffset: Int) : Int {
            builder.startTable(26)
            addNoticeCount(builder, noticeCount)
            addLastEventMs(builder, lastEventMs)
            addLastConnectedMs(builder, lastConnectedMs)
            addBytesTx(builder, bytesTx)
            addBytesRx(builder, bytesRx)
            addTotalEventsRx(builder, totalEventsRx)
            addReasons(builder, reasonsOffset)
            addDiscoveryKinds(builder, discoveryKindsOffset)
            addInfo(builder, infoOffset)
            addWireSubs(builder, wireSubsOffset)
            addLastError(builder, lastErrorOffset)
            addNotices(builder, noticesOffset)
            addLastNotice(builder, lastNoticeOffset)
            addReconnectCount(builder, reconnectCount)
            addEosedSubCount(builder, eosedSubCount)
            addActiveSubCount(builder, activeSubCount)
            addTotalSubCount(builder, totalSubCount)
            addAuthTone(builder, authToneOffset)
            addAuth(builder, authOffset)
            addConnectionTone(builder, connectionToneOffset)
            addConnection(builder, connectionOffset)
            addRoleTone(builder, roleToneOffset)
            addRole(builder, roleOffset)
            addRelayUrl(builder, relayUrlOffset)
            addHasLastError(builder, hasLastError)
            addHasLastNotice(builder, hasLastNotice)
            return endRelayDiagnosticsRow(builder)
        }
        fun startRelayDiagnosticsRow(builder: FlatBufferBuilder) = builder.startTable(26)
        fun addRelayUrl(builder: FlatBufferBuilder, relayUrl: Int) = builder.addOffset(0, relayUrl, 0)
        fun addRole(builder: FlatBufferBuilder, role: Int) = builder.addOffset(1, role, 0)
        fun addRoleTone(builder: FlatBufferBuilder, roleTone: Int) = builder.addOffset(2, roleTone, 0)
        fun addConnection(builder: FlatBufferBuilder, connection: Int) = builder.addOffset(3, connection, 0)
        fun addConnectionTone(builder: FlatBufferBuilder, connectionTone: Int) = builder.addOffset(4, connectionTone, 0)
        fun addAuth(builder: FlatBufferBuilder, auth: Int) = builder.addOffset(5, auth, 0)
        fun addAuthTone(builder: FlatBufferBuilder, authTone: Int) = builder.addOffset(6, authTone, 0)
        fun addTotalSubCount(builder: FlatBufferBuilder, totalSubCount: UInt) = builder.addInt(7, totalSubCount.toInt(), 0)
        fun addActiveSubCount(builder: FlatBufferBuilder, activeSubCount: UInt) = builder.addInt(8, activeSubCount.toInt(), 0)
        fun addEosedSubCount(builder: FlatBufferBuilder, eosedSubCount: UInt) = builder.addInt(9, eosedSubCount.toInt(), 0)
        fun addTotalEventsRx(builder: FlatBufferBuilder, totalEventsRx: ULong) = builder.addLong(10, totalEventsRx.toLong(), 0)
        fun addReconnectCount(builder: FlatBufferBuilder, reconnectCount: UInt) = builder.addInt(11, reconnectCount.toInt(), 0)
        fun addBytesRx(builder: FlatBufferBuilder, bytesRx: ULong) = builder.addLong(12, bytesRx.toLong(), 0)
        fun addBytesTx(builder: FlatBufferBuilder, bytesTx: ULong) = builder.addLong(13, bytesTx.toLong(), 0)
        fun addLastConnectedMs(builder: FlatBufferBuilder, lastConnectedMs: ULong) = builder.addLong(14, lastConnectedMs.toLong(), 0)
        fun addLastEventMs(builder: FlatBufferBuilder, lastEventMs: ULong) = builder.addLong(15, lastEventMs.toLong(), 0)
        fun addHasLastNotice(builder: FlatBufferBuilder, hasLastNotice: Boolean) = builder.addBoolean(16, hasLastNotice, false)
        fun addLastNotice(builder: FlatBufferBuilder, lastNotice: Int) = builder.addOffset(17, lastNotice, 0)
        fun addNoticeCount(builder: FlatBufferBuilder, noticeCount: ULong) = builder.addLong(18, noticeCount.toLong(), 0)
        fun addNotices(builder: FlatBufferBuilder, notices: Int) = builder.addOffset(19, notices, 0)
        fun createNoticesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNoticesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addHasLastError(builder: FlatBufferBuilder, hasLastError: Boolean) = builder.addBoolean(20, hasLastError, false)
        fun addLastError(builder: FlatBufferBuilder, lastError: Int) = builder.addOffset(21, lastError, 0)
        fun addWireSubs(builder: FlatBufferBuilder, wireSubs: Int) = builder.addOffset(22, wireSubs, 0)
        fun createWireSubsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startWireSubsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addInfo(builder: FlatBufferBuilder, info: Int) = builder.addOffset(23, info, 0)
        fun addDiscoveryKinds(builder: FlatBufferBuilder, discoveryKinds: Int) = builder.addOffset(24, discoveryKinds, 0)
        fun createDiscoveryKindsVector(builder: FlatBufferBuilder, data: LongArray) : Int {
            builder.startVector(8, data.size, 8)
            for (i in data.size - 1 downTo 0) {
                builder.addLong(data[i])
            }
            return builder.endVector()
        }
        fun startDiscoveryKindsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(8, numElems, 8)
        fun addReasons(builder: FlatBufferBuilder, reasons: Int) = builder.addOffset(25, reasons, 0)
        fun createReasonsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startReasonsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endRelayDiagnosticsRow(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
