// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RelayDiagnosticsWireSub : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelayDiagnosticsWireSub {
        __init(_i, _bb)
        return this
    }
    val wireId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val shortWireId : String?
        get() {
            val o = __offset(6)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val relayUrl : String?
        get() {
            val o = __offset(8)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val filterSummary : String?
        get() {
            val o = __offset(10)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val stateLabel : String?
        get() {
            val o = __offset(12)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val stateTone : String?
        get() {
            val o = __offset(14)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val consumerCountLabel : String?
        get() {
            val o = __offset(16)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val hasEventsRxDisplay : Boolean
        get() {
            val o = __offset(18)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val eventsRxDisplay : String?
        get() {
            val o = __offset(20)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val eoseObserved : Boolean
        get() {
            val o = __offset(22)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val openedDisplay : String?
        get() {
            val o = __offset(24)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val hasLastEventDisplay : Boolean
        get() {
            val o = __offset(26)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lastEventDisplay : String?
        get() {
            val o = __offset(28)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val hasEoseDisplay : Boolean
        get() {
            val o = __offset(30)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val eoseDisplay : String?
        get() {
            val o = __offset(32)
            return if (o != 0) __string(o + bb_pos) else null
        }
    val hasCloseReason : Boolean
        get() {
            val o = __offset(34)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val closeReason : String?
        get() {
            val o = __offset(36)
            return if (o != 0) __string(o + bb_pos) else null
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelayDiagnosticsWireSub(_bb: ByteBuffer): RelayDiagnosticsWireSub = getRootAsRelayDiagnosticsWireSub(_bb, RelayDiagnosticsWireSub())
        fun getRootAsRelayDiagnosticsWireSub(_bb: ByteBuffer, obj: RelayDiagnosticsWireSub): RelayDiagnosticsWireSub {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun RelayDiagnosticsWireSubBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "KRDG")
        fun startRelayDiagnosticsWireSub(builder: FlatBufferBuilder) = builder.startTable(17)
        fun addWireId(builder: FlatBufferBuilder, wireId: Int) = builder.addOffset(0, wireId, 0)
        fun addShortWireId(builder: FlatBufferBuilder, shortWireId: Int) = builder.addOffset(1, shortWireId, 0)
        fun addRelayUrl(builder: FlatBufferBuilder, relayUrl: Int) = builder.addOffset(2, relayUrl, 0)
        fun addFilterSummary(builder: FlatBufferBuilder, filterSummary: Int) = builder.addOffset(3, filterSummary, 0)
        fun addStateLabel(builder: FlatBufferBuilder, stateLabel: Int) = builder.addOffset(4, stateLabel, 0)
        fun addStateTone(builder: FlatBufferBuilder, stateTone: Int) = builder.addOffset(5, stateTone, 0)
        fun addConsumerCountLabel(builder: FlatBufferBuilder, consumerCountLabel: Int) = builder.addOffset(6, consumerCountLabel, 0)
        fun addHasEventsRxDisplay(builder: FlatBufferBuilder, hasEventsRxDisplay: Boolean) = builder.addBoolean(7, hasEventsRxDisplay, false)
        fun addEventsRxDisplay(builder: FlatBufferBuilder, eventsRxDisplay: Int) = builder.addOffset(8, eventsRxDisplay, 0)
        fun addEoseObserved(builder: FlatBufferBuilder, eoseObserved: Boolean) = builder.addBoolean(9, eoseObserved, false)
        fun addOpenedDisplay(builder: FlatBufferBuilder, openedDisplay: Int) = builder.addOffset(10, openedDisplay, 0)
        fun addHasLastEventDisplay(builder: FlatBufferBuilder, hasLastEventDisplay: Boolean) = builder.addBoolean(11, hasLastEventDisplay, false)
        fun addLastEventDisplay(builder: FlatBufferBuilder, lastEventDisplay: Int) = builder.addOffset(12, lastEventDisplay, 0)
        fun addHasEoseDisplay(builder: FlatBufferBuilder, hasEoseDisplay: Boolean) = builder.addBoolean(13, hasEoseDisplay, false)
        fun addEoseDisplay(builder: FlatBufferBuilder, eoseDisplay: Int) = builder.addOffset(14, eoseDisplay, 0)
        fun addHasCloseReason(builder: FlatBufferBuilder, hasCloseReason: Boolean) = builder.addBoolean(15, hasCloseReason, false)
        fun addCloseReason(builder: FlatBufferBuilder, closeReason: Int) = builder.addOffset(16, closeReason, 0)
        fun endRelayDiagnosticsWireSub(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
