import { highlightCurlyLanguage } from "./shared";

const KOTLIN_KEYWORDS = new Set([
  "package",
  "import",
  "public",
  "private",
  "internal",
  "protected",
  "open",
  "final",
  "abstract",
  "sealed",
  "data",
  "object",
  "companion",
  "class",
  "interface",
  "enum",
  "fun",
  "val",
  "var",
  "lateinit",
  "const",
  "this",
  "super",
  "null",
  "true",
  "false",
  "return",
  "if",
  "else",
  "when",
  "for",
  "in",
  "is",
  "as",
  "while",
  "do",
  "try",
  "catch",
  "finally",
  "throw",
  "break",
  "continue",
  "by",
  "where",
  "out",
  "inline",
  "noinline",
  "crossinline",
  "reified",
  "operator",
  "infix",
  "tailrec",
  "vararg",
  "suspend",
  "typealias",
  "init",
  "constructor",
  "override",
  "annotation",
  "@Composable",
  "@Serializable",
  "@SerialName",
  "@JsonClassDiscriminator",
  "@OptIn",
  "@Suppress",
]);

export function highlightKotlin(source: string): string {
  return highlightCurlyLanguage(source, {
    keywords: KOTLIN_KEYWORDS,
    identifierStart: /[A-Za-z_@]/,
    identifierContinue: /[A-Za-z0-9_]/,
    numberContinue: /[0-9_.fFL]/,
    isType: (word) => /^[A-Z][A-Za-z0-9_]*$/.test(word),
  });
}
