import { highlightCurlyLanguage } from "./shared";

const SWIFT_KEYWORDS = new Set([
  "import",
  "public",
  "private",
  "internal",
  "fileprivate",
  "open",
  "struct",
  "class",
  "enum",
  "protocol",
  "extension",
  "func",
  "var",
  "let",
  "init",
  "self",
  "Self",
  "return",
  "if",
  "else",
  "guard",
  "for",
  "in",
  "while",
  "do",
  "try",
  "throws",
  "throw",
  "catch",
  "switch",
  "case",
  "default",
  "break",
  "continue",
  "where",
  "as",
  "is",
  "nil",
  "true",
  "false",
  "static",
  "mutating",
  "inout",
  "associatedtype",
  "typealias",
  "indirect",
  "lazy",
  "weak",
  "unowned",
  "some",
  "any",
  "operator",
  "precedencegroup",
  "@escaping",
  "@discardableResult",
  "@MainActor",
  "@ViewBuilder",
  "@Environment",
  "@Binding",
  "@State",
  "@StateObject",
  "@ObservedObject",
  "@Published",
  "async",
  "await",
  "actor",
]);

const KNOWN_TYPES = new Set([
  "View",
  "Text",
  "Button",
  "Image",
  "VStack",
  "HStack",
  "ZStack",
  "ForEach",
  "List",
  "ScrollView",
  "NavigationStack",
  "NavigationLink",
  "URL",
  "String",
  "Int",
  "Double",
  "Float",
  "Bool",
  "Array",
  "Dictionary",
  "Set",
  "Optional",
  "Color",
  "Font",
  "EnvironmentValues",
  "EnvironmentKey",
  "Layout",
  "Subviews",
  "ProposedViewSize",
  "CGSize",
  "CGRect",
  "CGPoint",
  "CGFloat",
  "Identifiable",
  "Equatable",
  "Hashable",
  "Codable",
  "Decodable",
  "Encodable",
  "Void",
]);

export function highlightSwift(source: string): string {
  return highlightCurlyLanguage(source, {
    keywords: SWIFT_KEYWORDS,
    identifierStart: /[A-Za-z_@]/,
    identifierContinue: /[A-Za-z0-9_]/,
    numberContinue: /[0-9_.]/,
    isType: (word) =>
      KNOWN_TYPES.has(word) || /^[A-Z][A-Za-z0-9_]*$/.test(word),
  });
}
