//! #1939 — [`super::ACTION_CONTRACT`] data table.
//!
//! NIP-29 group action entries live in the sibling `nip29` submodule (size
//! management — 500-LOC hard cap) and are imported by name here. The `nip29`
//! module is declared in the parent `action_contract.rs`.

use super::{
    ActionContract, ActionDefaultTier, BuilderSupport, PublicReExportPolicy, TypedDispatchPolicy,
};
// NIP-29 entries (split out for 500-LOC cap): discover, publish_group_event, join, create_public_group.
use super::nip29::{
    NIP29_CREATE_PUBLIC_GROUP, NIP29_DISCOVER, NIP29_JOIN, NIP29_PUBLISH_GROUP_EVENT,
};

const PUBLIC_REEXPORT: PublicReExportPolicy = PublicReExportPolicy::DefaultsActionPayloads;
const TYPED_ONLY: TypedDispatchPolicy = TypedDispatchPolicy::TypedOnly;

/// Contract namespace for the core publish action. Kept here so emitters do not
/// own the publish routing key.
pub const PUBLISH_NAMESPACE: &str = "nmp.publish";

/// The neutral typed action contract manifest.
pub const ACTION_CONTRACT: &[ActionContract] = &[
    ActionContract {
        namespace: PUBLISH_NAMESPACE,
        producer: "nmp-core publish",
        module_type: "nmp_core::publish::PublishModule",
        payload_type: "nmp_core::publish::PublishAction",
        schema_id: "nmp.publish",
        schema_path: "crates/nmp-core/schema/publish.fbs",
        root_type: "PublishPayload",
        schema_version: 3,
        file_identifier: "NPUB",
        default_tier: ActionDefaultTier::CoreBuiltin,
        builder_support: BuilderSupport::GeneratedPublishUnion,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip65.publish_relay_list",
        producer: "nmp-router publish_relay_list",
        module_type: "nmp_router::PublishRelayListAction",
        payload_type: "nmp_router::PublishRelayListInput",
        schema_id: "nmp.nip65.publish_relay_list",
        schema_path: "crates/nmp-router/schema/publish_relay_list.fbs",
        root_type: "PublishRelayListPayload",
        schema_version: 1,
        file_identifier: "N65P",
        default_tier: ActionDefaultTier::Substrate,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip51.block_relay",
        producer: "nmp-router block_relay",
        module_type: "nmp_router::BlockRelayAction",
        payload_type: "nmp_router::BlockRelayInput",
        schema_id: "nmp.nip51.block_relay",
        schema_path: "crates/nmp-router/schema/block_relay.fbs",
        root_type: "BlockRelayPayload",
        schema_version: 1,
        file_identifier: "NBLK",
        default_tier: ActionDefaultTier::Substrate,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip51.unblock_relay",
        producer: "nmp-router block_relay",
        module_type: "nmp_router::UnblockRelayAction",
        payload_type: "nmp_router::UnblockRelayInput",
        schema_id: "nmp.nip51.unblock_relay",
        schema_path: "crates/nmp-router/schema/unblock_relay.fbs",
        root_type: "UnblockRelayPayload",
        schema_version: 1,
        file_identifier: "NUBL",
        default_tier: ActionDefaultTier::Substrate,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.follow",
        producer: "nmp-nip02 action_modules",
        module_type: "nmp_nip02::FollowModule",
        payload_type: "nmp_nip02::PubkeyAction",
        schema_id: "nmp.nip02.follow_action",
        schema_path: "crates/nmp-nip02/schema/follow_action.fbs",
        root_type: "FollowActionPayload",
        schema_version: 1,
        file_identifier: "NF2A",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.unfollow",
        producer: "nmp-nip02 action_modules",
        module_type: "nmp_nip02::UnfollowModule",
        payload_type: "nmp_nip02::PubkeyAction",
        schema_id: "nmp.nip02.follow_action",
        schema_path: "crates/nmp-nip02/schema/follow_action.fbs",
        root_type: "FollowActionPayload",
        schema_version: 1,
        file_identifier: "NF2A",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.follow_many",
        producer: "nmp-nip02 action_modules",
        module_type: "nmp_nip02::FollowManyModule",
        payload_type: "nmp_nip02::FollowManyAction",
        schema_id: "nmp.nip02.follow_many_action",
        schema_path: "crates/nmp-nip02/schema/follow_many_action.fbs",
        root_type: "FollowManyActionPayload",
        schema_version: 1,
        file_identifier: "NFMA",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip25.react",
        producer: "nmp-nip25 action",
        module_type: "nmp_nip25::ReactModule",
        payload_type: "nmp_nip25::ReactAction",
        schema_id: "nmp.nip25.react",
        schema_path: "crates/nmp-nip25/schema/react.fbs",
        root_type: "ReactPayload",
        schema_version: 1,
        file_identifier: "N25R",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip25.unreact",
        producer: "nmp-nip25 action",
        module_type: "nmp_nip25::UnreactModule",
        payload_type: "nmp_nip25::UnreactAction",
        schema_id: "nmp.nip25.unreact",
        schema_path: "crates/nmp-nip25/schema/unreact.fbs",
        root_type: "UnreactPayload",
        schema_version: 1,
        file_identifier: "N25U",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip18.repost",
        producer: "nmp-nip18 action",
        module_type: "nmp_nip18::RepostModule",
        payload_type: "nmp_nip18::RepostAction",
        schema_id: "nmp.nip18.repost",
        schema_path: "crates/nmp-nip18/schema/repost.fbs",
        root_type: "RepostPayload",
        schema_version: 1,
        file_identifier: "N18R",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip18.quote_repost",
        producer: "nmp-nip18 action",
        module_type: "nmp_nip18::QuoteRepostModule",
        payload_type: "nmp_nip18::QuoteRepostAction",
        schema_id: "nmp.nip18.quote_repost",
        schema_path: "crates/nmp-nip18/schema/quote_repost.fbs",
        root_type: "QuoteRepostPayload",
        schema_version: 1,
        file_identifier: "N18Q",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip84.publish_highlight",
        producer: "nmp-nip84 action",
        module_type: "nmp_nip84::PublishHighlightModule",
        payload_type: "nmp_nip84::PublishHighlightAction",
        schema_id: "nmp.nip84.publish_highlight",
        schema_path: "crates/nmp-nip84/schema/publish_highlight.fbs",
        root_type: "PublishHighlightPayload",
        schema_version: 2,
        file_identifier: "N84H",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip51.add_bookmark",
        producer: "nmp-nip51 bookmarks",
        module_type: "nmp_nip51::AddBookmarkAction",
        payload_type: "nmp_nip51::BookmarkUpdateInput",
        schema_id: "nmp.nip51.bookmark_update",
        schema_path: "crates/nmp-nip51/schema/bookmark_update.fbs",
        root_type: "BookmarkUpdatePayload",
        schema_version: 1,
        file_identifier: "N51B",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedBookmarkItemTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip51.remove_bookmark",
        producer: "nmp-nip51 bookmarks",
        module_type: "nmp_nip51::RemoveBookmarkAction",
        payload_type: "nmp_nip51::BookmarkUpdateInput",
        schema_id: "nmp.nip51.bookmark_update",
        schema_path: "crates/nmp-nip51/schema/bookmark_update.fbs",
        root_type: "BookmarkUpdatePayload",
        schema_version: 1,
        file_identifier: "N51B",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedBookmarkItemTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip22.post_comment",
        producer: "nmp-nip22 action",
        module_type: "nmp_nip22::PostCommentModule",
        payload_type: "nmp_nip22::PostCommentAction",
        schema_id: "nmp.nip22.post_comment",
        schema_path: "crates/nmp-nip22/schema/post_comment.fbs",
        root_type: "PostComment",
        schema_version: 1,
        file_identifier: "N22C",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    // nmp-nip51 — bookmark-set add/remove (kind:30003/30004), web bookmarks (kind:39701 NIP-B0).
    ActionContract {
        namespace: "nmp.nip51.add_bookmark_set_item",
        producer: "nmp-nip51 bookmark_sets",
        module_type: "nmp_nip51::AddBookmarkSetItemAction",
        payload_type: "nmp_nip51::BookmarkSetUpdateInput",
        schema_id: "nmp.nip51.bookmark_set_update",
        schema_path: "crates/nmp-nip51/schema/bookmark_set_update.fbs",
        root_type: "BookmarkSetUpdatePayload",
        schema_version: 1,
        file_identifier: "N51S",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedBookmarkSetItemTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip51.remove_bookmark_set_item",
        producer: "nmp-nip51 bookmark_sets",
        module_type: "nmp_nip51::RemoveBookmarkSetItemAction",
        payload_type: "nmp_nip51::BookmarkSetUpdateInput",
        schema_id: "nmp.nip51.bookmark_set_update",
        schema_path: "crates/nmp-nip51/schema/bookmark_set_update.fbs",
        root_type: "BookmarkSetUpdatePayload",
        schema_version: 1,
        file_identifier: "N51S",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedBookmarkSetItemTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip51.publish_web_bookmark",
        producer: "nmp-nip51 web_bookmarks",
        module_type: "nmp_nip51::PublishWebBookmarkAction",
        payload_type: "nmp_nip51::PublishWebBookmarkInput",
        schema_id: "nmp.nip51.web_bookmark_publish",
        schema_path: "crates/nmp-nip51/schema/web_bookmark_publish.fbs",
        root_type: "WebBookmarkPublishPayload",
        schema_version: 1,
        file_identifier: "N51W",
        default_tier: ActionDefaultTier::Social,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    // nmp-blossom — BUD-02 file upload (ComponentRegistered — not in nmp-defaults).
    ActionContract {
        namespace: "nmp.blossom.upload",
        producer: "nmp-blossom action",
        module_type: "nmp_blossom::UploadAction",
        payload_type: "nmp_blossom::UploadInput",
        schema_id: "nmp.blossom.upload",
        schema_path: "crates/nmp-blossom/schema/upload.fbs",
        root_type: "UploadPayload",
        schema_version: 1,
        file_identifier: "BUPL",
        default_tier: ActionDefaultTier::ComponentRegistered,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    // nmp-core — relay-pinned browse action (ComponentRegistered — opt-in action module).
    ActionContract {
        namespace: "nmp.browse_relay",
        producer: "nmp-core browse",
        module_type: "nmp_core::browse::BrowseRelayModule",
        payload_type: "nmp_core::browse::BrowseRelayAction",
        schema_id: "nmp.browse_relay",
        schema_path: "crates/nmp-core/schema/browse_relay.fbs",
        root_type: "BrowseRelayPayload",
        schema_version: 1,
        file_identifier: "NBRW",
        default_tier: ActionDefaultTier::ComponentRegistered,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    // nmp-defaults — topic articles example/action (ComponentRegistered — opt-in action module).
    ActionContract {
        namespace: "nmp.app.topic_articles",
        producer: "nmp-defaults topic_articles",
        module_type: "nmp_defaults::topic_articles::TopicArticlesModule",
        payload_type: "nmp_defaults::topic_articles::TopicArticlesAction",
        schema_id: "nmp.app.topic_articles",
        schema_path: "crates/nmp-defaults/schema/topic_articles.fbs",
        root_type: "TopicArticlesPayload",
        schema_version: 1,
        file_identifier: "NTPC",
        default_tier: ActionDefaultTier::ComponentRegistered,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip17.send",
        producer: "nmp-nip17 action",
        module_type: "nmp_nip17::SendDmAction",
        payload_type: "nmp_nip17::SendDmInput",
        schema_id: "nmp.nip17.send",
        schema_path: "crates/nmp-nip17/schema/send.fbs",
        root_type: "SendDmPayload",
        schema_version: 1,
        file_identifier: "N17S",
        default_tier: ActionDefaultTier::DirectMessages,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip17.publish_relay_list",
        producer: "nmp-nip17 dm_relay_list",
        module_type: "nmp_nip17::PublishDmRelayListAction",
        payload_type: "nmp_nip17::PublishDmRelayListInput",
        schema_id: "nmp.nip17.publish_relay_list",
        schema_path: "crates/nmp-nip17/schema/dm_relay_list_action.fbs",
        root_type: "PublishDmRelayListPayload",
        schema_version: 1,
        file_identifier: "N17R",
        default_tier: ActionDefaultTier::DirectMessages,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip17.hydrate_peer_relay_list",
        producer: "nmp-nip17 action",
        module_type: "nmp_nip17::HydratePeerRelayListAction",
        payload_type: "nmp_nip17::HydratePeerRelayListInput",
        schema_id: "nmp.nip17.hydrate_peer_relay_list",
        schema_path: "crates/nmp-nip17/schema/hydrate_peer_relay_list.fbs",
        root_type: "HydratePeerRelayListPayload",
        schema_version: 1,
        file_identifier: "N17H",
        default_tier: ActionDefaultTier::DirectMessages,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.nip57.zap",
        producer: "nmp-nip57 action",
        module_type: "nmp_nip57::ZapAction",
        payload_type: "nmp_nip57::ZapInput",
        schema_id: "nmp.nip57.zap",
        schema_path: "crates/nmp-nip57/schema/zap.fbs",
        root_type: "ZapPayload",
        schema_version: 1,
        file_identifier: "N57Z",
        default_tier: ActionDefaultTier::Zaps,
        builder_support: BuilderSupport::NotGenerated {
            reason: "post-v1 zap send surface removed from v1 generated host builders (#2318)",
        },
        public_re_export: PublicReExportPolicy::NotReExported {
            reason: "nmp-defaults does not register or re-export zap payloads in v1 (#2318)",
        },
        typed_dispatch: TYPED_ONLY,
    },
    // nmp-nip47 — NIP-47 Nostr Wallet Connect (opt-in via `with_wallet`).
    ActionContract {
        namespace: "nmp.wallet.connect",
        producer: "nmp-nip47 action connect",
        module_type: "nmp_nip47::WalletConnectModule",
        payload_type: "nmp_nip47::WalletConnectAction",
        schema_id: "nmp.wallet.connect",
        schema_path: "crates/nmp-nip47/schema/wallet_connect.fbs",
        root_type: "WalletConnectPayload",
        schema_version: 1,
        file_identifier: "N47C",
        default_tier: ActionDefaultTier::Wallet,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.wallet.disconnect",
        producer: "nmp-nip47 action connect",
        module_type: "nmp_nip47::WalletDisconnectModule",
        payload_type: "nmp_nip47::WalletDisconnectAction",
        schema_id: "nmp.wallet.disconnect",
        schema_path: "crates/nmp-nip47/schema/wallet_disconnect.fbs",
        root_type: "WalletDisconnectPayload",
        schema_version: 1,
        file_identifier: "N47D",
        default_tier: ActionDefaultTier::Wallet,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    ActionContract {
        namespace: "nmp.wallet.pay_invoice",
        producer: "nmp-nip47 action pay_invoice",
        module_type: "nmp_nip47::WalletPayInvoiceModule",
        payload_type: "nmp_nip47::WalletAction",
        schema_id: "nmp.wallet.pay_invoice",
        schema_path: "crates/nmp-nip47/schema/wallet_pay_invoice.fbs",
        root_type: "WalletPayInvoicePayload",
        schema_version: 1,
        file_identifier: "N47P",
        default_tier: ActionDefaultTier::Wallet,
        builder_support: BuilderSupport::GeneratedFlatTable,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    // nmp-marmot — MLS-over-Nostr write seam (opt-in via `--features marmot`).
    // One namespace, nine arms (union). M14-1c / #2169.
    ActionContract {
        namespace: "nmp.marmot",
        producer: "nmp-marmot action",
        module_type: "nmp_marmot::MarmotActionModule",
        payload_type: "nmp_marmot::MarmotAction",
        schema_id: "nmp.marmot",
        schema_path: "crates/nmp-marmot/schema/marmot_action.fbs",
        root_type: "MarmotActionPayload",
        schema_version: 1,
        file_identifier: "NMMA",
        default_tier: ActionDefaultTier::Marmot,
        builder_support: BuilderSupport::GeneratedMarmotUnion,
        public_re_export: PUBLIC_REEXPORT,
        typed_dispatch: TYPED_ONLY,
    },
    // nmp-nip29 — NIP-29 group actions (issue #2170). Full entries in `nip29.rs`.
    NIP29_DISCOVER,
    NIP29_PUBLISH_GROUP_EVENT,
    NIP29_JOIN,
    NIP29_CREATE_PUBLIC_GROUP,
];
