// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Metrics : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Metrics {
        __init(_i, _bb)
        return this
    }
    val generatedEvents : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val noteEvents : ULong
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val profileEvents : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val duplicateEvents : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val deleteEvents : ULong
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val storedEvents : ULong
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val tombstones : ULong
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val visibleItems : ULong
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val visibleProfiledItems : ULong
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val visiblePlaceholderAvatarItems : ULong
        get() {
            val o = __offset(22)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val openViews : UInt
        get() {
            val o = __offset(24)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val eventsSinceLastUpdate : ULong
        get() {
            val o = __offset(26)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val diagnosticFirehoseEvents : ULong
        get() {
            val o = __offset(28)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val insertedCount : ULong
        get() {
            val o = __offset(30)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val updatedCount : ULong
        get() {
            val o = __offset(32)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val removedCount : ULong
        get() {
            val o = __offset(34)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val emitHzConfigured : UInt
        get() {
            val o = __offset(36)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val updateSequence : ULong
        get() {
            val o = __offset(38)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val estimatedStoreBytes : ULong
        get() {
            val o = __offset(40)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val payloadBytes : ULong
        get() {
            val o = __offset(42)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val storeToPayloadRatio : Double
        get() {
            val o = __offset(44)
            return if(o != 0) bb.getDouble(o + bb_pos) else 0.0
        }
    val actorQueueDepth : UInt
        get() {
            val o = __offset(46)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val framesRx : ULong
        get() {
            val o = __offset(48)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val eventsRx : ULong
        get() {
            val o = __offset(50)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val eoseRx : ULong
        get() {
            val o = __offset(52)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val noticesRx : ULong
        get() {
            val o = __offset(54)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val closedRx : ULong
        get() {
            val o = __offset(56)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val bytesRx : ULong
        get() {
            val o = __offset(58)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val bytesTx : ULong
        get() {
            val o = __offset(60)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val contactsAuthors : ULong
        get() {
            val o = __offset(62)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val timelineAuthors : ULong
        get() {
            val o = __offset(64)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val firstEventMs : ULong?
        get() {
            val o = __offset(66)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val targetProfileLoadedMs : ULong?
        get() {
            val o = __offset(68)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val timelineOpenedMs : ULong?
        get() {
            val o = __offset(70)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val timelineFirstItemMs : ULong?
        get() {
            val o = __offset(72)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val updateEmittedMs : ULong?
        get() {
            val o = __offset(74)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val lastEventToEmitMs : ULong?
        get() {
            val o = __offset(76)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val maxEventToEmitMs : ULong
        get() {
            val o = __offset(78)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val maxEventsPerUpdate : ULong
        get() {
            val o = __offset(80)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val claimDropsTotal : ULong
        get() {
            val o = __offset(82)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val makeUpdateUs : ULong
        get() {
            val o = __offset(84)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val serializeUs : ULong
        get() {
            val o = __offset(86)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val updateFrameDegradationsTotal : ULong
        get() {
            val o = __offset(88)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMetrics(_bb: ByteBuffer): Metrics = getRootAsMetrics(_bb, Metrics())
        fun getRootAsMetrics(_bb: ByteBuffer, obj: Metrics): Metrics {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMetrics(builder: FlatBufferBuilder, generatedEvents: ULong, noteEvents: ULong, profileEvents: ULong, duplicateEvents: ULong, deleteEvents: ULong, storedEvents: ULong, tombstones: ULong, visibleItems: ULong, visibleProfiledItems: ULong, visiblePlaceholderAvatarItems: ULong, openViews: UInt, eventsSinceLastUpdate: ULong, diagnosticFirehoseEvents: ULong, insertedCount: ULong, updatedCount: ULong, removedCount: ULong, emitHzConfigured: UInt, updateSequence: ULong, estimatedStoreBytes: ULong, payloadBytes: ULong, storeToPayloadRatio: Double, actorQueueDepth: UInt, framesRx: ULong, eventsRx: ULong, eoseRx: ULong, noticesRx: ULong, closedRx: ULong, bytesRx: ULong, bytesTx: ULong, contactsAuthors: ULong, timelineAuthors: ULong, firstEventMs: ULong?, targetProfileLoadedMs: ULong?, timelineOpenedMs: ULong?, timelineFirstItemMs: ULong?, updateEmittedMs: ULong?, lastEventToEmitMs: ULong?, maxEventToEmitMs: ULong, maxEventsPerUpdate: ULong, claimDropsTotal: ULong, makeUpdateUs: ULong, serializeUs: ULong, updateFrameDegradationsTotal: ULong) : Int {
            builder.startTable(43)
            addUpdateFrameDegradationsTotal(builder, updateFrameDegradationsTotal)
            addSerializeUs(builder, serializeUs)
            addMakeUpdateUs(builder, makeUpdateUs)
            addClaimDropsTotal(builder, claimDropsTotal)
            addMaxEventsPerUpdate(builder, maxEventsPerUpdate)
            addMaxEventToEmitMs(builder, maxEventToEmitMs)
            lastEventToEmitMs?.run { addLastEventToEmitMs(builder, lastEventToEmitMs) }
            updateEmittedMs?.run { addUpdateEmittedMs(builder, updateEmittedMs) }
            timelineFirstItemMs?.run { addTimelineFirstItemMs(builder, timelineFirstItemMs) }
            timelineOpenedMs?.run { addTimelineOpenedMs(builder, timelineOpenedMs) }
            targetProfileLoadedMs?.run { addTargetProfileLoadedMs(builder, targetProfileLoadedMs) }
            firstEventMs?.run { addFirstEventMs(builder, firstEventMs) }
            addTimelineAuthors(builder, timelineAuthors)
            addContactsAuthors(builder, contactsAuthors)
            addBytesTx(builder, bytesTx)
            addBytesRx(builder, bytesRx)
            addClosedRx(builder, closedRx)
            addNoticesRx(builder, noticesRx)
            addEoseRx(builder, eoseRx)
            addEventsRx(builder, eventsRx)
            addFramesRx(builder, framesRx)
            addStoreToPayloadRatio(builder, storeToPayloadRatio)
            addPayloadBytes(builder, payloadBytes)
            addEstimatedStoreBytes(builder, estimatedStoreBytes)
            addUpdateSequence(builder, updateSequence)
            addRemovedCount(builder, removedCount)
            addUpdatedCount(builder, updatedCount)
            addInsertedCount(builder, insertedCount)
            addDiagnosticFirehoseEvents(builder, diagnosticFirehoseEvents)
            addEventsSinceLastUpdate(builder, eventsSinceLastUpdate)
            addVisiblePlaceholderAvatarItems(builder, visiblePlaceholderAvatarItems)
            addVisibleProfiledItems(builder, visibleProfiledItems)
            addVisibleItems(builder, visibleItems)
            addTombstones(builder, tombstones)
            addStoredEvents(builder, storedEvents)
            addDeleteEvents(builder, deleteEvents)
            addDuplicateEvents(builder, duplicateEvents)
            addProfileEvents(builder, profileEvents)
            addNoteEvents(builder, noteEvents)
            addGeneratedEvents(builder, generatedEvents)
            addActorQueueDepth(builder, actorQueueDepth)
            addEmitHzConfigured(builder, emitHzConfigured)
            addOpenViews(builder, openViews)
            return endMetrics(builder)
        }
        fun startMetrics(builder: FlatBufferBuilder) = builder.startTable(43)
        fun addGeneratedEvents(builder: FlatBufferBuilder, generatedEvents: ULong) = builder.addLong(0, generatedEvents.toLong(), 0)
        fun addNoteEvents(builder: FlatBufferBuilder, noteEvents: ULong) = builder.addLong(1, noteEvents.toLong(), 0)
        fun addProfileEvents(builder: FlatBufferBuilder, profileEvents: ULong) = builder.addLong(2, profileEvents.toLong(), 0)
        fun addDuplicateEvents(builder: FlatBufferBuilder, duplicateEvents: ULong) = builder.addLong(3, duplicateEvents.toLong(), 0)
        fun addDeleteEvents(builder: FlatBufferBuilder, deleteEvents: ULong) = builder.addLong(4, deleteEvents.toLong(), 0)
        fun addStoredEvents(builder: FlatBufferBuilder, storedEvents: ULong) = builder.addLong(5, storedEvents.toLong(), 0)
        fun addTombstones(builder: FlatBufferBuilder, tombstones: ULong) = builder.addLong(6, tombstones.toLong(), 0)
        fun addVisibleItems(builder: FlatBufferBuilder, visibleItems: ULong) = builder.addLong(7, visibleItems.toLong(), 0)
        fun addVisibleProfiledItems(builder: FlatBufferBuilder, visibleProfiledItems: ULong) = builder.addLong(8, visibleProfiledItems.toLong(), 0)
        fun addVisiblePlaceholderAvatarItems(builder: FlatBufferBuilder, visiblePlaceholderAvatarItems: ULong) = builder.addLong(9, visiblePlaceholderAvatarItems.toLong(), 0)
        fun addOpenViews(builder: FlatBufferBuilder, openViews: UInt) = builder.addInt(10, openViews.toInt(), 0)
        fun addEventsSinceLastUpdate(builder: FlatBufferBuilder, eventsSinceLastUpdate: ULong) = builder.addLong(11, eventsSinceLastUpdate.toLong(), 0)
        fun addDiagnosticFirehoseEvents(builder: FlatBufferBuilder, diagnosticFirehoseEvents: ULong) = builder.addLong(12, diagnosticFirehoseEvents.toLong(), 0)
        fun addInsertedCount(builder: FlatBufferBuilder, insertedCount: ULong) = builder.addLong(13, insertedCount.toLong(), 0)
        fun addUpdatedCount(builder: FlatBufferBuilder, updatedCount: ULong) = builder.addLong(14, updatedCount.toLong(), 0)
        fun addRemovedCount(builder: FlatBufferBuilder, removedCount: ULong) = builder.addLong(15, removedCount.toLong(), 0)
        fun addEmitHzConfigured(builder: FlatBufferBuilder, emitHzConfigured: UInt) = builder.addInt(16, emitHzConfigured.toInt(), 0)
        fun addUpdateSequence(builder: FlatBufferBuilder, updateSequence: ULong) = builder.addLong(17, updateSequence.toLong(), 0)
        fun addEstimatedStoreBytes(builder: FlatBufferBuilder, estimatedStoreBytes: ULong) = builder.addLong(18, estimatedStoreBytes.toLong(), 0)
        fun addPayloadBytes(builder: FlatBufferBuilder, payloadBytes: ULong) = builder.addLong(19, payloadBytes.toLong(), 0)
        fun addStoreToPayloadRatio(builder: FlatBufferBuilder, storeToPayloadRatio: Double) = builder.addDouble(20, storeToPayloadRatio, 0.0)
        fun addActorQueueDepth(builder: FlatBufferBuilder, actorQueueDepth: UInt) = builder.addInt(21, actorQueueDepth.toInt(), 0)
        fun addFramesRx(builder: FlatBufferBuilder, framesRx: ULong) = builder.addLong(22, framesRx.toLong(), 0)
        fun addEventsRx(builder: FlatBufferBuilder, eventsRx: ULong) = builder.addLong(23, eventsRx.toLong(), 0)
        fun addEoseRx(builder: FlatBufferBuilder, eoseRx: ULong) = builder.addLong(24, eoseRx.toLong(), 0)
        fun addNoticesRx(builder: FlatBufferBuilder, noticesRx: ULong) = builder.addLong(25, noticesRx.toLong(), 0)
        fun addClosedRx(builder: FlatBufferBuilder, closedRx: ULong) = builder.addLong(26, closedRx.toLong(), 0)
        fun addBytesRx(builder: FlatBufferBuilder, bytesRx: ULong) = builder.addLong(27, bytesRx.toLong(), 0)
        fun addBytesTx(builder: FlatBufferBuilder, bytesTx: ULong) = builder.addLong(28, bytesTx.toLong(), 0)
        fun addContactsAuthors(builder: FlatBufferBuilder, contactsAuthors: ULong) = builder.addLong(29, contactsAuthors.toLong(), 0)
        fun addTimelineAuthors(builder: FlatBufferBuilder, timelineAuthors: ULong) = builder.addLong(30, timelineAuthors.toLong(), 0)
        fun addFirstEventMs(builder: FlatBufferBuilder, firstEventMs: ULong) = builder.addLong(31, firstEventMs.toLong(), 0)
        fun addTargetProfileLoadedMs(builder: FlatBufferBuilder, targetProfileLoadedMs: ULong) = builder.addLong(32, targetProfileLoadedMs.toLong(), 0)
        fun addTimelineOpenedMs(builder: FlatBufferBuilder, timelineOpenedMs: ULong) = builder.addLong(33, timelineOpenedMs.toLong(), 0)
        fun addTimelineFirstItemMs(builder: FlatBufferBuilder, timelineFirstItemMs: ULong) = builder.addLong(34, timelineFirstItemMs.toLong(), 0)
        fun addUpdateEmittedMs(builder: FlatBufferBuilder, updateEmittedMs: ULong) = builder.addLong(35, updateEmittedMs.toLong(), 0)
        fun addLastEventToEmitMs(builder: FlatBufferBuilder, lastEventToEmitMs: ULong) = builder.addLong(36, lastEventToEmitMs.toLong(), 0)
        fun addMaxEventToEmitMs(builder: FlatBufferBuilder, maxEventToEmitMs: ULong) = builder.addLong(37, maxEventToEmitMs.toLong(), 0)
        fun addMaxEventsPerUpdate(builder: FlatBufferBuilder, maxEventsPerUpdate: ULong) = builder.addLong(38, maxEventsPerUpdate.toLong(), 0)
        fun addClaimDropsTotal(builder: FlatBufferBuilder, claimDropsTotal: ULong) = builder.addLong(39, claimDropsTotal.toLong(), 0)
        fun addMakeUpdateUs(builder: FlatBufferBuilder, makeUpdateUs: ULong) = builder.addLong(40, makeUpdateUs.toLong(), 0)
        fun addSerializeUs(builder: FlatBufferBuilder, serializeUs: ULong) = builder.addLong(41, serializeUs.toLong(), 0)
        fun addUpdateFrameDegradationsTotal(builder: FlatBufferBuilder, updateFrameDegradationsTotal: ULong) = builder.addLong(42, updateFrameDegradationsTotal.toLong(), 0)
        fun endMetrics(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
