// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class NegentropySyncStats : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : NegentropySyncStats {
        __init(_i, _bb)
        return this
    }
    val rounds : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val haveIds : ULong
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val needIds : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val localItemCount : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val transferAvoidedBytes : ULong
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val lastReconcileAtMs : ULong?
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsNegentropySyncStats(_bb: ByteBuffer): NegentropySyncStats = getRootAsNegentropySyncStats(_bb, NegentropySyncStats())
        fun getRootAsNegentropySyncStats(_bb: ByteBuffer, obj: NegentropySyncStats): NegentropySyncStats {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createNegentropySyncStats(builder: FlatBufferBuilder, rounds: ULong, haveIds: ULong, needIds: ULong, localItemCount: ULong, transferAvoidedBytes: ULong, lastReconcileAtMs: ULong?) : Int {
            builder.startTable(6)
            lastReconcileAtMs?.run { addLastReconcileAtMs(builder, lastReconcileAtMs) }
            addTransferAvoidedBytes(builder, transferAvoidedBytes)
            addLocalItemCount(builder, localItemCount)
            addNeedIds(builder, needIds)
            addHaveIds(builder, haveIds)
            addRounds(builder, rounds)
            return endNegentropySyncStats(builder)
        }
        fun startNegentropySyncStats(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addRounds(builder: FlatBufferBuilder, rounds: ULong) = builder.addLong(0, rounds.toLong(), 0)
        fun addHaveIds(builder: FlatBufferBuilder, haveIds: ULong) = builder.addLong(1, haveIds.toLong(), 0)
        fun addNeedIds(builder: FlatBufferBuilder, needIds: ULong) = builder.addLong(2, needIds.toLong(), 0)
        fun addLocalItemCount(builder: FlatBufferBuilder, localItemCount: ULong) = builder.addLong(3, localItemCount.toLong(), 0)
        fun addTransferAvoidedBytes(builder: FlatBufferBuilder, transferAvoidedBytes: ULong) = builder.addLong(4, transferAvoidedBytes.toLong(), 0)
        fun addLastReconcileAtMs(builder: FlatBufferBuilder, lastReconcileAtMs: ULong) = builder.addLong(5, lastReconcileAtMs.toLong(), 0)
        fun endNegentropySyncStats(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
