// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PullWakeBatch : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PullWakeBatch {
        __init(_i, _bb)
        return this
    }
    fun wakes(j: Int) : nmp.transport.PullWake? = wakes(nmp.transport.PullWake(), j)
    fun wakes(obj: nmp.transport.PullWake, j: Int) : nmp.transport.PullWake? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val wakesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPullWakeBatch(_bb: ByteBuffer): PullWakeBatch = getRootAsPullWakeBatch(_bb, PullWakeBatch())
        fun getRootAsPullWakeBatch(_bb: ByteBuffer, obj: PullWakeBatch): PullWakeBatch {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPullWakeBatch(builder: FlatBufferBuilder, wakesOffset: Int) : Int {
            builder.startTable(1)
            addWakes(builder, wakesOffset)
            return endPullWakeBatch(builder)
        }
        fun startPullWakeBatch(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addWakes(builder: FlatBufferBuilder, wakes: Int) = builder.addOffset(0, wakes, 0)
        fun createWakesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startWakesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endPullWakeBatch(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
