// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SnapshotFrame : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SnapshotFrame {
        __init(_i, _bb)
        return this
    }
    val schemaVersion : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 1u
        }
    val payload : nmp.transport.Value? get() = payload(nmp.transport.Value())
    fun payload(obj: nmp.transport.Value) : nmp.transport.Value? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun typedProjections(j: Int) : nmp.transport.TypedProjection? = typedProjections(nmp.transport.TypedProjection(), j)
    fun typedProjections(obj: nmp.transport.TypedProjection, j: Int) : nmp.transport.TypedProjection? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val typedProjectionsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSnapshotFrame(_bb: ByteBuffer): SnapshotFrame = getRootAsSnapshotFrame(_bb, SnapshotFrame())
        fun getRootAsSnapshotFrame(_bb: ByteBuffer, obj: SnapshotFrame): SnapshotFrame {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSnapshotFrame(builder: FlatBufferBuilder, schemaVersion: UInt, payloadOffset: Int, typedProjectionsOffset: Int) : Int {
            builder.startTable(3)
            addTypedProjections(builder, typedProjectionsOffset)
            addPayload(builder, payloadOffset)
            addSchemaVersion(builder, schemaVersion)
            return endSnapshotFrame(builder)
        }
        fun startSnapshotFrame(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addSchemaVersion(builder: FlatBufferBuilder, schemaVersion: UInt) = builder.addInt(0, schemaVersion.toInt(), 1)
        fun addPayload(builder: FlatBufferBuilder, payload: Int) = builder.addOffset(1, payload, 0)
        fun addTypedProjections(builder: FlatBufferBuilder, typedProjections: Int) = builder.addOffset(2, typedProjections, 0)
        fun createTypedProjectionsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startTypedProjectionsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endSnapshotFrame(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
