// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TypedProjection : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TypedProjection {
        __init(_i, _bb)
        return this
    }
    val key : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val keyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun keyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val payload : nmp.transport.TypedPayload? get() = payload(nmp.transport.TypedPayload())
    fun payload(obj: nmp.transport.TypedPayload) : nmp.transport.TypedPayload? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val projectionRev : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val state : UByte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTypedProjection(_bb: ByteBuffer): TypedProjection = getRootAsTypedProjection(_bb, TypedProjection())
        fun getRootAsTypedProjection(_bb: ByteBuffer, obj: TypedProjection): TypedProjection {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTypedProjection(builder: FlatBufferBuilder, keyOffset: Int, payloadOffset: Int, projectionRev: ULong, state: UByte) : Int {
            builder.startTable(4)
            addProjectionRev(builder, projectionRev)
            addPayload(builder, payloadOffset)
            addKey(builder, keyOffset)
            addState(builder, state)
            return endTypedProjection(builder)
        }
        fun startTypedProjection(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addKey(builder: FlatBufferBuilder, key: Int) = builder.addOffset(0, key, 0)
        fun addPayload(builder: FlatBufferBuilder, payload: Int) = builder.addOffset(1, payload, 0)
        fun addProjectionRev(builder: FlatBufferBuilder, projectionRev: ULong) = builder.addLong(2, projectionRev.toLong(), 0)
        fun addState(builder: FlatBufferBuilder, state: UByte) = builder.addByte(3, state.toByte(), 0)
        fun endTypedProjection(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
