// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class WireSubscriptionStatus : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : WireSubscriptionStatus {
        __init(_i, _bb)
        return this
    }
    val wireId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val wireIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun wireIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val relayUrl : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val relayUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun relayUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val filterSummary : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val filterSummaryAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun filterSummaryInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val state : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stateAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun stateInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val logicalConsumerCount : UInt
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val eventsRx : ULong
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val openedAtMs : ULong
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val lastEventAtMs : ULong?
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val eoseAtMs : ULong?
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val closeReason : String?
        get() {
            val o = __offset(22)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val closeReasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(22, 1)
    fun closeReasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 22, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsWireSubscriptionStatus(_bb: ByteBuffer): WireSubscriptionStatus = getRootAsWireSubscriptionStatus(_bb, WireSubscriptionStatus())
        fun getRootAsWireSubscriptionStatus(_bb: ByteBuffer, obj: WireSubscriptionStatus): WireSubscriptionStatus {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createWireSubscriptionStatus(builder: FlatBufferBuilder, wireIdOffset: Int, relayUrlOffset: Int, filterSummaryOffset: Int, stateOffset: Int, logicalConsumerCount: UInt, eventsRx: ULong, openedAtMs: ULong, lastEventAtMs: ULong?, eoseAtMs: ULong?, closeReasonOffset: Int) : Int {
            builder.startTable(10)
            eoseAtMs?.run { addEoseAtMs(builder, eoseAtMs) }
            lastEventAtMs?.run { addLastEventAtMs(builder, lastEventAtMs) }
            addOpenedAtMs(builder, openedAtMs)
            addEventsRx(builder, eventsRx)
            addCloseReason(builder, closeReasonOffset)
            addLogicalConsumerCount(builder, logicalConsumerCount)
            addState(builder, stateOffset)
            addFilterSummary(builder, filterSummaryOffset)
            addRelayUrl(builder, relayUrlOffset)
            addWireId(builder, wireIdOffset)
            return endWireSubscriptionStatus(builder)
        }
        fun startWireSubscriptionStatus(builder: FlatBufferBuilder) = builder.startTable(10)
        fun addWireId(builder: FlatBufferBuilder, wireId: Int) = builder.addOffset(0, wireId, 0)
        fun addRelayUrl(builder: FlatBufferBuilder, relayUrl: Int) = builder.addOffset(1, relayUrl, 0)
        fun addFilterSummary(builder: FlatBufferBuilder, filterSummary: Int) = builder.addOffset(2, filterSummary, 0)
        fun addState(builder: FlatBufferBuilder, state: Int) = builder.addOffset(3, state, 0)
        fun addLogicalConsumerCount(builder: FlatBufferBuilder, logicalConsumerCount: UInt) = builder.addInt(4, logicalConsumerCount.toInt(), 0)
        fun addEventsRx(builder: FlatBufferBuilder, eventsRx: ULong) = builder.addLong(5, eventsRx.toLong(), 0)
        fun addOpenedAtMs(builder: FlatBufferBuilder, openedAtMs: ULong) = builder.addLong(6, openedAtMs.toLong(), 0)
        fun addLastEventAtMs(builder: FlatBufferBuilder, lastEventAtMs: ULong) = builder.addLong(7, lastEventAtMs.toLong(), 0)
        fun addEoseAtMs(builder: FlatBufferBuilder, eoseAtMs: ULong) = builder.addLong(8, eoseAtMs.toLong(), 0)
        fun addCloseReason(builder: FlatBufferBuilder, closeReason: Int) = builder.addOffset(9, closeReason, 0)
        fun endWireSubscriptionStatus(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
