//! Typed FlatBuffers wire codec for
//! [`crate::aggregate::ReactionAggregateSnapshot`].
//!
//! The canonical FFI shape is the serde JSON of `ReactionAggregateSnapshot`
//! (`ReactionAggregateProjection::snapshot_json`). This module adds a **typed
//! FlatBuffers** encoding of the same read model — the typed sidecar (ADR-0037)
//! carried alongside the generic `Value` projection under the same
//! `"nmp.nip25.reactions"` key. The serde shape stays authoritative; this is the
//! typed payload an `N25A`-aware host decodes with generated accessors instead
//! of JSON reflection.
//!
//! Raw data only (ADR-0032): the emoji `token` is the verbatim reaction content
//! and `reactors` are raw hex pubkeys. No `display::` forwarder runs on the
//! encode path.
//!
//! Honours D6 (no panics): [`decode_reaction_aggregate_snapshot`] returns
//! `Err(String)` on any malformed input; there are no
//! `unwrap`/`expect`/panicking-index operations on the decode path.
//!
//! ## Regenerating the bindings
//!
//! The checked-in bindings in `wire/generated/reaction_aggregate_generated.rs`
//! are produced by `flatc` from `schema/reaction_aggregate.fbs`. Regenerate only
//! with the workspace FlatBuffers pin (`25.12.19`), enforced by
//! `ci/check-flatbuffers-version-pins.sh`. The schema is self-contained, so
//! generate with plain `flatc --rust`:
//!
//! ```sh
//! flatc --rust -o crates/nmp-nip25/src/wire/generated \
//!       crates/nmp-nip25/schema/reaction_aggregate.fbs
//! ```

// The generated FlatBuffers bindings are intrinsically `unsafe` (every accessor
// reads from a raw `Table`). This single generated module — and only it — opts
// back into `unsafe`. No hand-written code in this file uses `unsafe`.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/reaction_aggregate_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};
use generated::nmp::nip_25 as fb;

use crate::aggregate::{
    ReactionAggregateSnapshot, ReactionEmojiCount, ReactionTargetAggregate, ViewerReaction,
};

// #1723 — `REACTION_AGGREGATE_SCHEMA_ID` / `_FILE_IDENTIFIER` / `_SCHEMA_VERSION`
// are derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("reaction_aggregate_producer_consts.generated.rs");

// --- encode ---------------------------------------------------------------

/// Encode a [`ReactionAggregateSnapshot`] to typed FlatBuffers bytes (with the
/// `N25A` file identifier). `targets` order is preserved verbatim (target id
/// ascending as the projection emits it).
#[must_use]
pub fn encode_reaction_aggregate_snapshot(snapshot: &ReactionAggregateSnapshot) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let target_offsets: Vec<WIPOffset<fb::ReactionTargetAggregate<'_>>> = snapshot
        .targets
        .iter()
        .map(|target| encode_target(&mut fbb, target))
        .collect();
    let targets = fbb.create_vector(&target_offsets);

    let root = fb::ReactionAggregateSnapshot::create(
        &mut fbb,
        &fb::ReactionAggregateSnapshotArgs {
            schema_version: REACTION_AGGREGATE_SCHEMA_VERSION,
            targets: Some(targets),
        },
    );
    fb::finish_reaction_aggregate_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

fn encode_target<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    target: &ReactionTargetAggregate,
) -> WIPOffset<fb::ReactionTargetAggregate<'a>> {
    let target_event_id = fbb.create_string(&target.target_event_id);

    let emoji_offsets: Vec<WIPOffset<fb::ReactionEmojiCount<'a>>> = target
        .by_emoji
        .iter()
        .map(|emoji| {
            let token = fbb.create_string(&emoji.token);
            fb::ReactionEmojiCount::create(
                fbb,
                &fb::ReactionEmojiCountArgs {
                    token: Some(token),
                    count: emoji.count,
                },
            )
        })
        .collect();
    let by_emoji = fbb.create_vector(&emoji_offsets);

    let reactor_offsets: Vec<WIPOffset<&str>> = target
        .reactors
        .iter()
        .map(|pubkey| fbb.create_string(pubkey))
        .collect();
    let reactors = fbb.create_vector(&reactor_offsets);

    let mine_offsets: Vec<WIPOffset<fb::ViewerReaction<'a>>> = target
        .mine
        .iter()
        .map(|viewer| {
            let token = fbb.create_string(&viewer.token);
            let reaction_event_id = fbb.create_string(&viewer.reaction_event_id);
            fb::ViewerReaction::create(
                fbb,
                &fb::ViewerReactionArgs {
                    token: Some(token),
                    reaction_event_id: Some(reaction_event_id),
                },
            )
        })
        .collect();
    let mine = fbb.create_vector(&mine_offsets);

    fb::ReactionTargetAggregate::create(
        fbb,
        &fb::ReactionTargetAggregateArgs {
            target_event_id: Some(target_event_id),
            total: target.total,
            by_emoji: Some(by_emoji),
            reactors: Some(reactors),
            mine: Some(mine),
        },
    )
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by
/// [`encode_reaction_aggregate_snapshot`]) back into a
/// [`ReactionAggregateSnapshot`]. Returns an error string on any malformed
/// input or missing required field.
pub fn decode_reaction_aggregate_snapshot(
    bytes: &[u8],
) -> Result<ReactionAggregateSnapshot, String> {
    if bytes.len() < 8 || !fb::reaction_aggregate_snapshot_buffer_has_identifier(bytes) {
        return Err("missing N25A file identifier".to_string());
    }
    let root = fb::root_as_reaction_aggregate_snapshot(bytes)
        .map_err(|e| format!("not a valid ReactionAggregateSnapshot buffer: {e}"))?;

    let mut targets = Vec::new();
    if let Some(fb_targets) = root.targets() {
        targets.reserve(fb_targets.len());
        for fb_target in fb_targets.iter() {
            targets.push(decode_target(fb_target)?);
        }
    }

    Ok(ReactionAggregateSnapshot { targets })
}

fn decode_target(target: fb::ReactionTargetAggregate<'_>) -> Result<ReactionTargetAggregate, String> {
    let mut by_emoji = Vec::new();
    if let Some(fb_emoji) = target.by_emoji() {
        by_emoji.reserve(fb_emoji.len());
        for emoji in fb_emoji.iter() {
            by_emoji.push(ReactionEmojiCount {
                token: str_field(emoji.token(), "ReactionEmojiCount.token")?,
                count: emoji.count(),
            });
        }
    }

    let mut reactors = Vec::new();
    if let Some(fb_reactors) = target.reactors() {
        reactors.reserve(fb_reactors.len());
        for reactor in fb_reactors.iter() {
            reactors.push(reactor.to_string());
        }
    }

    let mut mine = Vec::new();
    if let Some(fb_mine) = target.mine() {
        mine.reserve(fb_mine.len());
        for viewer in fb_mine.iter() {
            mine.push(ViewerReaction {
                token: str_field(viewer.token(), "ViewerReaction.token")?,
                reaction_event_id: str_field(
                    viewer.reaction_event_id(),
                    "ViewerReaction.reaction_event_id",
                )?,
            });
        }
    }

    Ok(ReactionTargetAggregate {
        target_event_id: str_field(target.target_event_id(), "ReactionTargetAggregate.target_event_id")?,
        total: target.total(),
        by_emoji,
        reactors,
        mine,
    })
}

/// Require a present string field; an absent FlatBuffers string on a mandatory
/// slot is a decode error.
fn str_field(value: Option<&str>, ctx: &str) -> Result<String, String> {
    value
        .map(str::to_string)
        .ok_or_else(|| format!("{ctx}: missing required string field"))
}

#[cfg(test)]
#[path = "reaction_aggregate_fb_tests.rs"]
mod tests;
