// @generated by `cargo run -p nmp-codegen -- gen producer-consts`. DO NOT EDIT.
//
// Source of truth: crates/nmp-codegen/src/projection_contract.rs
//   (PROJECTION_CONTRACT entry for key "publish_queue": schema_id / file_identifier /
//   version). Regenerate + verify drift via
//   `.github/workflows/codegen-drift.yml` (gen producer-consts --check).
/// Stable schema identifier carried in the typed-projection envelope. Equals the
/// snapshot key (ADR-0072 shared-keyspace contract).
pub const PUBLISH_QUEUE_SCHEMA_ID: &str = "publish_queue";
/// FlatBuffers file identifier embedded in every buffer this module emits.
pub const PUBLISH_QUEUE_FILE_IDENTIFIER: &[u8; 4] = b"KPBQ";
/// Wire schema version. Bump on any breaking change to this projection's `.fbs`.
pub const PUBLISH_QUEUE_SCHEMA_VERSION: u32 = 1;
