//! Typed FlatBuffers wire codec for the kernel-owned `"relay_role_options"`
//! projection (Tier-2 built-in).
//!
//! The authoritative FFI shape is the serde JSON the
//! `snapshot_projections_with_publish_cluster` helper inserts under
//! `"relay_role_options"`: the serialisation of
//! `crate::actor::relay_role_options()`, a `Vec<RelayRoleOption>`
//! (`{ value, label, tint, is_default }`). This module adds a **typed
//! FlatBuffers** encoding of the same shape, carried in the `typed_projections`
//! sidecar (ADR-0037) ALONGSIDE — never replacing — the generic `Value`
//! projection.
//!
//! [`RelayRoleOptionsModel`] is built directly from the same option vector the
//! JSON path serialises, in the same tick, so the two wire forms cannot
//! structurally diverge.
//!
//! Honours D6 (no panics): decode returns `Err(String)` on any malformed input.

// The generated FlatBuffers bindings are intrinsically `unsafe`. This `allow`
// block scopes the relaxation to the single generated module.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/relay_role_options_generated.rs"]
pub mod generated;

use flatbuffers::{FlatBufferBuilder, WIPOffset};

use generated::nmp::kernel as fb;

// #1723 — `*_SCHEMA_ID` / `*_FILE_IDENTIFIER` / `*_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("relay_role_options_producer_consts.generated.rs");

/// One relay-role picker option — a field-for-field mirror of one
/// `RelayRoleOption`.
///
/// `label` removed (#1678, D7): presentation artifact; shells map
/// `value` → label themselves (value→label mapping is static and
/// shell-language-specific).
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RelayRoleOptionRow {
    pub value: String,
    pub tint: String,
    pub is_default: bool,
}

/// The `"relay_role_options"` read model — the ordered picker options. Built
/// from the same option vector the JSON projection serialises; see
/// [`Kernel::builtin_typed_projections`](crate::kernel::Kernel), which maps the
/// `crate::actor::relay_role_options()` output (whose element type is
/// `pub(crate)`-but-unnameable outside the codegen feature) into these rows.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RelayRoleOptionsModel {
    pub options: Vec<RelayRoleOptionRow>,
}

// --- encode ---------------------------------------------------------------

/// Encode a [`RelayRoleOptionsModel`] to typed FlatBuffers bytes (with the
/// `KRRO` file identifier). Option order is preserved verbatim.
#[must_use]
pub(crate) fn encode_relay_role_options(model: &RelayRoleOptionsModel) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();

    let option_offsets: Vec<WIPOffset<fb::RelayRoleOption>> = model
        .options
        .iter()
        .map(|option| {
            let value = fbb.create_string(&option.value);
            let tint = fbb.create_string(&option.tint);
            fb::RelayRoleOption::create(
                &mut fbb,
                &fb::RelayRoleOptionArgs {
                    value: Some(value),
                    tint: Some(tint),
                    is_default: option.is_default,
                },
            )
        })
        .collect();
    let options = fbb.create_vector(&option_offsets);

    let root = fb::RelayRoleOptionsSnapshot::create(
        &mut fbb,
        &fb::RelayRoleOptionsSnapshotArgs {
            options: Some(options),
        },
    );
    fb::finish_relay_role_options_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by [`encode_relay_role_options`])
/// back into a [`RelayRoleOptionsModel`]. Returns an error string on any
/// malformed input.
pub fn decode_relay_role_options(bytes: &[u8]) -> Result<RelayRoleOptionsModel, String> {
    if bytes.len() < 8 || !fb::relay_role_options_snapshot_buffer_has_identifier(bytes) {
        return Err("missing KRRO file identifier".to_string());
    }
    let root = fb::root_as_relay_role_options_snapshot(bytes)
        .map_err(|e| format!("not a valid RelayRoleOptionsSnapshot buffer: {e}"))?;

    let mut options = Vec::new();
    if let Some(fb_options) = root.options() {
        options.reserve(fb_options.len());
        for option in fb_options.iter() {
            options.push(RelayRoleOptionRow {
                value: option.value().unwrap_or_default().to_string(),
                tint: option.tint().unwrap_or_default().to_string(),
                is_default: option.is_default(),
            });
        }
    }

    Ok(RelayRoleOptionsModel { options })
}

#[cfg(test)]
#[path = "relay_role_options_fb_tests.rs"]
mod tests;
