//! Typed FlatBuffers wire codec for the kernel-owned `"relay_diagnostics"`
//! projection (Tier-2 built-in).
//!
//! The authoritative FFI shape is the serde JSON the
//! `snapshot_projections_with_publish_cluster` helper inserts under
//! `"relay_diagnostics"`: the serialisation of `relay_diagnostics_snapshot()` (a
//! `RelayDiagnosticsSnapshot` — the pre-rolled diagnostics-screen view). This
//! module adds a **typed FlatBuffers** encoding of the same shape, carried in the
//! `typed_projections` sidecar (ADR-0037) ALONGSIDE — never replacing — the
//! generic `Value` projection.
//!
//! ## Capture-once ownership (the #1031 struct->Model path)
//!
//! `relay_diagnostics_snapshot()` is `&self` but pre-formats wall-clock-relative
//! labels against a `now` it reads internally each call, so calling it twice in a
//! tick risks a one-second-bucket divergence between the JSON and typed forms.
//! The JSON path captures the produced `RelayDiagnosticsSnapshot` STRUCT once into
//! a per-tick `Kernel` field; the struct->Model mapping lives in
//! `builtins_diagnostics.rs` (where the `pub(super)` struct fields are reachable),
//! and this codec encodes that single captured instance — so every formatted
//! label is identical to the JSON by construction. Unlike the four drained
//! built-ins this is the #1031 struct->Model convention (a real struct survives;
//! no Value-parse needed).
//!
//! Honours D6 (no panics): decode returns `Err(String)` on any malformed input.

// The generated FlatBuffers bindings are intrinsically `unsafe`. This `allow`
// block scopes the relaxation to the single generated module.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/relay_diagnostics_generated.rs"]
pub mod generated;

// ConnectionReasonRow model + encode/decode helpers extracted to satisfy the
// 500-LOC file-size gate (AGENTS.md).
#[path = "relay_diagnostics_connection_reason.rs"]
mod connection_reason;
pub use connection_reason::ConnectionReasonRow;
use connection_reason::{connection_reason_from_fb, create_connection_reason};

// NoticeRow model + encode/decode helpers extracted to satisfy the 500-LOC gate.
#[path = "relay_diagnostics_notice.rs"]
mod notice;
use flatbuffers::{FlatBufferBuilder, WIPOffset};
pub use notice::NoticeRow;
use notice::{create_notice, notice_from_fb};

use generated::nmp::kernel as fb;

// #1723 — `*_SCHEMA_ID` / `*_FILE_IDENTIFIER` / `*_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("relay_diagnostics_producer_consts.generated.rs");

/// A field-for-field mirror of one SERIALISED `RelayDiagnosticsWireSub` row.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct WireSubRow {
    pub wire_id: String,
    pub relay_url: String,
    pub filter_summary: String,
    /// Raw state string. Shells title-case for display and derive their own hue.
    pub state: String,
    /// Raw consumer count. Shells format for display.
    pub consumer_count: u32,
    /// Raw events received counter. Shells format as compact count when > 0.
    pub events_rx: u64,
    pub eose_observed: bool,
    /// Unix epoch milliseconds when the subscription opened. 0 when unknown.
    pub opened_ms: u64,
    /// Unix epoch milliseconds of the last event; 0 when none.
    pub last_event_ms: u64,
    /// Unix epoch milliseconds when EOSE was observed; 0 when none.
    pub eose_ms: u64,
    pub close_reason: Option<String>,
}

/// A field-for-field mirror of one SERIALISED `RelayDiagnosticsRow`.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RelayRow {
    pub relay_url: String,
    /// Raw role string. Shells title-case for display and derive their own hue.
    pub role: String,
    /// Raw connection string. Shells title-case for display and derive their own hue.
    pub connection: String,
    /// Raw auth string. Shells title-case for display and derive their own hue.
    pub auth: String,
    pub total_sub_count: u32,
    pub active_sub_count: u32,
    pub eosed_sub_count: u32,
    pub total_events_rx: u64,
    pub reconnect_count: u32,
    /// Raw bytes received. Shells format as "X KB" etc. when > 0.
    pub bytes_rx: u64,
    /// Raw bytes transmitted. Shells format as "X KB" etc. when > 0.
    pub bytes_tx: u64,
    /// Unix epoch milliseconds of the last successful connect; 0 when never connected.
    pub last_connected_ms: u64,
    /// Unix epoch milliseconds of the last event received; 0 when none.
    pub last_event_ms: u64,
    pub last_notice: Option<String>,
    pub notice_count: u64,
    pub notices: Vec<NoticeRow>,
    pub last_error: Option<String>,
    pub wire_subs: Vec<WireSubRow>,
    /// Raw discovery kind numbers (deduplicated, sorted). Shells format for display.
    pub discovery_kinds: Vec<u64>,
    /// ADR-0051 — the relay's NIP-11 information document; `None` until fetched.
    pub info: Option<InfoRow>,
    /// Routing provenance reasons (SPLIT A, pre-block). Empty before the first
    /// compile or when no attribution is available.
    pub reasons: Vec<ConnectionReasonRow>,
}

/// A field-for-field mirror of one SERIALISED `RelayDiagnosticsInfo` (ADR-0051).
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct InfoRow {
    pub name: Option<String>,
    pub description: Option<String>,
    pub icon: Option<String>,
    pub pubkey: Option<String>,
    pub contact: Option<String>,
    pub software: Option<String>,
    pub version: Option<String>,
    pub supported_nips: Vec<u32>,
    pub payment_required: Option<bool>,
    pub auth_required: Option<bool>,
    pub restricted_writes: Option<bool>,
}

/// A field-for-field mirror of one SERIALISED `RelayDiagnosticsInterest` row.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct InterestRow {
    pub key: String,
    pub state: String,
    pub refcount: u32,
    pub cache_coverage: String,
    pub relay_urls: Vec<String>,
}

/// The `"relay_diagnostics"` read model — `{ relays, interests }`.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct RelayDiagnosticsModel {
    pub relays: Vec<RelayRow>,
    pub interests: Vec<InterestRow>,
}

// --- encode ---------------------------------------------------------------

fn create_wire_sub<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    row: &WireSubRow,
) -> WIPOffset<fb::RelayDiagnosticsWireSub<'a>> {
    let wire_id = fbb.create_string(&row.wire_id);
    let relay_url = fbb.create_string(&row.relay_url);
    let filter_summary = fbb.create_string(&row.filter_summary);
    let state = fbb.create_string(&row.state);
    let close_reason = row.close_reason.as_ref().map(|v| fbb.create_string(v));
    fb::RelayDiagnosticsWireSub::create(
        fbb,
        &fb::RelayDiagnosticsWireSubArgs {
            wire_id: Some(wire_id),
            relay_url: Some(relay_url),
            filter_summary: Some(filter_summary),
            state: Some(state),
            consumer_count: row.consumer_count,
            events_rx: row.events_rx,
            eose_observed: row.eose_observed,
            opened_ms: row.opened_ms,
            last_event_ms: row.last_event_ms,
            eose_ms: row.eose_ms,
            has_close_reason: row.close_reason.is_some(),
            close_reason,
        },
    )
}

fn create_info<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    info: &InfoRow,
) -> WIPOffset<fb::RelayDiagnosticsInfo<'a>> {
    let name = info.name.as_ref().map(|v| fbb.create_string(v));
    let description = info.description.as_ref().map(|v| fbb.create_string(v));
    let icon = info.icon.as_ref().map(|v| fbb.create_string(v));
    let pubkey = info.pubkey.as_ref().map(|v| fbb.create_string(v));
    let contact = info.contact.as_ref().map(|v| fbb.create_string(v));
    let software = info.software.as_ref().map(|v| fbb.create_string(v));
    let version = info.version.as_ref().map(|v| fbb.create_string(v));
    let supported_nips = fbb.create_vector(&info.supported_nips);
    fb::RelayDiagnosticsInfo::create(
        fbb,
        &fb::RelayDiagnosticsInfoArgs {
            has_name: info.name.is_some(),
            name,
            has_description: info.description.is_some(),
            description,
            has_icon: info.icon.is_some(),
            icon,
            has_pubkey: info.pubkey.is_some(),
            pubkey,
            has_contact: info.contact.is_some(),
            contact,
            has_software: info.software.is_some(),
            software,
            has_version: info.version.is_some(),
            version,
            supported_nips: Some(supported_nips),
            has_payment_required: info.payment_required.is_some(),
            payment_required: info.payment_required.unwrap_or(false),
            has_auth_required: info.auth_required.is_some(),
            auth_required: info.auth_required.unwrap_or(false),
            has_restricted_writes: info.restricted_writes.is_some(),
            restricted_writes: info.restricted_writes.unwrap_or(false),
        },
    )
}

fn create_relay_row<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    row: &RelayRow,
) -> WIPOffset<fb::RelayDiagnosticsRow<'a>> {
    let wire_offsets: Vec<WIPOffset<fb::RelayDiagnosticsWireSub<'_>>> = row
        .wire_subs
        .iter()
        .map(|w| create_wire_sub(fbb, w))
        .collect();
    let wire_subs = fbb.create_vector(&wire_offsets);
    let reason_offsets: Vec<WIPOffset<fb::RelayConnectionReason<'_>>> = row
        .reasons
        .iter()
        .map(|r| create_connection_reason(fbb, r))
        .collect();
    let reasons = fbb.create_vector(&reason_offsets);
    let notice_offsets: Vec<WIPOffset<fb::RelayDiagnosticsNotice<'_>>> =
        row.notices.iter().map(|n| create_notice(fbb, n)).collect();
    let notices = fbb.create_vector(&notice_offsets);
    let info = row.info.as_ref().map(|i| create_info(fbb, i));
    let relay_url = fbb.create_string(&row.relay_url);
    let role = fbb.create_string(&row.role);
    let connection = fbb.create_string(&row.connection);
    let auth = fbb.create_string(&row.auth);
    let last_notice = row.last_notice.as_ref().map(|v| fbb.create_string(v));
    let last_error = row.last_error.as_ref().map(|v| fbb.create_string(v));
    let discovery_kinds = fbb.create_vector(&row.discovery_kinds);
    fb::RelayDiagnosticsRow::create(
        fbb,
        &fb::RelayDiagnosticsRowArgs {
            relay_url: Some(relay_url),
            role: Some(role),
            connection: Some(connection),
            auth: Some(auth),
            total_sub_count: row.total_sub_count,
            active_sub_count: row.active_sub_count,
            eosed_sub_count: row.eosed_sub_count,
            total_events_rx: row.total_events_rx,
            reconnect_count: row.reconnect_count,
            bytes_rx: row.bytes_rx,
            bytes_tx: row.bytes_tx,
            last_connected_ms: row.last_connected_ms,
            last_event_ms: row.last_event_ms,
            has_last_notice: row.last_notice.is_some(),
            last_notice,
            notice_count: row.notice_count,
            notices: Some(notices),
            has_last_error: row.last_error.is_some(),
            last_error,
            wire_subs: Some(wire_subs),
            info,
            discovery_kinds: Some(discovery_kinds),
            reasons: Some(reasons),
        },
    )
}

fn create_interest<'a>(
    fbb: &mut FlatBufferBuilder<'a>,
    row: &InterestRow,
) -> WIPOffset<fb::RelayDiagnosticsInterest<'a>> {
    let url_offsets: Vec<WIPOffset<&str>> = row
        .relay_urls
        .iter()
        .map(|u| fbb.create_string(u))
        .collect();
    let relay_urls = fbb.create_vector(&url_offsets);
    let key = fbb.create_string(&row.key);
    let state = fbb.create_string(&row.state);
    let cache_coverage = fbb.create_string(&row.cache_coverage);
    fb::RelayDiagnosticsInterest::create(
        fbb,
        &fb::RelayDiagnosticsInterestArgs {
            key: Some(key),
            state: Some(state),
            refcount: row.refcount,
            cache_coverage: Some(cache_coverage),
            relay_urls: Some(relay_urls),
        },
    )
}

/// Encode a [`RelayDiagnosticsModel`] to typed FlatBuffers bytes (with the
/// `KRDG` file identifier).
#[must_use]
pub(crate) fn encode_relay_diagnostics(model: &RelayDiagnosticsModel) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();
    let relay_offsets: Vec<WIPOffset<fb::RelayDiagnosticsRow<'_>>> = model
        .relays
        .iter()
        .map(|r| create_relay_row(&mut fbb, r))
        .collect();
    let relays = fbb.create_vector(&relay_offsets);
    let interest_offsets: Vec<WIPOffset<fb::RelayDiagnosticsInterest<'_>>> = model
        .interests
        .iter()
        .map(|i| create_interest(&mut fbb, i))
        .collect();
    let interests = fbb.create_vector(&interest_offsets);
    let root = fb::RelayDiagnosticsSnapshot::create(
        &mut fbb,
        &fb::RelayDiagnosticsSnapshotArgs {
            relays: Some(relays),
            interests: Some(interests),
        },
    );
    fb::finish_relay_diagnostics_snapshot_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by [`encode_relay_diagnostics`])
/// back into a [`RelayDiagnosticsModel`]. Returns an error string on any
/// malformed input.
pub fn decode_relay_diagnostics(bytes: &[u8]) -> Result<RelayDiagnosticsModel, String> {
    if bytes.len() < 8 || !fb::relay_diagnostics_snapshot_buffer_has_identifier(bytes) {
        return Err("missing KRDG file identifier".to_string());
    }
    let root = fb::root_as_relay_diagnostics_snapshot(bytes)
        .map_err(|e| format!("not a valid RelayDiagnosticsSnapshot buffer: {e}"))?;

    let mut relays = Vec::new();
    if let Some(fb_relays) = root.relays() {
        relays.reserve(fb_relays.len());
        for r in fb_relays.iter() {
            relays.push(relay_row_from_fb(r));
        }
    }
    let mut interests = Vec::new();
    if let Some(fb_interests) = root.interests() {
        interests.reserve(fb_interests.len());
        for i in fb_interests.iter() {
            interests.push(interest_from_fb(i));
        }
    }
    Ok(RelayDiagnosticsModel { relays, interests })
}

fn opt(s: Option<&str>) -> Option<String> {
    s.map(str::to_string)
}

fn wire_sub_from_fb(row: fb::RelayDiagnosticsWireSub<'_>) -> WireSubRow {
    WireSubRow {
        wire_id: row.wire_id().unwrap_or_default().to_string(),
        relay_url: row.relay_url().unwrap_or_default().to_string(),
        filter_summary: row.filter_summary().unwrap_or_default().to_string(),
        state: row.state().unwrap_or_default().to_string(),
        consumer_count: row.consumer_count(),
        events_rx: row.events_rx(),
        eose_observed: row.eose_observed(),
        opened_ms: row.opened_ms(),
        last_event_ms: row.last_event_ms(),
        eose_ms: row.eose_ms(),
        close_reason: row
            .has_close_reason()
            .then(|| opt(row.close_reason()))
            .flatten(),
    }
}

fn relay_row_from_fb(row: fb::RelayDiagnosticsRow<'_>) -> RelayRow {
    let mut wire_subs = Vec::new();
    if let Some(fb_subs) = row.wire_subs() {
        wire_subs.reserve(fb_subs.len());
        for s in fb_subs.iter() {
            wire_subs.push(wire_sub_from_fb(s));
        }
    }
    let mut reasons = Vec::new();
    if let Some(fb_reasons) = row.reasons() {
        reasons.reserve(fb_reasons.len());
        for r in fb_reasons.iter() {
            reasons.push(connection_reason_from_fb(r));
        }
    }
    let notices = row
        .notices()
        .map(|v| v.iter().map(notice_from_fb).collect())
        .unwrap_or_default();
    let discovery_kinds = row
        .discovery_kinds()
        .map(|v| v.iter().collect())
        .unwrap_or_default();
    RelayRow {
        relay_url: row.relay_url().unwrap_or_default().to_string(),
        role: row.role().unwrap_or_default().to_string(),
        connection: row.connection().unwrap_or_default().to_string(),
        auth: row.auth().unwrap_or_default().to_string(),
        total_sub_count: row.total_sub_count(),
        active_sub_count: row.active_sub_count(),
        eosed_sub_count: row.eosed_sub_count(),
        total_events_rx: row.total_events_rx(),
        reconnect_count: row.reconnect_count(),
        bytes_rx: row.bytes_rx(),
        bytes_tx: row.bytes_tx(),
        last_connected_ms: row.last_connected_ms(),
        last_event_ms: row.last_event_ms(),
        last_notice: row
            .has_last_notice()
            .then(|| opt(row.last_notice()))
            .flatten(),
        notice_count: row.notice_count(),
        notices,
        last_error: row
            .has_last_error()
            .then(|| opt(row.last_error()))
            .flatten(),
        wire_subs,
        discovery_kinds,
        info: row.info().map(info_from_fb),
        reasons,
    }
}

fn info_from_fb(info: fb::RelayDiagnosticsInfo<'_>) -> InfoRow {
    let mut supported_nips = Vec::new();
    if let Some(nips) = info.supported_nips() {
        supported_nips.reserve(nips.len());
        for n in nips.iter() {
            supported_nips.push(n);
        }
    }
    InfoRow {
        name: info.has_name().then(|| opt(info.name())).flatten(),
        description: info
            .has_description()
            .then(|| opt(info.description()))
            .flatten(),
        icon: info.has_icon().then(|| opt(info.icon())).flatten(),
        pubkey: info.has_pubkey().then(|| opt(info.pubkey())).flatten(),
        contact: info.has_contact().then(|| opt(info.contact())).flatten(),
        software: info.has_software().then(|| opt(info.software())).flatten(),
        version: info.has_version().then(|| opt(info.version())).flatten(),
        supported_nips,
        payment_required: info.has_payment_required().then(|| info.payment_required()),
        auth_required: info.has_auth_required().then(|| info.auth_required()),
        restricted_writes: info
            .has_restricted_writes()
            .then(|| info.restricted_writes()),
    }
}

fn interest_from_fb(row: fb::RelayDiagnosticsInterest<'_>) -> InterestRow {
    let mut relay_urls = Vec::new();
    if let Some(urls) = row.relay_urls() {
        relay_urls.reserve(urls.len());
        for u in urls.iter() {
            relay_urls.push(u.to_string());
        }
    }
    InterestRow {
        key: row.key().unwrap_or_default().to_string(),
        state: row.state().unwrap_or_default().to_string(),
        refcount: row.refcount(),
        cache_coverage: row.cache_coverage().unwrap_or_default().to_string(),
        relay_urls,
    }
}

#[cfg(test)]
#[path = "relay_diagnostics_fb_tests.rs"]
mod tests;
