// automatically generated by the FlatBuffers compiler, do not modify

package nmp.embed

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ArticleProjection : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ArticleProjection {
        __init(_i, _bb)
        return this
    }
    val id : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val authorPubkey : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authorPubkeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun authorPubkeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val hasAuthorDisplayName : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val authorDisplayName : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authorDisplayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun authorDisplayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val hasAuthorPictureUrl : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val authorPictureUrl : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authorPictureUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun authorPictureUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val createdAt : ULong
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val hasTitle : Boolean
        get() {
            val o = __offset(18)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val title : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val titleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(20, 1)
    fun titleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 20, 1)
    val hasSummary : Boolean
        get() {
            val o = __offset(22)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val summary : String?
        get() {
            val o = __offset(24)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val summaryAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(24, 1)
    fun summaryInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 24, 1)
    val hasHeroImageUrl : Boolean
        get() {
            val o = __offset(26)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val heroImageUrl : String?
        get() {
            val o = __offset(28)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val heroImageUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(28, 1)
    fun heroImageUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 28, 1)
    val dTag : String?
        get() {
            val o = __offset(30)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val dTagAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(30, 1)
    fun dTagInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 30, 1)
    fun contentTree(j: Int) : UByte {
        val o = __offset(32)
        return if (o != 0) {
            bb.get(__vector(o) + j * 1).toUByte()
        } else {
            0u
        }
    }
    val contentTreeLength : Int
        get() {
            val o = __offset(32); return if (o != 0) __vector_len(o) else 0
        }
    val contentTreeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(32, 1)
    fun contentTreeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 32, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsArticleProjection(_bb: ByteBuffer): ArticleProjection = getRootAsArticleProjection(_bb, ArticleProjection())
        fun getRootAsArticleProjection(_bb: ByteBuffer, obj: ArticleProjection): ArticleProjection {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createArticleProjection(builder: FlatBufferBuilder, idOffset: Int, authorPubkeyOffset: Int, hasAuthorDisplayName: Boolean, authorDisplayNameOffset: Int, hasAuthorPictureUrl: Boolean, authorPictureUrlOffset: Int, createdAt: ULong, hasTitle: Boolean, titleOffset: Int, hasSummary: Boolean, summaryOffset: Int, hasHeroImageUrl: Boolean, heroImageUrlOffset: Int, dTagOffset: Int, contentTreeOffset: Int) : Int {
            builder.startTable(15)
            addCreatedAt(builder, createdAt)
            addContentTree(builder, contentTreeOffset)
            addDTag(builder, dTagOffset)
            addHeroImageUrl(builder, heroImageUrlOffset)
            addSummary(builder, summaryOffset)
            addTitle(builder, titleOffset)
            addAuthorPictureUrl(builder, authorPictureUrlOffset)
            addAuthorDisplayName(builder, authorDisplayNameOffset)
            addAuthorPubkey(builder, authorPubkeyOffset)
            addId(builder, idOffset)
            addHasHeroImageUrl(builder, hasHeroImageUrl)
            addHasSummary(builder, hasSummary)
            addHasTitle(builder, hasTitle)
            addHasAuthorPictureUrl(builder, hasAuthorPictureUrl)
            addHasAuthorDisplayName(builder, hasAuthorDisplayName)
            return endArticleProjection(builder)
        }
        fun startArticleProjection(builder: FlatBufferBuilder) = builder.startTable(15)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addOffset(0, id, 0)
        fun addAuthorPubkey(builder: FlatBufferBuilder, authorPubkey: Int) = builder.addOffset(1, authorPubkey, 0)
        fun addHasAuthorDisplayName(builder: FlatBufferBuilder, hasAuthorDisplayName: Boolean) = builder.addBoolean(2, hasAuthorDisplayName, false)
        fun addAuthorDisplayName(builder: FlatBufferBuilder, authorDisplayName: Int) = builder.addOffset(3, authorDisplayName, 0)
        fun addHasAuthorPictureUrl(builder: FlatBufferBuilder, hasAuthorPictureUrl: Boolean) = builder.addBoolean(4, hasAuthorPictureUrl, false)
        fun addAuthorPictureUrl(builder: FlatBufferBuilder, authorPictureUrl: Int) = builder.addOffset(5, authorPictureUrl, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: ULong) = builder.addLong(6, createdAt.toLong(), 0)
        fun addHasTitle(builder: FlatBufferBuilder, hasTitle: Boolean) = builder.addBoolean(7, hasTitle, false)
        fun addTitle(builder: FlatBufferBuilder, title: Int) = builder.addOffset(8, title, 0)
        fun addHasSummary(builder: FlatBufferBuilder, hasSummary: Boolean) = builder.addBoolean(9, hasSummary, false)
        fun addSummary(builder: FlatBufferBuilder, summary: Int) = builder.addOffset(10, summary, 0)
        fun addHasHeroImageUrl(builder: FlatBufferBuilder, hasHeroImageUrl: Boolean) = builder.addBoolean(11, hasHeroImageUrl, false)
        fun addHeroImageUrl(builder: FlatBufferBuilder, heroImageUrl: Int) = builder.addOffset(12, heroImageUrl, 0)
        fun addDTag(builder: FlatBufferBuilder, dTag: Int) = builder.addOffset(13, dTag, 0)
        fun addContentTree(builder: FlatBufferBuilder, contentTree: Int) = builder.addOffset(14, contentTree, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createContentTreeVector(builder: FlatBufferBuilder, data: UByteArray) : Int {
            builder.startVector(1, data.size, 1)
            for (i in data.size - 1 downTo 0) {
                builder.addByte(data[i].toByte())
            }
            return builder.endVector()
        }
        fun startContentTreeVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(1, numElems, 1)
        fun endArticleProjection(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
