// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AccountSummaryRow : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AccountSummaryRow {
        __init(_i, _bb)
        return this
    }
    val id : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val npub : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val npubAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun npubInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val hasDisplayName : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val displayName : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val displayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun displayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val signerKind : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val signerKindAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun signerKindInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val status : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val statusAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun statusInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val signerIsRemote : Boolean
        get() {
            val o = __offset(18)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isActive : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hasPictureUrl : Boolean
        get() {
            val o = __offset(22)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val pictureUrl : String?
        get() {
            val o = __offset(24)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val pictureUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(24, 1)
    fun pictureUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 24, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAccountSummaryRow(_bb: ByteBuffer): AccountSummaryRow = getRootAsAccountSummaryRow(_bb, AccountSummaryRow())
        fun getRootAsAccountSummaryRow(_bb: ByteBuffer, obj: AccountSummaryRow): AccountSummaryRow {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createAccountSummaryRow(builder: FlatBufferBuilder, idOffset: Int, npubOffset: Int, hasDisplayName: Boolean, displayNameOffset: Int, signerKindOffset: Int, statusOffset: Int, signerIsRemote: Boolean, isActive: Boolean, hasPictureUrl: Boolean, pictureUrlOffset: Int) : Int {
            builder.startTable(11)
            addPictureUrl(builder, pictureUrlOffset)
            addStatus(builder, statusOffset)
            addSignerKind(builder, signerKindOffset)
            addDisplayName(builder, displayNameOffset)
            addNpub(builder, npubOffset)
            addId(builder, idOffset)
            addHasPictureUrl(builder, hasPictureUrl)
            addIsActive(builder, isActive)
            addSignerIsRemote(builder, signerIsRemote)
            addHasDisplayName(builder, hasDisplayName)
            return endAccountSummaryRow(builder)
        }
        fun startAccountSummaryRow(builder: FlatBufferBuilder) = builder.startTable(11)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addOffset(0, id, 0)
        fun addNpub(builder: FlatBufferBuilder, npub: Int) = builder.addOffset(1, npub, 0)
        fun addHasDisplayName(builder: FlatBufferBuilder, hasDisplayName: Boolean) = builder.addBoolean(2, hasDisplayName, false)
        fun addDisplayName(builder: FlatBufferBuilder, displayName: Int) = builder.addOffset(3, displayName, 0)
        fun addSignerKind(builder: FlatBufferBuilder, signerKind: Int) = builder.addOffset(4, signerKind, 0)
        fun addStatus(builder: FlatBufferBuilder, status: Int) = builder.addOffset(5, status, 0)
        fun addSignerIsRemote(builder: FlatBufferBuilder, signerIsRemote: Boolean) = builder.addBoolean(7, signerIsRemote, false)
        fun addIsActive(builder: FlatBufferBuilder, isActive: Boolean) = builder.addBoolean(8, isActive, false)
        fun addHasPictureUrl(builder: FlatBufferBuilder, hasPictureUrl: Boolean) = builder.addBoolean(9, hasPictureUrl, false)
        fun addPictureUrl(builder: FlatBufferBuilder, pictureUrl: Int) = builder.addOffset(10, pictureUrl, 0)
        fun endAccountSummaryRow(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
