// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ProfileCard : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ProfileCard {
        __init(_i, _bb)
        return this
    }
    val pubkey : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val pubkeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun pubkeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val hasDisplayName : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val displayName : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val displayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun displayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val hasPictureUrl : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val pictureUrl : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val pictureUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun pictureUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val nip05 : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nip05AsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun nip05InByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val about : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val aboutAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun aboutInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val hasLnurl : Boolean
        get() {
            val o = __offset(18)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lnurl : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lnurlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(20, 1)
    fun lnurlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 20, 1)
    val hasName : Boolean
        get() {
            val o = __offset(22)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val name : String?
        get() {
            val o = __offset(24)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(24, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 24, 1)
    val hasRawDisplayName : Boolean
        get() {
            val o = __offset(26)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val rawDisplayName : String?
        get() {
            val o = __offset(28)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val rawDisplayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(28, 1)
    fun rawDisplayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 28, 1)
    val hasDisplayNameCamel : Boolean
        get() {
            val o = __offset(30)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val displayNameCamel : String?
        get() {
            val o = __offset(32)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val displayNameCamelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(32, 1)
    fun displayNameCamelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 32, 1)
    val hasBanner : Boolean
        get() {
            val o = __offset(34)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val banner : String?
        get() {
            val o = __offset(36)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val bannerAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(36, 1)
    fun bannerInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 36, 1)
    val hasWebsite : Boolean
        get() {
            val o = __offset(38)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val website : String?
        get() {
            val o = __offset(40)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val websiteAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(40, 1)
    fun websiteInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 40, 1)
    val hasLud16 : Boolean
        get() {
            val o = __offset(42)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lud16 : String?
        get() {
            val o = __offset(44)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lud16AsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(44, 1)
    fun lud16InByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 44, 1)
    val hasLud06 : Boolean
        get() {
            val o = __offset(46)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lud06 : String?
        get() {
            val o = __offset(48)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lud06AsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(48, 1)
    fun lud06InByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 48, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsProfileCard(_bb: ByteBuffer): ProfileCard = getRootAsProfileCard(_bb, ProfileCard())
        fun getRootAsProfileCard(_bb: ByteBuffer, obj: ProfileCard): ProfileCard {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createProfileCard(builder: FlatBufferBuilder, pubkeyOffset: Int, hasDisplayName: Boolean, displayNameOffset: Int, hasPictureUrl: Boolean, pictureUrlOffset: Int, nip05Offset: Int, aboutOffset: Int, hasLnurl: Boolean, lnurlOffset: Int, hasName: Boolean, nameOffset: Int, hasRawDisplayName: Boolean, rawDisplayNameOffset: Int, hasDisplayNameCamel: Boolean, displayNameCamelOffset: Int, hasBanner: Boolean, bannerOffset: Int, hasWebsite: Boolean, websiteOffset: Int, hasLud16: Boolean, lud16Offset: Int, hasLud06: Boolean, lud06Offset: Int) : Int {
            builder.startTable(23)
            addLud06(builder, lud06Offset)
            addLud16(builder, lud16Offset)
            addWebsite(builder, websiteOffset)
            addBanner(builder, bannerOffset)
            addDisplayNameCamel(builder, displayNameCamelOffset)
            addRawDisplayName(builder, rawDisplayNameOffset)
            addName(builder, nameOffset)
            addLnurl(builder, lnurlOffset)
            addAbout(builder, aboutOffset)
            addNip05(builder, nip05Offset)
            addPictureUrl(builder, pictureUrlOffset)
            addDisplayName(builder, displayNameOffset)
            addPubkey(builder, pubkeyOffset)
            addHasLud06(builder, hasLud06)
            addHasLud16(builder, hasLud16)
            addHasWebsite(builder, hasWebsite)
            addHasBanner(builder, hasBanner)
            addHasDisplayNameCamel(builder, hasDisplayNameCamel)
            addHasRawDisplayName(builder, hasRawDisplayName)
            addHasName(builder, hasName)
            addHasLnurl(builder, hasLnurl)
            addHasPictureUrl(builder, hasPictureUrl)
            addHasDisplayName(builder, hasDisplayName)
            return endProfileCard(builder)
        }
        fun startProfileCard(builder: FlatBufferBuilder) = builder.startTable(23)
        fun addPubkey(builder: FlatBufferBuilder, pubkey: Int) = builder.addOffset(0, pubkey, 0)
        fun addHasDisplayName(builder: FlatBufferBuilder, hasDisplayName: Boolean) = builder.addBoolean(1, hasDisplayName, false)
        fun addDisplayName(builder: FlatBufferBuilder, displayName: Int) = builder.addOffset(2, displayName, 0)
        fun addHasPictureUrl(builder: FlatBufferBuilder, hasPictureUrl: Boolean) = builder.addBoolean(3, hasPictureUrl, false)
        fun addPictureUrl(builder: FlatBufferBuilder, pictureUrl: Int) = builder.addOffset(4, pictureUrl, 0)
        fun addNip05(builder: FlatBufferBuilder, nip05: Int) = builder.addOffset(5, nip05, 0)
        fun addAbout(builder: FlatBufferBuilder, about: Int) = builder.addOffset(6, about, 0)
        fun addHasLnurl(builder: FlatBufferBuilder, hasLnurl: Boolean) = builder.addBoolean(7, hasLnurl, false)
        fun addLnurl(builder: FlatBufferBuilder, lnurl: Int) = builder.addOffset(8, lnurl, 0)
        fun addHasName(builder: FlatBufferBuilder, hasName: Boolean) = builder.addBoolean(9, hasName, false)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(10, name, 0)
        fun addHasRawDisplayName(builder: FlatBufferBuilder, hasRawDisplayName: Boolean) = builder.addBoolean(11, hasRawDisplayName, false)
        fun addRawDisplayName(builder: FlatBufferBuilder, rawDisplayName: Int) = builder.addOffset(12, rawDisplayName, 0)
        fun addHasDisplayNameCamel(builder: FlatBufferBuilder, hasDisplayNameCamel: Boolean) = builder.addBoolean(13, hasDisplayNameCamel, false)
        fun addDisplayNameCamel(builder: FlatBufferBuilder, displayNameCamel: Int) = builder.addOffset(14, displayNameCamel, 0)
        fun addHasBanner(builder: FlatBufferBuilder, hasBanner: Boolean) = builder.addBoolean(15, hasBanner, false)
        fun addBanner(builder: FlatBufferBuilder, banner: Int) = builder.addOffset(16, banner, 0)
        fun addHasWebsite(builder: FlatBufferBuilder, hasWebsite: Boolean) = builder.addBoolean(17, hasWebsite, false)
        fun addWebsite(builder: FlatBufferBuilder, website: Int) = builder.addOffset(18, website, 0)
        fun addHasLud16(builder: FlatBufferBuilder, hasLud16: Boolean) = builder.addBoolean(19, hasLud16, false)
        fun addLud16(builder: FlatBufferBuilder, lud16: Int) = builder.addOffset(20, lud16, 0)
        fun addHasLud06(builder: FlatBufferBuilder, hasLud06: Boolean) = builder.addBoolean(21, hasLud06, false)
        fun addLud06(builder: FlatBufferBuilder, lud06: Int) = builder.addOffset(22, lud06, 0)
        fun endProfileCard(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
