// automatically generated by the FlatBuffers compiler, do not modify

package nmp.kernel

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SignerState : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SignerState {
        __init(_i, _bb)
        return this
    }
    val signerKind : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val signerKindAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun signerKindInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val state : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stateAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun stateInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val hasReason : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val reason : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val reasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun reasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val isReady : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isAwaitingApproval : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isReconnecting : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isUnavailable : Boolean
        get() {
            val o = __offset(18)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val isFailed : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSignerState(_bb: ByteBuffer): SignerState = getRootAsSignerState(_bb, SignerState())
        fun getRootAsSignerState(_bb: ByteBuffer, obj: SignerState): SignerState {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun SignerStateBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "KSST")
        fun createSignerState(builder: FlatBufferBuilder, signerKindOffset: Int, stateOffset: Int, hasReason: Boolean, reasonOffset: Int, isReady: Boolean, isAwaitingApproval: Boolean, isReconnecting: Boolean, isUnavailable: Boolean, isFailed: Boolean) : Int {
            builder.startTable(9)
            addReason(builder, reasonOffset)
            addState(builder, stateOffset)
            addSignerKind(builder, signerKindOffset)
            addIsFailed(builder, isFailed)
            addIsUnavailable(builder, isUnavailable)
            addIsReconnecting(builder, isReconnecting)
            addIsAwaitingApproval(builder, isAwaitingApproval)
            addIsReady(builder, isReady)
            addHasReason(builder, hasReason)
            return endSignerState(builder)
        }
        fun startSignerState(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addSignerKind(builder: FlatBufferBuilder, signerKind: Int) = builder.addOffset(0, signerKind, 0)
        fun addState(builder: FlatBufferBuilder, state: Int) = builder.addOffset(1, state, 0)
        fun addHasReason(builder: FlatBufferBuilder, hasReason: Boolean) = builder.addBoolean(2, hasReason, false)
        fun addReason(builder: FlatBufferBuilder, reason: Int) = builder.addOffset(3, reason, 0)
        fun addIsReady(builder: FlatBufferBuilder, isReady: Boolean) = builder.addBoolean(4, isReady, false)
        fun addIsAwaitingApproval(builder: FlatBufferBuilder, isAwaitingApproval: Boolean) = builder.addBoolean(5, isAwaitingApproval, false)
        fun addIsReconnecting(builder: FlatBufferBuilder, isReconnecting: Boolean) = builder.addBoolean(6, isReconnecting, false)
        fun addIsUnavailable(builder: FlatBufferBuilder, isUnavailable: Boolean) = builder.addBoolean(7, isUnavailable, false)
        fun addIsFailed(builder: FlatBufferBuilder, isFailed: Boolean) = builder.addBoolean(8, isFailed, false)
        fun endSignerState(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishSignerStateBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "KSST")
        fun finishSizePrefixedSignerStateBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "KSST")
    }
}
