// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip47

@Suppress("unused")
class NwcConnectionState private constructor() {
    companion object {
        const val Connected: UByte = 0u
        const val Reconnecting: UByte = 1u
        const val TransportLost: UByte = 2u
    }
}
