// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip01

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class NoteRelationCounts : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : NoteRelationCounts {
        __init(_i, _bb)
        return this
    }
    val replies : nmp.nip01.RelationCount? get() = replies(nmp.nip01.RelationCount())
    fun replies(obj: nmp.nip01.RelationCount) : nmp.nip01.RelationCount? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val reactions : nmp.nip01.RelationCount? get() = reactions(nmp.nip01.RelationCount())
    fun reactions(obj: nmp.nip01.RelationCount) : nmp.nip01.RelationCount? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val reposts : nmp.nip01.RelationCount? get() = reposts(nmp.nip01.RelationCount())
    fun reposts(obj: nmp.nip01.RelationCount) : nmp.nip01.RelationCount? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val zaps : nmp.nip01.RelationCount? get() = zaps(nmp.nip01.RelationCount())
    fun zaps(obj: nmp.nip01.RelationCount) : nmp.nip01.RelationCount? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val comments : nmp.nip01.RelationCount? get() = comments(nmp.nip01.RelationCount())
    fun comments(obj: nmp.nip01.RelationCount) : nmp.nip01.RelationCount? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsNoteRelationCounts(_bb: ByteBuffer): NoteRelationCounts = getRootAsNoteRelationCounts(_bb, NoteRelationCounts())
        fun getRootAsNoteRelationCounts(_bb: ByteBuffer, obj: NoteRelationCounts): NoteRelationCounts {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createNoteRelationCounts(builder: FlatBufferBuilder, repliesOffset: Int, reactionsOffset: Int, repostsOffset: Int, zapsOffset: Int, commentsOffset: Int) : Int {
            builder.startTable(5)
            addComments(builder, commentsOffset)
            addZaps(builder, zapsOffset)
            addReposts(builder, repostsOffset)
            addReactions(builder, reactionsOffset)
            addReplies(builder, repliesOffset)
            return endNoteRelationCounts(builder)
        }
        fun startNoteRelationCounts(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addReplies(builder: FlatBufferBuilder, replies: Int) = builder.addOffset(0, replies, 0)
        fun addReactions(builder: FlatBufferBuilder, reactions: Int) = builder.addOffset(1, reactions, 0)
        fun addReposts(builder: FlatBufferBuilder, reposts: Int) = builder.addOffset(2, reposts, 0)
        fun addZaps(builder: FlatBufferBuilder, zaps: Int) = builder.addOffset(3, zaps, 0)
        fun addComments(builder: FlatBufferBuilder, comments: Int) = builder.addOffset(4, comments, 0)
        fun endNoteRelationCounts(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
