// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip01

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RelationCountInterest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelationCountInterest {
        __init(_i, _bb)
        return this
    }
    val namespace : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val namespaceAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun namespaceInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val targetEventId : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val targetEventIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun targetEventIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val tag : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val tagAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun tagInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelationCountInterest(_bb: ByteBuffer): RelationCountInterest = getRootAsRelationCountInterest(_bb, RelationCountInterest())
        fun getRootAsRelationCountInterest(_bb: ByteBuffer, obj: RelationCountInterest): RelationCountInterest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRelationCountInterest(builder: FlatBufferBuilder, namespaceOffset: Int, targetEventIdOffset: Int, tagOffset: Int) : Int {
            builder.startTable(3)
            addTag(builder, tagOffset)
            addTargetEventId(builder, targetEventIdOffset)
            addNamespace(builder, namespaceOffset)
            return endRelationCountInterest(builder)
        }
        fun startRelationCountInterest(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addNamespace(builder: FlatBufferBuilder, namespace: Int) = builder.addOffset(0, namespace, 0)
        fun addTargetEventId(builder: FlatBufferBuilder, targetEventId: Int) = builder.addOffset(1, targetEventId, 0)
        fun addTag(builder: FlatBufferBuilder, tag: Int) = builder.addOffset(2, tag, 0)
        fun endRelationCountInterest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
