// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip01

@Suppress("unused")
class ThreadPointerKind private constructor() {
    companion object {
        const val Event: UByte = 0u
        const val Address: UByte = 1u
        const val External: UByte = 2u
    }
}
