// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip01

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ThreadPointer : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ThreadPointer {
        __init(_i, _bb)
        return this
    }
    val kind : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val id : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val coord : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val coordAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun coordInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val uri : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val uriAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun uriInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val relay : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val relayAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun relayInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val hasKindNum : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val kindNum : UInt
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsThreadPointer(_bb: ByteBuffer): ThreadPointer = getRootAsThreadPointer(_bb, ThreadPointer())
        fun getRootAsThreadPointer(_bb: ByteBuffer, obj: ThreadPointer): ThreadPointer {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createThreadPointer(builder: FlatBufferBuilder, kind: UByte, idOffset: Int, coordOffset: Int, uriOffset: Int, relayOffset: Int, hasKindNum: Boolean, kindNum: UInt) : Int {
            builder.startTable(7)
            addKindNum(builder, kindNum)
            addRelay(builder, relayOffset)
            addUri(builder, uriOffset)
            addCoord(builder, coordOffset)
            addId(builder, idOffset)
            addHasKindNum(builder, hasKindNum)
            addKind(builder, kind)
            return endThreadPointer(builder)
        }
        fun startThreadPointer(builder: FlatBufferBuilder) = builder.startTable(7)
        fun addKind(builder: FlatBufferBuilder, kind: UByte) = builder.addByte(0, kind.toByte(), 0)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addOffset(1, id, 0)
        fun addCoord(builder: FlatBufferBuilder, coord: Int) = builder.addOffset(2, coord, 0)
        fun addUri(builder: FlatBufferBuilder, uri: Int) = builder.addOffset(3, uri, 0)
        fun addRelay(builder: FlatBufferBuilder, relay: Int) = builder.addOffset(4, relay, 0)
        fun addHasKindNum(builder: FlatBufferBuilder, hasKindNum: Boolean) = builder.addBoolean(5, hasKindNum, false)
        fun addKindNum(builder: FlatBufferBuilder, kindNum: UInt) = builder.addInt(6, kindNum.toInt(), 0)
        fun endThreadPointer(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
