// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip01

@Suppress("unused")
class TimelineBlockKind private constructor() {
    companion object {
        const val Standalone: UByte = 0u
        const val Module: UByte = 1u
    }
}
