// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip01

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class TimelineBlockEntry : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TimelineBlockEntry {
        __init(_i, _bb)
        return this
    }
    val kind : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val standaloneId : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val standaloneIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun standaloneIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val standaloneRoot : nmp.nip01.ThreadPointer? get() = standaloneRoot(nmp.nip01.ThreadPointer())
    fun standaloneRoot(obj: nmp.nip01.ThreadPointer) : nmp.nip01.ThreadPointer? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun moduleEventIds(j: Int) : nmp.nip01.BlockEventId? = moduleEventIds(nmp.nip01.BlockEventId(), j)
    fun moduleEventIds(obj: nmp.nip01.BlockEventId, j: Int) : nmp.nip01.BlockEventId? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val moduleEventIdsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val moduleHasGap : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val moduleRoot : nmp.nip01.ThreadPointer? get() = moduleRoot(nmp.nip01.ThreadPointer())
    fun moduleRoot(obj: nmp.nip01.ThreadPointer) : nmp.nip01.ThreadPointer? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTimelineBlockEntry(_bb: ByteBuffer): TimelineBlockEntry = getRootAsTimelineBlockEntry(_bb, TimelineBlockEntry())
        fun getRootAsTimelineBlockEntry(_bb: ByteBuffer, obj: TimelineBlockEntry): TimelineBlockEntry {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTimelineBlockEntry(builder: FlatBufferBuilder, kind: UByte, standaloneIdOffset: Int, standaloneRootOffset: Int, moduleEventIdsOffset: Int, moduleHasGap: Boolean, moduleRootOffset: Int) : Int {
            builder.startTable(6)
            addModuleRoot(builder, moduleRootOffset)
            addModuleEventIds(builder, moduleEventIdsOffset)
            addStandaloneRoot(builder, standaloneRootOffset)
            addStandaloneId(builder, standaloneIdOffset)
            addModuleHasGap(builder, moduleHasGap)
            addKind(builder, kind)
            return endTimelineBlockEntry(builder)
        }
        fun startTimelineBlockEntry(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addKind(builder: FlatBufferBuilder, kind: UByte) = builder.addByte(0, kind.toByte(), 0)
        fun addStandaloneId(builder: FlatBufferBuilder, standaloneId: Int) = builder.addOffset(1, standaloneId, 0)
        fun addStandaloneRoot(builder: FlatBufferBuilder, standaloneRoot: Int) = builder.addOffset(2, standaloneRoot, 0)
        fun addModuleEventIds(builder: FlatBufferBuilder, moduleEventIds: Int) = builder.addOffset(3, moduleEventIds, 0)
        fun createModuleEventIdsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startModuleEventIdsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addModuleHasGap(builder: FlatBufferBuilder, moduleHasGap: Boolean) = builder.addBoolean(4, moduleHasGap, false)
        fun addModuleRoot(builder: FlatBufferBuilder, moduleRoot: Int) = builder.addOffset(5, moduleRoot, 0)
        fun endTimelineBlockEntry(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
