#!/usr/bin/env python3
"""Static triage for common RMP/NMP architecture violations.

This script intentionally favors actionable suspicion over completeness. It
does not prove compliance; it points reviewers at places that need judgment.

Precision notes (see references/rules.md "Scanner Precision And Canonical
Allowances"):

- App/operator relay policy is the audited D3 opt-out, not a routing bypass.
  Relay URLs declared in app/operator config surfaces downgrade to warnings;
  relay URLs at ordinary send/publish/view-open call sites stay errors.
- Generated files are mechanical derivations of a canonical source. They are
  skipped; review the canonical source instead.
- One-shot presentation timers (toast dismissal, copy feedback, focus, initial
  scroll) are not polling. Repeating timers and sleep-in-loop patterns are.
- D6 only flags error handling at the FFI boundary, not ordinary native
  OS/capability try/catch. `#[uniffi::export]` is the canonical native binding
  decorator after the clean-break and is NOT itself a smell; a `Result`/`throws`
  near the boundary is.

This scanner is a complement to the doctrine-lint binary, not a replacement.
Doctrine-lint owns the Rust D-rules (D0, D6-D27, product_raw_read, ...). The
scanner's comparative advantage is cross-language heuristics (Swift/Kotlin/TS),
checks doctrine-lint has no rule for yet, and runs on external app repos that do
not build doctrine-lint. Rules below scoped with a path predicate target the
2026 redesign spine (see references/*.md); they avoid duplicating doctrine-lint.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


EXCLUDED_DIRS = {
    ".git",
    ".gradle",
    ".idea",
    ".swiftpm",
    "build",
    "DerivedData",
    "docs",
    "examples",
    "fixtures",
    "node_modules",
    "target",
    "tests",
    "testdata",
    ".build",
    "dist",
    "vendor",
    "wiki",
}

TEXT_EXTENSIONS = {
    ".rs",
    ".swift",
    ".kt",
    ".kts",
    ".java",
    ".ts",
    ".tsx",
    ".js",
    ".jsx",
    ".mjs",
    ".c",
    ".cc",
    ".cpp",
    ".h",
    ".hpp",
}

NATIVE_EXTENSIONS = {".swift", ".kt", ".kts", ".java", ".ts", ".tsx", ".js", ".jsx", ".mjs"}

# Markers that identify a file as generated output of a canonical source. The
# canonical source is what reviewers must inspect; the generated artifact is a
# mechanical derivation (D4 single source of truth).
GENERATED_FILENAME_HINTS = (".generated.", ".g.dart", ".pb.rs", ".pb.go", "_generated.")
GENERATED_HEADER_MARKERS = (
    "@generated",
    "do not edit",
    "code generated",
    "generated by",
    "autogenerated",
    "auto-generated",
    "this file is automatically generated",
    "@codegen",
)


@dataclass
class Finding:
    severity: str
    rule: str
    path: str
    line: int
    match: str
    reason: str


def iter_files(root: Path) -> Iterable[Path]:
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(part in EXCLUDED_DIRS for part in path.parts):
            continue
        if path.suffix not in TEXT_EXTENSIONS:
            continue
        yield path


def is_generated_file(path: Path, lines: list[str]) -> bool:
    """A generated file is a mechanical derivation; scan its canonical source."""
    name = path.name.lower()
    if any(hint in name for hint in GENERATED_FILENAME_HINTS):
        return True
    head = "\n".join(lines[:8]).lower()
    return any(marker in head for marker in GENERATED_HEADER_MARKERS)


def is_relay_policy_surface(path: Path) -> bool:
    """App/operator relay-policy declaration site (audited D3 opt-out).

    Hardcoded relays here are operator policy declarations, not routing
    bypasses at a send/publish/view-open call site.
    """
    name = path.name.lower()
    if any(hint in name for hint in ("config", "relay_policy", "relaypolicy", "defaults", "bootstrap")):
        return True
    for part in path.parts:
        lowered = part.lower()
        if "config" in lowered or lowered.endswith("-config") or lowered.endswith("_config"):
            return True
    return False


def is_display_string_line(line: str) -> bool:
    """Native presentation string (placeholder/prompt/label), not a routing call."""
    stripped = line.strip()
    if stripped.startswith("Text(") or stripped.startswith("Label("):
        return True
    return bool(re.search(r"\b(placeholder|prompt|accessibilityLabel|footnote|helpText)\b", line))


# --- Path predicates for spine-scoped rules -------------------------------
# A rule may carry an optional predicate over the repo-relative path. It fires
# only where the predicate holds. This keeps NMP-internal layer rules quiet on
# external app repos and vice versa, and keeps the scanner from duplicating the
# doctrine-lint Rust gates.

def _norm(rel: str) -> str:
    return rel.replace("\\", "/")


def is_framework_crate(rel: str) -> bool:
    """A shared NMP framework crate (crates/nmp-*)."""
    return "crates/nmp-" in _norm(rel)


def is_app_code(rel: str) -> bool:
    """App-layer code: anything that is not a shared NMP framework crate.

    True for app roots under apps/ and for external consumer repos (whose code
    never lives under crates/nmp-). This is where register_defaults and raw read
    surfaces are violations.
    """
    return not is_framework_crate(rel)


def is_sub_l5_framework_crate(rel: str) -> bool:
    """L0-L4 framework crate: a shared crate that is not a binding/runtime/composition
    crate (L6) or a tooling/render sidecar (nmp-cli/-codegen/-testing)."""
    r = _norm(rel)
    if "crates/nmp-" not in r:
        return False
    return not any(
        x in r
        for x in (
            "nmp-uniffi",
            "nmp-native-runtime",
            "nmp-browser-runtime",
            "nmp-defaults",
            "nmp-cli",
            "nmp-codegen",
            "nmp-testing",
        )
    )


def is_nip_crate(rel: str) -> bool:
    return bool(re.search(r"nmp-nip\d", _norm(rel)))


def is_nip_protocol_crate(rel: str) -> bool:
    """A NIP protocol crate, excluding its `-runtime` sibling (a runtime legitimately
    sits atop its own base protocol crate, which is not a cross-NIP dependency)."""
    return is_nip_crate(rel) and "-runtime" not in _norm(rel)


def should_skip_line(path: Path, line: str) -> bool:
    parts = set(path.parts)
    if {"docs", "wiki", "README.md", "CHANGELOG.md", "AGENTS.md", "CLAUDE.md"} & parts:
        return True
    if "test" in path.name.lower() or "tests" in parts:
        return True
    stripped = line.strip()
    if not stripped:
        return True
    if stripped.startswith("//") or stripped.startswith("#") or stripped.startswith("*"):
        return True
    if stripped.startswith("Text(") or stripped.startswith("Label("):
        return True
    return False


# Inherently-repeating poll loops and Rust sleeps. Always an error: these
# re-arm or block-and-recheck rather than waiting on a blocking primitive.
POLLING_RE = re.compile(
    r"\b(thread::sleep|setInterval|while\s+.*sleep|loop\s*\{[^}]*sleep|"
    r"try_recv\b.*sleep|sleep\b.*try_recv)"
)
# Repeating Apple timer. Polling when it re-fires; one-shot otherwise.
REPEATING_TIMER_RE = re.compile(r"Timer\.scheduledTimer")
# Single-fire timers. Allowed for native presentation, forbidden when used to
# re-arm a loop (caught via surrounding loop context).
ONESHOT_TIMER_RE = re.compile(
    r"\b(Task\.sleep|setTimeout)\b|DispatchQueue\.[A-Za-z0-9_.]+\.asyncAfter"
)
LOOP_CONTEXT_RE = re.compile(r"\b(while|for|loop|repeat)\b")

ONESHOT_TIMER_REASON = (
    "One-shot presentation timer (toast/copy-feedback/focus/initial-scroll). "
    "Allowed only in native presentation; must never drive domain state or re-arm a loop."
)

HARDCODED_RELAY_RE = re.compile(r"wss://[A-Za-z0-9._~:/?#\[\]@!$&'()*+,;=%-]+")
RELAY_POLICY_REASON = (
    "Relay URL in an app/operator config surface. This is the audited D3 opt-out "
    "(operator relay policy), not a framework default; verify it is a policy "
    "declaration and not a send/publish/view-open routing bypass."
)


def classify_polling(line: str, back_window: str, fwd_window: str) -> tuple[str, str, str] | None:
    """Return (severity, rule, reason) for D8 timer/sleep usage, or None.

    ``back_window`` is the preceding lines (used to detect an enclosing loop);
    ``fwd_window`` is the current line plus following lines (used to read a
    timer's ``repeats:`` argument when the call spans lines). The ``repeats:``
    flag is never read from ``back_window`` so a prior timer cannot leak its
    flag onto this one.
    """
    if POLLING_RE.search(line):
        return (
            "error",
            "D8/no-polling",
            "Polling or sleep-check loops are forbidden; use blocking primitives or callbacks.",
        )
    if REPEATING_TIMER_RE.search(line):
        if re.search(r"repeats\s*:\s*true", fwd_window):
            return (
                "error",
                "D8/no-polling",
                "Repeating timer polls on a schedule; use blocking primitives or callbacks.",
            )
        # repeats:false or argument not visible: one-shot presentation timer.
        return ("warning", "D8/one-shot-timer", ONESHOT_TIMER_REASON)
    if ONESHOT_TIMER_RE.search(line):
        if LOOP_CONTEXT_RE.search(back_window):
            return (
                "error",
                "D8/no-polling",
                "One-shot timer inside a loop re-arms a poll; use blocking primitives or callbacks.",
            )
        return ("warning", "D8/one-shot-timer", ONESHOT_TIMER_REASON)
    return None


# Static rules with a fixed severity. Each tuple is
#   (severity, rule, pattern, reason, ext_filter, path_pred)
# where ext_filter restricts file suffixes (or None) and path_pred is an
# optional predicate over the repo-relative path (or None = any path).
# Dynamic rules (D8 polling, D3 relay, D6 ffi) are handled explicitly in scan().
RULES = [
    (
        "warning",
        "D9/kernel-owns-time",
        re.compile(r"\b(SystemTime::now|Instant::now|Date\(\)|Date\.now|currentTimeMillis|NSDate\(\))\b"),
        "Reducer, replay, routing, or policy code must use an injected clock.",
        None,
        None,
    ),
    (
        "warning",
        "D5/bounded-snapshot",
        re.compile(r"\b(AppState|Snapshot|FullState)\b.*\b(Vec<.*Event|Vec<.*Note|event_store|history|all_events)\b", re.I),
        "Snapshots should be screen-shaped and bounded by open views, never event history.",
        None,
        None,
    ),
    (
        "warning",
        "D7/native-policy-smell",
        re.compile(
            r"\b(shouldRetry|isRecoverable|retryCount|relayUrl|relay_url|publishRelay|reconnectRelay|"
            r"decrypt|encrypt|signEvent|nostrEvent|NostrEvent|Filter|Kind|kind\s*[=:])\b"
        ),
        "Native code may be rendering or capability execution only; verify this is not policy.",
        NATIVE_EXTENSIONS,
        None,
    ),
    (
        "warning",
        "D4/native-cache-smell",
        re.compile(r"\b(cache|cached|RoomDatabase|SwiftData|UserDefaults|SharedPreferences)\b"),
        "Native caches must not mirror Rust-owned app facts.",
        NATIVE_EXTENSIONS,
        None,
    ),
    (
        "warning",
        "no-debt",
        re.compile(r"(\bTODO\b|\bFIXME\b|\bHACK\b|\btemporary\b|\bfor now\b|\bstub\b|\bworkaround\b)"),
        "Temporary hacks, TODO debt, stubs, and workaround paths require canonical tracking or removal.",
        None,
        None,
    ),
    # --- 2026 redesign-spine rules (complement doctrine-lint) ---------------
    (
        "warning",
        "ADR-0069/no-register-defaults",
        re.compile(r"(?<!fn )\bregister_defaults\s*\("),
        "register_defaults() is killed as a production app path (ADR-0069). Compose explicitly: "
        "register_substrate() + named protocol installers. A preset needs a named owner + deletion gate.",
        {".rs"},
        is_app_code,
    ),
    (
        "warning",
        "ADR-0070/raw-read-surface",
        re.compile(r"\b(open_interest|ObservedProjectionRegistrar|ObservedProjectionReconciler)\b"),
        "Raw read substrate (ADR-0070). Product screens open typed read sessions (open_feed/"
        "open_search_session); open_interest/ObservedProjection are private machinery.",
        {".rs"},
        is_app_code,
    ),
    (
        "warning",
        "D-ABI/new-framework-c-abi",
        re.compile(r"\bpub\s+extern\s+\"C\"\s+fn\b"),
        "New pub extern \"C\" fn in a framework crate is an ABI regression (UniFFI is the sole "
        "native surface). Use #[uniffi::export]; app-owned glue belongs in apps/ with an owning issue.",
        {".rs"},
        is_framework_crate,
    ),
    (
        "warning",
        "layer-inversion/display-in-wire",
        re.compile(r"\b(author_display_name|author_picture_url|has_author_display|has_author_picture)\b"),
        "Display fields in an L0-L4 crate projection/wire table violate display separation; only "
        "ProfileProjection carries display strings. Join author_pubkey -> profile at L5 (#2514).",
        {".rs"},
        is_sub_l5_framework_crate,
    ),
    # NIP-29 kind-blindness (foreign-kind literals, kind-named actions) is enforced in Rust by
    # the doctrine-lint `nip29_kind_blind` rule (#2513/#2540) — not duplicated here, since the
    # only crate it would match (crates/nmp-nip29) is exactly what doctrine-lint already covers.
    (
        "warning",
        "protocol-purity/cross-nip-import",
        re.compile(r"\buse\s+nmp_nip\d+\s*::"),
        "Cross-nip import: protocol crates should not depend on each other (an L0 vocab/types crate "
        "or a crate's own -runtime base is fine). Compose cross-protocol features at the app layer.",
        {".rs"},
        is_nip_protocol_crate,
    ),
    (
        "warning",
        "ADR-0053/retired-projection-tier-vocab",
        re.compile(r"\b(declare_consumed_projections|Tier-1|Tier-2|Tier-3)\b"),
        "Retired projection-tier vocabulary (ADR-0053 folded into ADR-0070). Product reads open typed "
        "read sessions; declare_consumed_projections is output-transport plumbing, not a read API.",
        {".rs"},
        is_app_code,
    ),
    (
        "warning",
        "ADR-0071/dispatch-as-success",
        re.compile(
            r"\b(correlationId|correlation_id)\b.{0,80}\b(success|onSuccess|isPublished|markDone|markPublished|completed|onComplete)\b",
            re.I,
        ),
        "dispatch acceptance (correlation_id) is not publish success. Terminal status arrives via the "
        "PublishStatusView projection / action_results state on a later tick (ADR-0071, D6).",
        NATIVE_EXTENSIONS,
        None,
    ),
]

D6_PATTERN = re.compile(
    r"(extern\s+\"C\"|@Throws|throws\b|try\s*\{|catch\s*\(|->\s*Result\s*<)"
)
D6_REASON = "Errors must surface as state, not native exceptions or FFI Result types."


def has_ffi_context(rel: str, window: str) -> bool:
    lowered_window = window.lower()
    lowered_rel = rel.lower()
    return (
        "uniffi::export" in window
        or 'extern "C"' in window
        or "uniffi" in lowered_window
        or "ffi" in lowered_rel
        or "bindings" in lowered_rel
    )


def scan(root: Path) -> list[Finding]:
    findings: list[Finding] = []
    for path in iter_files(root):
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rel = str(path.relative_to(root))
        lines = text.splitlines()
        if is_generated_file(path, lines):
            continue
        is_native = path.suffix in NATIVE_EXTENSIONS
        relay_policy_surface = is_relay_policy_surface(path)
        skip_from = None
        if path.suffix == ".rs":
            for idx, raw in enumerate(lines, start=1):
                if "#[cfg(test)]" in raw:
                    skip_from = idx
                    break
        for line_no, line in enumerate(lines, start=1):
            if skip_from is not None and line_no >= skip_from:
                continue
            if should_skip_line(path, line):
                continue
            window = "\n".join(lines[max(0, line_no - 6) : line_no + 1])
            back_window = "\n".join(lines[max(0, line_no - 6) : line_no])
            fwd_window = "\n".join(lines[line_no - 1 : line_no + 2])

            # D8 — polling vs one-shot presentation timers.
            polling = classify_polling(line, back_window, fwd_window)
            if polling is not None:
                severity, rule, reason = polling
                findings.append(
                    Finding(severity, rule, rel, line_no, line.strip()[:180], reason)
                )

            # D3 — hardcoded relay vs app/operator policy declaration.
            relay_match = HARDCODED_RELAY_RE.search(line)
            if relay_match and not (
                "assert" in line or "relay.example" in line or "wss://x" in line
            ):
                if relay_policy_surface:
                    findings.append(
                        Finding(
                            "warning", "D3/no-hardcoded-relay", rel, line_no,
                            line.strip()[:180], RELAY_POLICY_REASON,
                        )
                    )
                elif is_native and is_display_string_line(line):
                    findings.append(
                        Finding(
                            "warning", "D3/no-hardcoded-relay", rel, line_no,
                            line.strip()[:180],
                            "Relay URL in a native display/placeholder string; verify it is "
                            "presentation only and not used to route a send/publish.",
                        )
                    )
                else:
                    findings.append(
                        Finding(
                            "error", "D3/no-hardcoded-relay", rel, line_no,
                            line.strip()[:180],
                            "Hardcoded relay URLs in production code usually bypass outbox routing.",
                        )
                    )

            # D6 — error handling only at the FFI boundary.
            if D6_PATTERN.search(line) and has_ffi_context(rel, window):
                findings.append(
                    Finding("warning", "D6/no-ffi-errors", rel, line_no, line.strip()[:180], D6_REASON)
                )

            # Remaining fixed-severity rules.
            for severity, rule, pattern, reason, ext_filter, path_pred in RULES:
                if ext_filter is not None and path.suffix not in ext_filter:
                    continue
                if path_pred is not None and not path_pred(rel):
                    continue
                if not pattern.search(line):
                    continue
                findings.append(
                    Finding(severity, rule, rel, line_no, line.strip()[:180], reason)
                )
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("root", nargs="?", default=".", help="Repository or app root to scan")
    parser.add_argument("--json", action="store_true", help="Emit JSON")
    parser.add_argument("--json-out", help="Write JSON findings to this path")
    parser.add_argument("--limit", type=int, default=200, help="Maximum findings to print, 0 for all")
    parser.add_argument(
        "--fail-on",
        choices=["never", "warning", "error"],
        default="never",
        help="Exit nonzero when findings at or above this severity exist",
    )
    args = parser.parse_args()

    root = Path(args.root).resolve()
    findings = scan(root)

    if args.json_out:
        Path(args.json_out).write_text(
            json.dumps([asdict(f) for f in findings], indent=2), encoding="utf-8"
        )

    visible = findings if args.limit == 0 else findings[: args.limit]

    if args.json:
        print(json.dumps([asdict(f) for f in visible], indent=2))
    else:
        if not findings:
            print("nmp-architecture-scan: no findings")
        for f in visible:
            print(f"{f.severity.upper()} {f.rule} {f.path}:{f.line}")
            print(f"  {f.match}")
            print(f"  {f.reason}")
        if len(visible) < len(findings):
            print(f"... {len(findings) - len(visible)} more finding(s); rerun with --limit 0 to show all")

    severities = {f.severity for f in findings}
    if args.fail_on == "error" and "error" in severities:
        return 2
    if args.fail_on == "warning" and findings:
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
