//! GENERATED by `nmp gen concept-reads`; do not edit by hand.
//!
//! This app-owned UniFFI facade slice contains only mechanical
//! marshaling into concept crates that this app composes. The generator
//! keeps `nmp-codegen` dependency-free from those concept crates by
//! stamping their symbol names as text into this app crate.

use nmp_replies::{
    close_replies,
    decode_and_validate_reply_target,
    decode_reply_summary_snapshot,
    open_replies,
    RepliesReadHandle,
};

use crate::facade::GalleryApp;

/// Opaque scalar read handle returned by the generated open door and
/// consumed by the generated close door.
#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]
pub struct GalleryOpenedReplies {
    pub projection_key: String,
    pub handle_id: u64,
}

/// Typed reply-summary output decoded by the generated facade.
#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]
pub struct GalleryReplySummary {
    pub target_id: String,
    pub count: u64,
    pub reply_event_ids: Vec<String>,
}

/// Facade-local concept-read error surface for generated read doors.
#[derive(uniffi::Error, Debug, Clone, Copy, PartialEq, Eq)]
pub enum GalleryReadError {
    /// The target input could not be decoded or validated.
    InvalidTarget,
    /// The concept crate rejected the compiled read plan.
    OpenFailed,
    /// The typed summary payload could not be decoded.
    DecodeFailed,
}

impl core::fmt::Display for GalleryReadError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidTarget => write!(f, "invalid concept-read target"),
            Self::OpenFailed => write!(f, "concept read open rejected the read plan"),
            Self::DecodeFailed => write!(f, "invalid concept-read summary payload"),
        }
    }
}

impl std::error::Error for GalleryReadError {}

#[uniffi::export]
impl GalleryApp {
    /// Open a generated concept read.
    pub fn open_replies(
        &self,
        target_json: String,
    ) -> Result<GalleryOpenedReplies, GalleryReadError> {
        let target = decode_and_validate_reply_target(&target_json)
            .map_err(|_| GalleryReadError::InvalidTarget)?;
        let handle =
            open_replies(self.runtime(), target).map_err(|_| GalleryReadError::OpenFailed)?;
        let (projection_key, handle_id) = handle.into_parts();
        Ok(GalleryOpenedReplies {
            projection_key,
            handle_id,
        })
    }

    /// Close a generated concept read. Idempotent (D6).
    pub fn close_replies(&self, opened: GalleryOpenedReplies) -> bool {
        let handle = RepliesReadHandle::from_parts(opened.projection_key, opened.handle_id);
        close_replies(self.runtime(), handle)
    }

    /// Decode a typed concept-read summary payload emitted by the kernel.
    pub fn decode_reply_summary(
        &self,
        payload: Vec<u8>,
    ) -> Result<GalleryReplySummary, GalleryReadError> {
        let snapshot = decode_reply_summary_snapshot(&payload)
            .map_err(|_| GalleryReadError::DecodeFailed)?;
        Ok(GalleryReplySummary {
            target_id: snapshot.target_id,
            count: snapshot.count,
            reply_event_ids: snapshot.reply_event_ids,
        })
    }
}

#[cfg(test)]
#[path = "concept_reads_replies_tests.rs"]
mod tests;
