// automatically generated by the FlatBuffers compiler, do not modify

package nmp.marmot

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MarmotMessageRow : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MarmotMessageRow {
        __init(_i, _bb)
        return this
    }
    val id : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val senderPubkeyHex : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val senderPubkeyHexAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun senderPubkeyHexInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val content : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val contentAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun contentInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val createdAt : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val hasEpoch : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val epoch : ULong
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMarmotMessageRow(_bb: ByteBuffer): MarmotMessageRow = getRootAsMarmotMessageRow(_bb, MarmotMessageRow())
        fun getRootAsMarmotMessageRow(_bb: ByteBuffer, obj: MarmotMessageRow): MarmotMessageRow {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMarmotMessageRow(builder: FlatBufferBuilder, idOffset: Int, senderPubkeyHexOffset: Int, contentOffset: Int, createdAt: ULong, hasEpoch: Boolean, epoch: ULong) : Int {
            builder.startTable(6)
            addEpoch(builder, epoch)
            addCreatedAt(builder, createdAt)
            addContent(builder, contentOffset)
            addSenderPubkeyHex(builder, senderPubkeyHexOffset)
            addId(builder, idOffset)
            addHasEpoch(builder, hasEpoch)
            return endMarmotMessageRow(builder)
        }
        fun startMarmotMessageRow(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addOffset(0, id, 0)
        fun addSenderPubkeyHex(builder: FlatBufferBuilder, senderPubkeyHex: Int) = builder.addOffset(1, senderPubkeyHex, 0)
        fun addContent(builder: FlatBufferBuilder, content: Int) = builder.addOffset(2, content, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: ULong) = builder.addLong(3, createdAt.toLong(), 0)
        fun addHasEpoch(builder: FlatBufferBuilder, hasEpoch: Boolean) = builder.addBoolean(4, hasEpoch, false)
        fun addEpoch(builder: FlatBufferBuilder, epoch: ULong) = builder.addLong(5, epoch.toLong(), 0)
        fun endMarmotMessageRow(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
