// automatically generated by the FlatBuffers compiler, do not modify

package nmp.marmot

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PendingWelcomeRow : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PendingWelcomeRow {
        __init(_i, _bb)
        return this
    }
    val idHex : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idHexAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idHexInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val groupName : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val groupNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun groupNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val inviterNpub : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val inviterNpubAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun inviterNpubInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPendingWelcomeRow(_bb: ByteBuffer): PendingWelcomeRow = getRootAsPendingWelcomeRow(_bb, PendingWelcomeRow())
        fun getRootAsPendingWelcomeRow(_bb: ByteBuffer, obj: PendingWelcomeRow): PendingWelcomeRow {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPendingWelcomeRow(builder: FlatBufferBuilder, idHexOffset: Int, groupNameOffset: Int, inviterNpubOffset: Int) : Int {
            builder.startTable(3)
            addInviterNpub(builder, inviterNpubOffset)
            addGroupName(builder, groupNameOffset)
            addIdHex(builder, idHexOffset)
            return endPendingWelcomeRow(builder)
        }
        fun startPendingWelcomeRow(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addIdHex(builder: FlatBufferBuilder, idHex: Int) = builder.addOffset(0, idHex, 0)
        fun addGroupName(builder: FlatBufferBuilder, groupName: Int) = builder.addOffset(1, groupName, 0)
        fun addInviterNpub(builder: FlatBufferBuilder, inviterNpub: Int) = builder.addOffset(2, inviterNpub, 0)
        fun endPendingWelcomeRow(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
