// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

@Suppress("unused")
class FrameKind private constructor() {
    companion object {
        const val Snapshot: UByte = 0u
        const val Panic: UByte = 1u
    }
}
