//! Rust UniFFI facade-slice emitter for app-local concept reads (#2899).

use std::collections::{BTreeMap, BTreeSet};

use super::app_registry::{AppConceptRead, LoadedAppConceptReadRegistry};
use super::registry::{SummaryShape, TargetInput};

/// Render the Rust facade slice for an app-local concept-read registry.
#[must_use]
pub fn render_registry(registry: &LoadedAppConceptReadRegistry) -> String {
    let mut out = String::new();
    out.push_str("//! GENERATED by `nmp gen concept-reads`; do not edit by hand.\n");
    out.push_str("//!\n");
    out.push_str("//! This app-owned UniFFI facade slice contains only mechanical\n");
    out.push_str("//! marshaling into concept crates that this app composes. The generator\n");
    out.push_str("//! keeps `nmp-codegen` dependency-free from those concept crates by\n");
    out.push_str("//! stamping their symbol names as text into this app crate.\n\n");
    render_imports(registry, &mut out);
    render_records(registry, &mut out);
    render_error(registry, &mut out);
    render_impl(registry, &mut out);
    if let Some(test_module) = registry.outputs.rust_test_module.as_deref() {
        out.push_str("#[cfg(test)]\n");
        out.push_str(&format!("#[path = \"{test_module}\"]\n"));
        out.push_str("mod tests;\n");
    }
    out
}

fn render_imports(registry: &LoadedAppConceptReadRegistry, out: &mut String) {
    let mut imports: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for read in &registry.reads {
        let symbols = imports.entry(read.concept.rust_crate).or_default();
        symbols.insert(read.concept.close_fn);
        symbols.insert(read.concept.summary.decoder_fn);
        symbols.insert(read.concept.open_fn);
        symbols.insert(read.concept.handle_type);
        if let TargetInput::Json { decoder_fn, .. } = read.concept.target_input {
            symbols.insert(decoder_fn);
        }
    }
    for (rust_crate, symbols) in imports {
        let mut symbols = symbols.into_iter().collect::<Vec<_>>();
        symbols.sort_by_key(|symbol| symbol.to_ascii_lowercase());
        out.push_str(&format!("use {rust_crate}::{{\n"));
        for symbol in symbols {
            out.push_str(&format!("    {symbol},\n"));
        }
        out.push_str("};\n\n");
    }
    out.push_str(&format!(
        "use crate::facade::{};\n\n",
        registry.facade.rust_type
    ));
}

fn render_records(registry: &LoadedAppConceptReadRegistry, out: &mut String) {
    for read in &registry.reads {
        out.push_str("/// Opaque scalar read handle returned by the generated open door and\n");
        out.push_str("/// consumed by the generated close door.\n");
        out.push_str("#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]\n");
        out.push_str(&format!("pub struct {} {{\n", read.opened_record));
        out.push_str("    pub projection_key: String,\n");
        out.push_str("    pub handle_id: u64,\n");
        out.push_str("}\n\n");
        render_summary_record(read, out);
    }
}

fn render_summary_record(read: &AppConceptRead, out: &mut String) {
    match read.concept.summary.shape {
        SummaryShape::Reply => {
            out.push_str("/// Typed reply-summary output decoded by the generated facade.\n");
            out.push_str("#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]\n");
            out.push_str(&format!("pub struct {} {{\n", read.summary.record));
            out.push_str("    pub target_id: String,\n");
            out.push_str("    pub count: u64,\n");
            out.push_str("    pub reply_event_ids: Vec<String>,\n");
            out.push_str("}\n\n");
        }
        SummaryShape::Reaction => {
            let group = read
                .summary
                .group_record
                .as_deref()
                .expect("registry validates reaction group record");
            out.push_str("/// One reaction content-token group in a generated reaction summary.\n");
            out.push_str("#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]\n");
            out.push_str(&format!("pub struct {group} {{\n"));
            out.push_str("    pub token: String,\n");
            out.push_str("    pub count: u64,\n");
            out.push_str("    pub reactor_pubkeys: Vec<String>,\n");
            out.push_str("}\n\n");
            out.push_str("/// Typed reaction-summary output decoded by the generated facade.\n");
            out.push_str("#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]\n");
            out.push_str(&format!("pub struct {} {{\n", read.summary.record));
            out.push_str("    pub target_id: String,\n");
            out.push_str("    pub total: u64,\n");
            out.push_str(&format!("    pub groups: Vec<{group}>,\n"));
            out.push_str("}\n\n");
        }
        SummaryShape::Repost => {
            out.push_str("/// Typed repost-summary output decoded by the generated facade.\n");
            out.push_str("#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]\n");
            out.push_str(&format!("pub struct {} {{\n", read.summary.record));
            out.push_str("    pub target_id: String,\n");
            out.push_str("    pub count: u64,\n");
            out.push_str("    pub reposter_pubkeys: Vec<String>,\n");
            out.push_str("}\n\n");
        }
        SummaryShape::Zap => {
            let zapper = read
                .summary
                .zapper_record
                .as_deref()
                .expect("registry validates zapper record");
            out.push_str("/// One zapper aggregate in a generated zap summary.\n");
            out.push_str("#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]\n");
            out.push_str(&format!("pub struct {zapper} {{\n"));
            out.push_str("    pub pubkey: Option<String>,\n");
            out.push_str("    pub total_msats: u64,\n");
            out.push_str("    pub zap_count: u32,\n");
            out.push_str("}\n\n");
            out.push_str("/// Typed zap-summary output decoded by the generated facade.\n");
            out.push_str("#[derive(uniffi::Record, Debug, Clone, PartialEq, Eq)]\n");
            out.push_str(&format!("pub struct {} {{\n", read.summary.record));
            out.push_str("    pub target_id: String,\n");
            out.push_str("    pub total_msats: u64,\n");
            out.push_str("    pub zap_count: u64,\n");
            out.push_str(&format!("    pub zappers: Vec<{zapper}>,\n"));
            out.push_str("}\n\n");
        }
    }
}

fn render_error(registry: &LoadedAppConceptReadRegistry, out: &mut String) {
    let error = &registry.facade.error_type;
    let invalid = &registry.facade.invalid_target_variant;
    let open_failed = &registry.facade.open_failed_variant;
    let decode_failed = &registry.facade.decode_failed_variant;
    out.push_str("/// Facade-local concept-read error surface for generated read doors.\n");
    out.push_str("#[derive(uniffi::Error, Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str(&format!("pub enum {error} {{\n"));
    out.push_str("    /// The target input could not be decoded or validated.\n");
    out.push_str(&format!("    {invalid},\n"));
    out.push_str("    /// The concept crate rejected the compiled read plan.\n");
    out.push_str(&format!("    {open_failed},\n"));
    out.push_str("    /// The typed summary payload could not be decoded.\n");
    out.push_str(&format!("    {decode_failed},\n"));
    out.push_str("}\n\n");
    out.push_str(&format!("impl core::fmt::Display for {error} {{\n"));
    out.push_str("    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {\n");
    out.push_str("        match self {\n");
    out.push_str(&format!(
        "            Self::{invalid} => write!(f, \"invalid concept-read target\"),\n"
    ));
    out.push_str(&format!(
        "            Self::{open_failed} => write!(f, \"concept read open rejected the read plan\"),\n"
    ));
    out.push_str(&format!(
        "            Self::{decode_failed} => write!(f, \"invalid concept-read summary payload\"),\n"
    ));
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str(&format!("impl std::error::Error for {error} {{}}\n\n"));
}

fn render_impl(registry: &LoadedAppConceptReadRegistry, out: &mut String) {
    out.push_str("#[uniffi::export]\n");
    out.push_str(&format!("impl {} {{\n", registry.facade.rust_type));
    for (index, read) in registry.reads.iter().enumerate() {
        render_open_method(read, registry, out);
        render_close_method(read, registry, out);
        render_decode_method(read, registry, out);
        if index + 1 < registry.reads.len() {
            out.push('\n');
        }
    }
    out.push_str("}\n\n");
}

fn render_open_method(
    read: &AppConceptRead,
    registry: &LoadedAppConceptReadRegistry,
    out: &mut String,
) {
    let error = &registry.facade.error_type;
    let invalid = &registry.facade.invalid_target_variant;
    let open_failed = &registry.facade.open_failed_variant;
    let runtime = &registry.facade.runtime_accessor;
    let open_fn = read.concept.open_fn;
    let record = &read.opened_record;
    match read.concept.target_input {
        TargetInput::Json {
            arg_name,
            decoder_fn,
        } => {
            out.push_str("    /// Open a generated concept read.\n");
            out.push_str(&format!("    pub fn {open_fn}(\n"));
            out.push_str("        &self,\n");
            out.push_str(&format!("        {arg_name}: String,\n"));
            out.push_str(&format!("    ) -> Result<{record}, {error}> {{\n"));
            out.push_str(&format!("        let target = {decoder_fn}(&{arg_name})\n"));
            out.push_str(&format!("            .map_err(|_| {error}::{invalid})?;\n"));
            out.push_str("        let handle =\n");
            out.push_str(&format!(
                "            {open_fn}(self.{runtime}(), target).map_err(|_| {error}::{open_failed})?;\n"
            ));
        }
        TargetInput::PlainString { arg_name } => {
            out.push_str("    /// Open a generated concept read.\n");
            out.push_str(&format!(
                "    pub fn {open_fn}(&self, {arg_name}: String) -> Result<{record}, {error}> {{\n"
            ));
            out.push_str(&format!(
                "        let handle = {open_fn}(self.{runtime}(), {arg_name}).map_err(|_| {error}::{invalid})?;\n"
            ));
        }
    }
    out.push_str("        let (projection_key, handle_id) = handle.into_parts();\n");
    out.push_str(&format!(
        "        Ok({record} {{\n            projection_key,\n            handle_id,\n        }})\n"
    ));
    out.push_str("    }\n\n");
}

fn render_close_method(
    read: &AppConceptRead,
    registry: &LoadedAppConceptReadRegistry,
    out: &mut String,
) {
    let close_fn = read.concept.close_fn;
    let record = &read.opened_record;
    let handle = read.concept.handle_type;
    let runtime = &registry.facade.runtime_accessor;
    out.push_str("    /// Close a generated concept read. Idempotent (D6).\n");
    out.push_str(&format!(
        "    pub fn {close_fn}(&self, opened: {record}) -> bool {{\n"
    ));
    out.push_str(&format!(
        "        let handle = {handle}::from_parts(opened.projection_key, opened.handle_id);\n"
    ));
    out.push_str(&format!("        {close_fn}(self.{runtime}(), handle)\n"));
    out.push_str("    }\n");
}

fn render_decode_method(
    read: &AppConceptRead,
    registry: &LoadedAppConceptReadRegistry,
    out: &mut String,
) {
    let decode_fn = read.concept.summary.decoder_fn;
    let facade_decode_fn = read.concept.summary.facade_decode_fn;
    let record = &read.summary.record;
    let error = &registry.facade.error_type;
    let decode_failed = &registry.facade.decode_failed_variant;
    out.push('\n');
    out.push_str("    /// Decode a typed concept-read summary payload emitted by the kernel.\n");
    out.push_str(&format!("    pub fn {facade_decode_fn}(\n"));
    out.push_str("        &self,\n");
    out.push_str("        payload: Vec<u8>,\n");
    out.push_str(&format!("    ) -> Result<{record}, {error}> {{\n"));
    out.push_str(&format!(
        "        let snapshot = {decode_fn}(&payload)\n            .map_err(|_| {error}::{decode_failed})?;\n"
    ));
    render_summary_conversion(read, out);
    out.push_str("    }\n");
}

fn render_summary_conversion(read: &AppConceptRead, out: &mut String) {
    match read.concept.summary.shape {
        SummaryShape::Reply => {
            out.push_str(&format!("        Ok({} {{\n", read.summary.record));
            out.push_str("            target_id: snapshot.target_id,\n");
            out.push_str("            count: snapshot.count,\n");
            out.push_str("            reply_event_ids: snapshot.reply_event_ids,\n");
            out.push_str("        })\n");
        }
        SummaryShape::Reaction => {
            let group = read
                .summary
                .group_record
                .as_deref()
                .expect("registry validates reaction group record");
            out.push_str("        let groups = snapshot\n");
            out.push_str("            .groups\n");
            out.push_str("            .into_iter()\n");
            out.push_str(&format!("            .map(|group| {group} {{\n"));
            out.push_str("                token: group.token,\n");
            out.push_str("                count: group.count,\n");
            out.push_str("                reactor_pubkeys: group.reactor_pubkeys,\n");
            out.push_str("            })\n");
            out.push_str("            .collect();\n");
            out.push_str(&format!("        Ok({} {{\n", read.summary.record));
            out.push_str("            target_id: snapshot.target_id,\n");
            out.push_str("            total: snapshot.total,\n");
            out.push_str("            groups,\n");
            out.push_str("        })\n");
        }
        SummaryShape::Repost => {
            out.push_str(&format!("        Ok({} {{\n", read.summary.record));
            out.push_str("            target_id: snapshot.target_id,\n");
            out.push_str("            count: snapshot.count,\n");
            out.push_str("            reposter_pubkeys: snapshot.reposter_pubkeys,\n");
            out.push_str("        })\n");
        }
        SummaryShape::Zap => {
            let zapper = read
                .summary
                .zapper_record
                .as_deref()
                .expect("registry validates zapper record");
            out.push_str("        let zappers = snapshot\n");
            out.push_str("            .zappers\n");
            out.push_str("            .into_iter()\n");
            out.push_str(&format!("            .map(|zapper| {zapper} {{\n"));
            out.push_str("                pubkey: zapper.pubkey,\n");
            out.push_str("                total_msats: zapper.total_msats,\n");
            out.push_str("                zap_count: zapper.zap_count,\n");
            out.push_str("            })\n");
            out.push_str("            .collect();\n");
            out.push_str(&format!("        Ok({} {{\n", read.summary.record));
            out.push_str("            target_id: snapshot.target_id,\n");
            out.push_str("            total_msats: snapshot.total_msats,\n");
            out.push_str("            zap_count: snapshot.zap_count,\n");
            out.push_str("            zappers,\n");
            out.push_str("        })\n");
        }
    }
}
