// automatically generated by the FlatBuffers compiler, do not modify

package nmp.transport

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RelayStatus : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelayStatus {
        __init(_i, _bb)
        return this
    }
    val role : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val roleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun roleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val relayUrl : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val relayUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun relayUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val connection : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val connectionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun connectionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val auth : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun authInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val negentropyProbe : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val negentropyProbeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun negentropyProbeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val activeWireSubscriptions : ULong
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val reconnectCount : UInt
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val lastConnectedAtMs : ULong?
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val lastEventAtMs : ULong?
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else null
        }
    val lastNotice : String?
        get() {
            val o = __offset(22)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lastNoticeAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(22, 1)
    fun lastNoticeInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 22, 1)
    val lastError : String?
        get() {
            val o = __offset(24)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lastErrorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(24, 1)
    fun lastErrorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 24, 1)
    val errorCategory : String?
        get() {
            val o = __offset(26)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val errorCategoryAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(26, 1)
    fun errorCategoryInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 26, 1)
    val eventsRx : ULong
        get() {
            val o = __offset(28)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val bytesRx : ULong
        get() {
            val o = __offset(30)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val bytesTx : ULong
        get() {
            val o = __offset(32)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val denied : Boolean
        get() {
            val o = __offset(34)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val lastCloseReason : String?
        get() {
            val o = __offset(36)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lastCloseReasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(36, 1)
    fun lastCloseReasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 36, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelayStatus(_bb: ByteBuffer): RelayStatus = getRootAsRelayStatus(_bb, RelayStatus())
        fun getRootAsRelayStatus(_bb: ByteBuffer, obj: RelayStatus): RelayStatus {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRelayStatus(builder: FlatBufferBuilder, roleOffset: Int, relayUrlOffset: Int, connectionOffset: Int, authOffset: Int, negentropyProbeOffset: Int, activeWireSubscriptions: ULong, reconnectCount: UInt, lastConnectedAtMs: ULong?, lastEventAtMs: ULong?, lastNoticeOffset: Int, lastErrorOffset: Int, errorCategoryOffset: Int, eventsRx: ULong, bytesRx: ULong, bytesTx: ULong, denied: Boolean, lastCloseReasonOffset: Int) : Int {
            builder.startTable(17)
            addBytesTx(builder, bytesTx)
            addBytesRx(builder, bytesRx)
            addEventsRx(builder, eventsRx)
            lastEventAtMs?.run { addLastEventAtMs(builder, lastEventAtMs) }
            lastConnectedAtMs?.run { addLastConnectedAtMs(builder, lastConnectedAtMs) }
            addActiveWireSubscriptions(builder, activeWireSubscriptions)
            addLastCloseReason(builder, lastCloseReasonOffset)
            addErrorCategory(builder, errorCategoryOffset)
            addLastError(builder, lastErrorOffset)
            addLastNotice(builder, lastNoticeOffset)
            addReconnectCount(builder, reconnectCount)
            addNegentropyProbe(builder, negentropyProbeOffset)
            addAuth(builder, authOffset)
            addConnection(builder, connectionOffset)
            addRelayUrl(builder, relayUrlOffset)
            addRole(builder, roleOffset)
            addDenied(builder, denied)
            return endRelayStatus(builder)
        }
        fun startRelayStatus(builder: FlatBufferBuilder) = builder.startTable(17)
        fun addRole(builder: FlatBufferBuilder, role: Int) = builder.addOffset(0, role, 0)
        fun addRelayUrl(builder: FlatBufferBuilder, relayUrl: Int) = builder.addOffset(1, relayUrl, 0)
        fun addConnection(builder: FlatBufferBuilder, connection: Int) = builder.addOffset(2, connection, 0)
        fun addAuth(builder: FlatBufferBuilder, auth: Int) = builder.addOffset(3, auth, 0)
        fun addNegentropyProbe(builder: FlatBufferBuilder, negentropyProbe: Int) = builder.addOffset(4, negentropyProbe, 0)
        fun addActiveWireSubscriptions(builder: FlatBufferBuilder, activeWireSubscriptions: ULong) = builder.addLong(5, activeWireSubscriptions.toLong(), 0)
        fun addReconnectCount(builder: FlatBufferBuilder, reconnectCount: UInt) = builder.addInt(6, reconnectCount.toInt(), 0)
        fun addLastConnectedAtMs(builder: FlatBufferBuilder, lastConnectedAtMs: ULong) = builder.addLong(7, lastConnectedAtMs.toLong(), 0)
        fun addLastEventAtMs(builder: FlatBufferBuilder, lastEventAtMs: ULong) = builder.addLong(8, lastEventAtMs.toLong(), 0)
        fun addLastNotice(builder: FlatBufferBuilder, lastNotice: Int) = builder.addOffset(9, lastNotice, 0)
        fun addLastError(builder: FlatBufferBuilder, lastError: Int) = builder.addOffset(10, lastError, 0)
        fun addErrorCategory(builder: FlatBufferBuilder, errorCategory: Int) = builder.addOffset(11, errorCategory, 0)
        fun addEventsRx(builder: FlatBufferBuilder, eventsRx: ULong) = builder.addLong(12, eventsRx.toLong(), 0)
        fun addBytesRx(builder: FlatBufferBuilder, bytesRx: ULong) = builder.addLong(13, bytesRx.toLong(), 0)
        fun addBytesTx(builder: FlatBufferBuilder, bytesTx: ULong) = builder.addLong(14, bytesTx.toLong(), 0)
        fun addDenied(builder: FlatBufferBuilder, denied: Boolean) = builder.addBoolean(15, denied, false)
        fun addLastCloseReason(builder: FlatBufferBuilder, lastCloseReason: Int) = builder.addOffset(16, lastCloseReason, 0)
        fun endRelayStatus(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
