// automatically generated by the FlatBuffers compiler, do not modify

package nmp.refs

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RefRowDeltaBatch : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RefRowDeltaBatch {
        __init(_i, _bb)
        return this
    }
    val namespace : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val namespaceAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun namespaceInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val baseline : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun rows(j: Int) : nmp.refs.RefRow? = rows(nmp.refs.RefRow(), j)
    fun rows(obj: nmp.refs.RefRow, j: Int) : nmp.refs.RefRow? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val rowsLength : Int
        get() {
            val o = __offset(8); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRefRowDeltaBatch(_bb: ByteBuffer): RefRowDeltaBatch = getRootAsRefRowDeltaBatch(_bb, RefRowDeltaBatch())
        fun getRootAsRefRowDeltaBatch(_bb: ByteBuffer, obj: RefRowDeltaBatch): RefRowDeltaBatch {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun RefRowDeltaBatchBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "NRRD")
        fun createRefRowDeltaBatch(builder: FlatBufferBuilder, namespaceOffset: Int, baseline: Boolean, rowsOffset: Int) : Int {
            builder.startTable(3)
            addRows(builder, rowsOffset)
            addNamespace(builder, namespaceOffset)
            addBaseline(builder, baseline)
            return endRefRowDeltaBatch(builder)
        }
        fun startRefRowDeltaBatch(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addNamespace(builder: FlatBufferBuilder, namespace: Int) = builder.addOffset(0, namespace, 0)
        fun addBaseline(builder: FlatBufferBuilder, baseline: Boolean) = builder.addBoolean(1, baseline, false)
        fun addRows(builder: FlatBufferBuilder, rows: Int) = builder.addOffset(2, rows, 0)
        fun createRowsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startRowsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endRefRowDeltaBatch(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishRefRowDeltaBatchBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "NRRD")
        fun finishSizePrefixedRefRowDeltaBatchBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "NRRD")
    }
}
