// automatically generated by the FlatBuffers compiler, do not modify

package nmp.refs

@Suppress("unused")
class RefRowState private constructor() {
    companion object {
        const val Changed: UByte = 0u
        const val Cleared: UByte = 1u
    }
}
