//! #1939 — neutral typed action contract manifest.
//!
//! This is the action-side twin of [`crate::projection_contract`]: one
//! platform-neutral source for each default typed action's routing namespace,
//! producing crate/module, payload schema id, schema version, FlatBuffers file
//! identifier, default-composition tier, generated-builder posture, public
//! re-export policy, and typed-dispatch exemption state.
//!
//! `nmp-core` stays protocol-neutral: this manifest lives in `nmp-codegen`
//! because it must name NIP namespaces and host-builder facts.

/// Where a default action enters the standard NMP composition.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActionDefaultTier {
    /// Registered by `nmp-core::kernel::default_registry`.
    CoreBuiltin,
    /// Registered by `nmp_defaults::register_substrate`.
    Substrate,
    /// Registered when `NmpDefaults.social` is enabled.
    Social,
    /// Registered when `NmpDefaults.dms` is enabled.
    DirectMessages,
    /// Registered when `NmpDefaults.zaps` is enabled.
    Zaps,
}

/// Whether host action builders are generated for this namespace.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuilderSupport {
    /// Generated by the flat-table `ACTION_BUILDERS` loop.
    GeneratedFlatTable,
    /// Generated by the dedicated `nmp.publish` union-body emitters.
    GeneratedPublishUnion,
    /// Public typed payload exists, but no generated host builder is emitted.
    NotGenerated {
        /// Tracked rationale for the absence.
        reason: &'static str,
    },
}

/// How `nmp-defaults::action_payloads` exposes the payload type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PublicReExportPolicy {
    /// Re-export the typed payload through `nmp_defaults::action_payloads`.
    DefaultsActionPayloads,
}

/// Whether a registered default is allowed to be JSON-only.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TypedDispatchPolicy {
    /// Must implement `ActionPayload` and be reachable through the byte doorway.
    TypedOnly,
    /// Explicit tracked exemption. The issue URL must explain the remaining
    /// migration and deadline; the current table intentionally has none.
    Exempt { issue: &'static str },
}

/// One default typed action's neutral public contract.
#[derive(Debug)]
pub struct ActionContract {
    /// Open-registry routing key stamped into `DispatchEnvelope.action_namespace`.
    pub namespace: &'static str,
    /// Crate/module that registers the action module.
    pub producer: &'static str,
    /// Rust `ActionModule` type that owns this namespace.
    pub module_type: &'static str,
    /// Rust `ActionPayload` type decoded for this namespace.
    pub payload_type: &'static str,
    /// Stable payload schema id (`ActionPayload::SCHEMA_ID`).
    pub schema_id: &'static str,
    /// FlatBuffers schema file path, relative to the repo root.
    pub schema_path: &'static str,
    /// FlatBuffers root type.
    pub root_type: &'static str,
    /// Payload schema version (`ActionPayload::SCHEMA_VERSION`).
    pub schema_version: u32,
    /// Four-byte FlatBuffers `file_identifier`.
    pub file_identifier: &'static str,
    /// Default composition tier.
    pub default_tier: ActionDefaultTier,
    /// Generated host-builder posture.
    pub builder_support: BuilderSupport,
    /// Public typed payload re-export posture.
    pub public_re_export: PublicReExportPolicy,
    /// Typed-dispatch gate posture.
    pub typed_dispatch: TypedDispatchPolicy,
}

mod table;
pub use table::{ACTION_CONTRACT, PUBLISH_NAMESPACE};

/// Look up an action contract by routing namespace.
#[must_use]
pub fn lookup(namespace: &str) -> Option<&'static ActionContract> {
    ACTION_CONTRACT.iter().find(|c| c.namespace == namespace)
}

/// Look up an action contract by namespace and fail closed when it is missing.
///
/// # Panics
/// When `namespace` has no [`ACTION_CONTRACT`] row.
#[must_use]
pub fn contract_for(namespace: &str) -> &'static ActionContract {
    lookup(namespace).unwrap_or_else(|| {
        panic!(
            "no ActionContract entry for namespace {namespace:?} — every default \
             typed action namespace MUST have an ACTION_CONTRACT row"
        )
    })
}

/// Sorted namespaces for the canonical default composition, including the
/// `nmp-core` built-in publish action.
#[must_use]
pub fn canonical_default_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|_| true)
}

/// Sorted namespaces registered by `nmp_defaults::register_substrate`.
#[must_use]
pub fn substrate_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Substrate)
}

/// Sorted social-tier action namespaces.
#[must_use]
pub fn social_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Social)
}

/// Sorted DM-tier action namespaces.
#[must_use]
pub fn dm_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::DirectMessages)
}

/// Sorted zap-tier action namespaces.
#[must_use]
pub fn zap_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Zaps)
}

/// Namespaces with an explicit JSON-only exemption.
#[must_use]
pub fn typed_dispatch_exemption_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| matches!(c.typed_dispatch, TypedDispatchPolicy::Exempt { .. }))
}

fn sorted_namespaces(mut pred: impl FnMut(&ActionContract) -> bool) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = ACTION_CONTRACT
        .iter()
        .filter(|c| pred(c))
        .map(|c| c.namespace)
        .collect();
    out.sort_unstable();
    out.dedup();
    out
}

/// Render a compact Markdown report for PR review.
#[must_use]
pub fn render_action_contract_report() -> String {
    let mut rows: Vec<&ActionContract> = ACTION_CONTRACT.iter().collect();
    rows.sort_unstable_by_key(|c| c.namespace);
    let mut out = String::from(
        "| namespace | tier | schema | file id | builder | re-export | producer |\n\
         |---|---|---|---|---|---|---|\n",
    );
    for c in rows {
        out.push_str(&format!(
            "| `{}` | `{:?}` | `{}` v{} | `{}` | `{}` | `{:?}` | {} |\n",
            c.namespace,
            c.default_tier,
            c.schema_id,
            c.schema_version,
            c.file_identifier,
            builder_label(c.builder_support),
            c.public_re_export,
            c.producer
        ));
    }
    out
}

fn builder_label(support: BuilderSupport) -> &'static str {
    match support {
        BuilderSupport::GeneratedFlatTable => "generated:flat",
        BuilderSupport::GeneratedPublishUnion => "generated:publish-union",
        BuilderSupport::NotGenerated { .. } => "not-generated:tracked",
    }
}

#[cfg(test)]
#[path = "action_contract/tests.rs"]
mod tests;
