//! #1939 — neutral typed action contract manifest.
//!
//! This is the action-side twin of [`crate::projection_contract`]: one
//! platform-neutral source for each default typed action's routing namespace,
//! producing crate/module, payload schema id, schema version, FlatBuffers file
//! identifier, default-composition tier, generated-builder posture, public
//! re-export policy, and typed-dispatch exemption state.
//!
//! `nmp-core` stays protocol-neutral: this manifest lives in `nmp-codegen`
//! because it must name NIP namespaces and host-builder facts.

/// Where a default action enters the standard NMP composition.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActionDefaultTier {
    /// Registered by `nmp-core::kernel::default_registry`.
    CoreBuiltin,
    /// Registered by `nmp_defaults::register_substrate`.
    Substrate,
    /// Registered when `NmpDefaults.social` is enabled.
    Social,
    /// Registered when `NmpDefaults.dms` is enabled.
    DirectMessages,
    /// Post-v1 zap action row. Not registered by `nmp-defaults` v1 composition
    /// (#2318).
    Zaps,
    /// Registered opt-in via `NmpAppBuilder::with_wallet` — NOT part of the
    /// default composition. Excluded from [`canonical_default_action_namespaces`]
    /// so `register_defaults` matching tests stay green.
    Wallet,
    /// Registered when the `marmot` feature is on (MLS-over-Nostr seam). NOT
    /// part of the default composition — `nmp-marmot` is a feature-gated dep.
    /// Excluded from [`canonical_default_action_namespaces`] so the no-marmot
    /// contract set-equality test stays green without a dep on `nmp-marmot`.
    Marmot,
    /// Registered by an app-component crate (e.g. `nmp-relations`, `nmp-blossom`)
    /// that is wired in at app-assembly time, not by `nmp-defaults`. Excluded
    /// from [`canonical_default_action_namespaces`] and from the
    /// `contract_matches_modules_and_default_payload_reexports` test so the
    /// no-blossom / no-relations default build stays green.
    ComponentRegistered,
}

/// Whether host action builders are generated for this namespace.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BuilderSupport {
    /// Generated by the flat-table `ACTION_BUILDERS` loop.
    GeneratedFlatTable,
    /// Generated by the nested NIP-51 bookmark-item builder path.
    GeneratedBookmarkItemTable,
    /// Generated by the NIP-51 bookmark-set item builder path (like
    /// `GeneratedBookmarkItemTable` but for `BookmarkSetUpdatePayload`, which adds
    /// `set_kind:ubyte` and `identifier:string` fields before the `BookmarkItem`
    /// nested table).
    GeneratedBookmarkSetItemTable,
    /// Generated by the dedicated `nmp.publish` union-body emitters.
    GeneratedPublishUnion,
    /// Generated by the dedicated `nmp.marmot` union-body emitters (M14-1c /
    /// #2169). One namespace, nine arms — same union pattern as publish.
    GeneratedMarmotUnion,
    /// Public typed payload exists, but no generated host builder is emitted.
    NotGenerated {
        /// Tracked rationale for the absence.
        reason: &'static str,
    },
}

/// How `nmp-defaults::action_payloads` exposes the payload type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PublicReExportPolicy {
    /// Re-export the typed payload through `nmp_defaults::action_payloads`.
    DefaultsActionPayloads,
    /// Keep the typed payload in its owning crate; not re-exported by
    /// `nmp-defaults`.
    NotReExported {
        /// Tracked rationale for the absence.
        reason: &'static str,
    },
}

/// Whether a registered default is allowed to be JSON-only.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TypedDispatchPolicy {
    /// Must implement `ActionPayload` and be reachable through the byte doorway.
    TypedOnly,
    /// Explicit tracked exemption. The issue URL must explain the remaining
    /// migration and deadline; the current table intentionally has none.
    Exempt { issue: &'static str },
}

/// One default typed action's neutral public contract.
#[derive(Debug)]
pub struct ActionContract {
    /// Open-registry routing key stamped into `DispatchEnvelope.action_namespace`.
    pub namespace: &'static str,
    /// Crate/module that registers the action module.
    pub producer: &'static str,
    /// Rust `ActionModule` type that owns this namespace.
    pub module_type: &'static str,
    /// Rust `ActionPayload` type decoded for this namespace.
    pub payload_type: &'static str,
    /// Positive ownership claim that owns this action namespace/surface.
    pub owner_claim: &'static str,
    /// Stable payload schema id (`ActionPayload::SCHEMA_ID`).
    pub schema_id: &'static str,
    /// FlatBuffers schema file path, relative to the repo root.
    pub schema_path: &'static str,
    /// FlatBuffers root type.
    pub root_type: &'static str,
    /// Payload schema version (`ActionPayload::SCHEMA_VERSION`).
    pub schema_version: u32,
    /// Four-byte FlatBuffers `file_identifier`.
    pub file_identifier: &'static str,
    /// Default composition tier.
    pub default_tier: ActionDefaultTier,
    /// Generated host-builder posture.
    pub builder_support: BuilderSupport,
    /// Public typed payload re-export posture.
    pub public_re_export: PublicReExportPolicy,
    /// Typed-dispatch gate posture.
    pub typed_dispatch: TypedDispatchPolicy,
}

mod table;
// NIP-29 group action entries split out of `table.rs` for 500-LOC cap.
// Referenced by `table.rs` via `super::nip29::*`.
mod nip29;
// Marmot opt-in action entry split out of `table.rs` for 500-LOC cap.
mod marmot;
pub use table::{ACTION_CONTRACT, PUBLISH_NAMESPACE};

/// Look up an action contract by routing namespace.
#[must_use]
pub fn lookup(namespace: &str) -> Option<&'static ActionContract> {
    ACTION_CONTRACT.iter().find(|c| c.namespace == namespace)
}

/// Look up an action contract by namespace and fail closed when it is missing.
///
/// # Panics
/// When `namespace` has no [`ACTION_CONTRACT`] row.
#[must_use]
pub fn contract_for(namespace: &str) -> &'static ActionContract {
    lookup(namespace).unwrap_or_else(|| {
        panic!(
            "no ActionContract entry for namespace {namespace:?} — every default \
             typed action namespace MUST have an ACTION_CONTRACT row"
        )
    })
}

/// Sorted namespaces for the canonical default composition, including the
/// `nmp-core` built-in publish action. Wallet, zaps, and Marmot namespaces are
/// opt-in/post-v1 and are excluded from this set so the `register_defaults`
/// matching test stays green on default builds.
#[must_use]
pub fn canonical_default_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| {
        c.default_tier != ActionDefaultTier::Wallet
            && c.default_tier != ActionDefaultTier::Marmot
            && c.default_tier != ActionDefaultTier::ComponentRegistered
            && c.default_tier != ActionDefaultTier::Zaps
    })
}

/// Sorted wallet-tier action namespaces (opt-in via `with_wallet`).
#[must_use]
pub fn wallet_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Wallet)
}

/// Sorted marmot-tier action namespaces (opt-in via `--features marmot`).
#[must_use]
pub fn marmot_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Marmot)
}

/// Sorted namespaces registered by `nmp_defaults::register_substrate`.
#[must_use]
pub fn substrate_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Substrate)
}

/// Sorted social-tier action namespaces.
#[must_use]
pub fn social_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Social)
}

/// Sorted DM-tier action namespaces.
#[must_use]
pub fn dm_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::DirectMessages)
}

/// Sorted zap-tier action namespaces, retained for post-v1/private crate tests
/// but not registered by `nmp-defaults`.
#[must_use]
pub fn zap_action_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| c.default_tier == ActionDefaultTier::Zaps)
}

/// Namespaces with an explicit JSON-only exemption.
#[must_use]
pub fn typed_dispatch_exemption_namespaces() -> Vec<&'static str> {
    sorted_namespaces(|c| matches!(c.typed_dispatch, TypedDispatchPolicy::Exempt { .. }))
}

fn sorted_namespaces(mut pred: impl FnMut(&ActionContract) -> bool) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = ACTION_CONTRACT
        .iter()
        .filter(|c| pred(c))
        .map(|c| c.namespace)
        .collect();
    out.sort_unstable();
    out.dedup();
    out
}

/// Render a compact Markdown report for PR review.
#[must_use]
pub fn render_action_contract_report() -> String {
    let mut rows: Vec<&ActionContract> = ACTION_CONTRACT.iter().collect();
    rows.sort_unstable_by_key(|c| c.namespace);
    let mut out = String::from(
        "| namespace | tier | schema | file id | builder | re-export | producer |\n\
         |---|---|---|---|---|---|---|\n",
    );
    for c in rows {
        out.push_str(&format!(
            "| `{}` | `{:?}` | `{}` v{} | `{}` | `{}` | `{:?}` | {} |\n",
            c.namespace,
            c.default_tier,
            c.schema_id,
            c.schema_version,
            c.file_identifier,
            builder_label(c.builder_support),
            c.public_re_export,
            c.producer
        ));
    }
    out
}

fn builder_label(support: BuilderSupport) -> &'static str {
    match support {
        BuilderSupport::GeneratedFlatTable => "generated:flat",
        BuilderSupport::GeneratedBookmarkItemTable => "generated:bookmark-item",
        BuilderSupport::GeneratedBookmarkSetItemTable => "generated:bookmark-set-item",
        BuilderSupport::GeneratedPublishUnion => "generated:publish-union",
        BuilderSupport::GeneratedMarmotUnion => "generated:marmot-union",
        BuilderSupport::NotGenerated { .. } => "not-generated:tracked",
    }
}

#[cfg(test)]
#[path = "action_contract/tests.rs"]
mod tests;
