//! ADR-0053 / Workstream-E4 — generator for `nmp-core`'s
//! `KERNEL_BUILTIN_PROJECTION_KEYS` const.
//!
//! The kernel built-in projection key set is **derived from the codegen
//! registry**, not hand-maintained. This module renders a tiny `.generated.rs`
//! containing the const from [`kernel_builtin_projection_keys`], which the
//! kernel `include!`s. A drift gate (`nmp gen builtin-keys --check`, run in
//! `.github/workflows/codegen-drift.yml`) fails any PR whose checked-in file
//! differs from a fresh render, and `nmp-core`'s
//! `builtin_projection_keys_const_matches_runtime` test pins the generated const
//! against the kernel's actual `make_update` emission — so the registry, the
//! generated const, and the producer can never silently diverge.
//!
//! Driven entirely by [`crate::swift_projections_registry`]; takes no schema
//! stdin (same shape as [`crate::swift_typed_decoders`]).

use std::path::Path;

use crate::projection_contract::{
    drain_projection_keys, kernel_builtin_dependencies, kernel_builtin_projection_keys,
    rev_conditional_presence_keys,
};

/// Render the `KERNEL_BUILTIN_PROJECTION_KEYS` Rust source from the registry.
///
/// The output is a `pub const &[&str]` of the sorted Tier-2 kernel built-in
/// keys, included by `crates/nmp-core/src/kernel/update/projections.rs`.
#[must_use]
pub fn render_builtin_keys() -> String {
    let keys = kernel_builtin_projection_keys();
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo run -p nmp-codegen -- gen builtin-keys`. DO NOT EDIT.\n\
         //\n\
         // Source of truth: crates/nmp-codegen/src/projection_contract.rs\n\
         //   (PROJECTION_CONTRACT entries tagged ProjectionTier::KernelBuiltin).\n\
         //   Regenerate + verify drift via\n\
         //   `.github/workflows/codegen-drift.yml` (nmp gen builtin-keys --check).\n\
         //\n\
         // The kernel's `builtin_projection_keys_const_matches_runtime` test pins this\n\
         // const against the actual `make_update` emission, so the generated list, the\n\
         // contract, and the producer cannot diverge.\n",
    );
    out.push_str("pub const KERNEL_BUILTIN_PROJECTION_KEYS: &[&str] = &[\n");
    for key in &keys {
        out.push_str(&format!("    {key:?},\n"));
    }
    out.push_str("];\n");
    out
}

/// Outcome of a `--check` run. Mirrors [`crate::swift::SwiftCheckOutcome`].
#[derive(Debug)]
pub struct BuiltinKeysCheckOutcome {
    /// `true` when the on-disk file matches the freshly-rendered output.
    pub up_to_date: bool,
    /// First differing line (1-based) when not up-to-date; `None` when
    /// up-to-date OR when the file doesn't exist.
    pub first_diff_line: Option<usize>,
}

/// Write the generated const Rust to `out_path`, replacing whatever was there.
///
/// # Errors
/// Filesystem I/O failures.
pub fn generate_builtin_keys(out_path: &Path) -> std::io::Result<()> {
    let rendered = render_builtin_keys();
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(out_path, rendered)
}

/// Diff a freshly-rendered output against the file at `out_path`. A missing
/// file is reported as stale (`up_to_date = false`), matching the other gates.
///
/// # Errors
/// Filesystem I/O failures other than NotFound.
pub fn check_builtin_keys(out_path: &Path) -> std::io::Result<BuiltinKeysCheckOutcome> {
    let rendered = render_builtin_keys();
    let actual = match std::fs::read_to_string(out_path) {
        Ok(s) => s,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            return Ok(BuiltinKeysCheckOutcome {
                up_to_date: false,
                first_diff_line: None,
            });
        }
        Err(err) => return Err(err),
    };
    if actual == rendered {
        return Ok(BuiltinKeysCheckOutcome {
            up_to_date: true,
            first_diff_line: None,
        });
    }
    let first_diff_line = crate::diff_report::first_diff_or_length(&actual, &rendered);
    Ok(BuiltinKeysCheckOutcome {
        up_to_date: false,
        first_diff_line,
    })
}

// ── BUILTIN_PROJECTION_DEPENDENCIES (revision dependency table) ────────────────
//
// #1723: the per-key source-version dependency list each Tier-2 built-in's
// derived revision sums over was hand-maintained in
// `crates/nmp-core/src/kernel/projection_rev/mod.rs`. It is now generated from
// the SAME projection contract as the built-in key set, so the dependency table
// and the key set cannot drift from each other or from the contract.

/// Render the `BUILTIN_PROJECTION_DEPENDENCIES` Rust source from the contract.
///
/// Output is a `pub(crate) const &[(&str, &[&str])]` of `(key, deps)` rows,
/// included by `crates/nmp-core/src/kernel/projection_rev/mod.rs`. The source
/// counter names are emitted as bare identifiers referencing the `SRC_*` consts
/// declared in that module, so the generated file `include!`s into a scope where
/// those consts are in scope.
#[must_use]
pub fn render_builtin_deps() -> String {
    let rows = kernel_builtin_dependencies();
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo run -p nmp-codegen -- gen builtin-deps`. DO NOT EDIT.\n\
         //\n\
         // Source of truth: crates/nmp-codegen/src/projection_contract.rs\n\
         //   (PROJECTION_CONTRACT KernelBuiltin entries' `dependency_versions`).\n\
         //   Regenerate + verify drift via\n\
         //   `.github/workflows/codegen-drift.yml` (nmp gen builtin-deps --check).\n\
         //\n\
         // Source-counter names map to the `SRC_*` consts declared in\n\
         // `kernel/projection_rev/mod.rs` (this file is `include!`d there). The\n\
         // `all_builtin_keys_have_dependency_entries` test pins every built-in key\n\
         // to a row here, so the table and the key set cannot diverge.\n",
    );
    out.push_str(
        "pub(crate) const BUILTIN_PROJECTION_DEPENDENCIES: &[(&str, &[&str])] = &[\n",
    );
    for (key, deps) in &rows {
        let dep_idents: Vec<String> = deps.iter().map(|d| src_const_ident(d)).collect();
        out.push_str(&format!(
            "    ({key:?}, &[{}]),\n",
            dep_idents.join(", ")
        ));
    }
    out.push_str("];\n");
    out
}

/// Map a source-version counter name (e.g. `"profiles_ver"`) to the Rust
/// `SRC_*` const identifier the `projection_rev` module declares
/// (`SRC_PROFILES`). Pure string-shape transform: strip the `_ver` suffix,
/// uppercase, prefix `SRC_`.
fn src_const_ident(source_name: &str) -> String {
    let stem = source_name.strip_suffix("_ver").unwrap_or(source_name);
    format!("SRC_{}", stem.to_uppercase())
}

/// Write the generated dependency-table Rust to `out_path`.
///
/// # Errors
/// Filesystem I/O failures.
pub fn generate_builtin_deps(out_path: &Path) -> std::io::Result<()> {
    let rendered = render_builtin_deps();
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(out_path, rendered)
}

/// Diff a freshly-rendered dependency table against the file at `out_path`.
///
/// # Errors
/// Filesystem I/O failures other than NotFound.
pub fn check_builtin_deps(out_path: &Path) -> std::io::Result<BuiltinKeysCheckOutcome> {
    let rendered = render_builtin_deps();
    let actual = match std::fs::read_to_string(out_path) {
        Ok(s) => s,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            return Ok(BuiltinKeysCheckOutcome {
                up_to_date: false,
                first_diff_line: None,
            });
        }
        Err(err) => return Err(err),
    };
    if actual == rendered {
        return Ok(BuiltinKeysCheckOutcome {
            up_to_date: true,
            first_diff_line: None,
        });
    }
    let first_diff_line = crate::diff_report::first_diff_or_length(&actual, &rendered);
    Ok(BuiltinKeysCheckOutcome {
        up_to_date: false,
        first_diff_line,
    })
}

// ── DRAIN_PROJECTION_KEYS / CONDITIONAL_PRESENCE_KEYS (presence policy) ─────────
//
// #1723: the kernel's two presence-classification key sets were hand-authored in
// `kernel/projection_rev/mod.rs`. They are now generated from the contract's
// `presence_policy` column so the contract is the single source for presence
// semantics too: `DRAIN_PROJECTION_KEYS` = keys with `PresencePolicy::Drain`;
// `CONDITIONAL_PRESENCE_KEYS` = `Drain` ∪ `CopyWithTtl`.

/// Render `DRAIN_PROJECTION_KEYS` + `CONDITIONAL_PRESENCE_KEYS` from the
/// contract's presence policies. Included by
/// `crates/nmp-core/src/kernel/projection_rev/mod.rs`.
#[must_use]
pub fn render_presence_keys() -> String {
    let drains = drain_projection_keys();
    let conditional = rev_conditional_presence_keys();
    let mut out = String::new();
    out.push_str(
        "// @generated by `cargo run -p nmp-codegen -- gen presence-keys`. DO NOT EDIT.\n\
         //\n\
         // Source of truth: crates/nmp-codegen/src/projection_contract.rs\n\
         //   (PROJECTION_CONTRACT `presence_policy`: Drain → DRAIN_PROJECTION_KEYS;\n\
         //    Drain ∪ CopyWithTtl → CONDITIONAL_PRESENCE_KEYS). Regenerate + verify\n\
         //   drift via `.github/workflows/codegen-drift.yml` (gen presence-keys --check).\n",
    );
    out.push_str(
        "/// The drain projections whose presence is a `Changed → Cleared → Unchanged`\n\
         /// tristate driven by `note_drain_emit`, not by the rev alone.\n",
    );
    out.push_str("pub(crate) const DRAIN_PROJECTION_KEYS: &[&str] = &[\n");
    for key in &drains {
        out.push_str(&format!("    {key:?},\n"));
    }
    out.push_str("];\n");
    out.push_str(
        "/// The conditionally-present keys (drains + copy-with-TTL): the keys whose\n\
         /// accessor returns `Null` when the tracker is empty, so absence in `typed`\n\
         /// is unambiguous (it means the tracker went empty this tick).\n",
    );
    out.push_str("pub(crate) const CONDITIONAL_PRESENCE_KEYS: &[&str] = &[\n");
    for key in &conditional {
        out.push_str(&format!("    {key:?},\n"));
    }
    out.push_str("];\n");
    out
}

/// Write the generated presence-key Rust to `out_path`.
///
/// # Errors
/// Filesystem I/O failures.
pub fn generate_presence_keys(out_path: &Path) -> std::io::Result<()> {
    let rendered = render_presence_keys();
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(out_path, rendered)
}

/// Diff a freshly-rendered presence-key file against the file at `out_path`.
///
/// # Errors
/// Filesystem I/O failures other than NotFound.
pub fn check_presence_keys(out_path: &Path) -> std::io::Result<BuiltinKeysCheckOutcome> {
    let rendered = render_presence_keys();
    let actual = match std::fs::read_to_string(out_path) {
        Ok(s) => s,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {
            return Ok(BuiltinKeysCheckOutcome {
                up_to_date: false,
                first_diff_line: None,
            });
        }
        Err(err) => return Err(err),
    };
    if actual == rendered {
        return Ok(BuiltinKeysCheckOutcome {
            up_to_date: true,
            first_diff_line: None,
        });
    }
    let first_diff_line = crate::diff_report::first_diff_or_length(&actual, &rendered);
    Ok(BuiltinKeysCheckOutcome {
        up_to_date: false,
        first_diff_line,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn presence_keys_render_matches_contract_policies() {
        let r = render_presence_keys();
        assert!(r.contains("pub(crate) const DRAIN_PROJECTION_KEYS"));
        assert!(r.contains("pub(crate) const CONDITIONAL_PRESENCE_KEYS"));
        // Drains: action_results + signed_events.
        assert!(r.contains("\"action_results\""));
        assert!(r.contains("\"signed_events\""));
        // CopyWithTtl keys appear in CONDITIONAL but NOT in the DRAIN const.
        let drain_block = r.split("CONDITIONAL_PRESENCE_KEYS").next().unwrap();
        assert!(!drain_block.contains("\"action_stages\""));
        assert!(r.contains("\"action_stages\""));
        assert!(r.contains("\"action_lifecycle\""));
    }

    #[test]
    fn deps_render_is_stable_and_sorted() {
        let a = render_builtin_deps();
        let b = render_builtin_deps();
        assert_eq!(a, b, "deps render must be deterministic");
        assert!(a.contains("pub(crate) const BUILTIN_PROJECTION_DEPENDENCIES"));
        // profile depends on SRC_PROFILES + SRC_ACTIVE_ACCOUNT (mapped idents).
        assert!(a.contains("(\"profile\", &[SRC_PROFILES, SRC_ACTIVE_ACCOUNT])"));
        // refs.event maps to SRC_REF_EVENT_ROWS.
        assert!(a.contains("(\"refs.event\", &[SRC_REF_EVENT_ROWS])"));
    }

    #[test]
    fn src_ident_mapping_round_trips_known_names() {
        assert_eq!(src_const_ident("profiles_ver"), "SRC_PROFILES");
        assert_eq!(src_const_ident("ref_event_rows_ver"), "SRC_REF_EVENT_ROWS");
        assert_eq!(
            src_const_ident("active_account_ver"),
            "SRC_ACTIVE_ACCOUNT"
        );
    }

    #[test]
    fn render_is_stable_and_sorted() {
        let a = render_builtin_keys();
        let b = render_builtin_keys();
        assert_eq!(a, b, "render must be deterministic");
        assert!(a.contains("pub const KERNEL_BUILTIN_PROJECTION_KEYS"));
        // The out-of-registry built-in signed_events is present.
        // ADR-0063 Lane H: mention_profiles removed (kernel no longer emits it).
        assert!(a.contains("\"signed_events\""));
        assert!(!a.contains("\"mention_profiles\""), "mention_profiles must be removed (ADR-0063 Lane H)");
        // A Tier-2 decodable built-in is present.
        assert!(a.contains("\"relay_diagnostics\""));
        // A Tier-1 host registration is NOT a built-in.
        assert!(!a.contains("\"wallet\""));
        // A transient JSON-era key is NOT a built-in.
        assert!(!a.contains("\"timeline\""));
    }
}
