//! Typed FlatBuffers wire codec for the actor-owned `"bunker_handshake"`
//! projection (Tier-1 closure path).
//!
//! The authoritative FFI shape is the serde JSON the
//! `registry.register("bunker_handshake", …)` closure in
//! `crates/nmp-core/src/actor/mod.rs` inserts under `"bunker_handshake"`: the
//! serialisation of the shared `BunkerHandshakeSlot`
//! (`Arc<Mutex<Option<BunkerHandshakeDto>>>`) — JSON `null` when the slot is
//! `None`, else the serialised [`BunkerHandshakeDto`]. This module adds a
//! **typed FlatBuffers** encoding of the same shape, carried in the
//! `typed_projections` sidecar (ADR-0037) ALONGSIDE — never replacing — the
//! generic `Value` projection, and only when the slot holds `Some` (the typed
//! closure mirrors the JSON closure's `Some`/`None`: no sidecar entry while the
//! slot is idle).
//!
//! Honours D6 (no panics): decode returns `Err(String)` on any malformed input.

// The generated FlatBuffers bindings are intrinsically `unsafe`. This `allow`
// block scopes the relaxation to the single generated module.
#[allow(
    clippy::all,
    dead_code,
    deprecated,
    missing_docs,
    non_camel_case_types,
    non_snake_case,
    unsafe_code,
    unused_imports
)]
#[path = "generated/bunker_handshake_generated.rs"]
pub mod generated;

use flatbuffers::FlatBufferBuilder;

use generated::nmp::kernel as fb;

// #1723 — `*_SCHEMA_ID` / `*_FILE_IDENTIFIER` / `*_SCHEMA_VERSION` are
// derived from this projection's PROJECTION_CONTRACT entry and generated by
// `cargo run -p nmp-codegen -- gen producer-consts` (drift-gated in
// `.github/workflows/codegen-drift.yml`). Edit the contract, not this include.
include!("bunker_handshake_producer_consts.generated.rs");

/// A field-for-field mirror of the SERIALISED `BunkerHandshakeDto` — the value
/// the `"bunker_handshake"` JSON projection serialises when the slot is `Some`.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct BunkerHandshakeModel {
    pub stage: String,
    pub progress_code: Option<String>,
    pub message: Option<String>,
    pub is_idle: bool,
    pub is_in_flight: bool,
    pub is_failed: bool,
    pub is_terminal_success: bool,
    pub can_cancel: bool,
}

// --- encode ---------------------------------------------------------------

/// Encode a [`BunkerHandshakeModel`] to typed FlatBuffers bytes (with the `KBHS`
/// file identifier).
#[must_use]
pub(crate) fn encode_bunker_handshake(model: &BunkerHandshakeModel) -> Vec<u8> {
    let mut fbb = FlatBufferBuilder::new();
    let stage = fbb.create_string(&model.stage);
    let message = model.message.as_ref().map(|v| fbb.create_string(v));
    let progress_code = model.progress_code.as_ref().map(|v| fbb.create_string(v));
    let root = fb::BunkerHandshake::create(
        &mut fbb,
        &fb::BunkerHandshakeArgs {
            stage: Some(stage),
            has_message: model.message.is_some(),
            message,
            has_progress_code: model.progress_code.is_some(),
            progress_code,
            is_idle: model.is_idle,
            is_in_flight: model.is_in_flight,
            is_failed: model.is_failed,
            is_terminal_success: model.is_terminal_success,
            can_cancel: model.can_cancel,
        },
    );
    fb::finish_bunker_handshake_buffer(&mut fbb, root);
    fbb.finished_data().to_vec()
}

// --- decode ---------------------------------------------------------------

/// Decode typed FlatBuffers bytes (as produced by [`encode_bunker_handshake`])
/// back into a [`BunkerHandshakeModel`]. Returns an error string on any
/// malformed input. Available to sibling crates (e.g. desktop shells) for
/// decoding the `"bunker_handshake"` typed sidecar from a snapshot frame.
pub fn decode_bunker_handshake(bytes: &[u8]) -> Result<BunkerHandshakeModel, String> {
    if bytes.len() < 8 || !fb::bunker_handshake_buffer_has_identifier(bytes) {
        return Err("missing KBHS file identifier".to_string());
    }
    let root = fb::root_as_bunker_handshake(bytes)
        .map_err(|e| format!("not a valid BunkerHandshake buffer: {e}"))?;
    Ok(BunkerHandshakeModel {
        stage: root.stage().unwrap_or_default().to_string(),
        message: root
            .has_message()
            .then(|| root.message().unwrap_or_default().to_string()),
        progress_code: root
            .has_progress_code()
            .then(|| root.progress_code().unwrap_or_default().to_string()),
        is_idle: root.is_idle(),
        is_in_flight: root.is_in_flight(),
        is_failed: root.is_failed(),
        is_terminal_success: root.is_terminal_success(),
        can_cancel: root.can_cancel(),
    })
}

#[cfg(test)]
#[path = "bunker_handshake_fb_tests.rs"]
mod tests;
