// automatically generated by the FlatBuffers compiler, do not modify

package nmp.feed

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FeedPage : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FeedPage {
        __init(_i, _bb)
        return this
    }
    val limit : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val nextCursor : nmp.feed.FeedCursor? get() = nextCursor(nmp.feed.FeedCursor())
    fun nextCursor(obj: nmp.feed.FeedCursor) : nmp.feed.FeedCursor? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val hasMore : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val totalBlocks : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsFeedPage(_bb: ByteBuffer): FeedPage = getRootAsFeedPage(_bb, FeedPage())
        fun getRootAsFeedPage(_bb: ByteBuffer, obj: FeedPage): FeedPage {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFeedPage(builder: FlatBufferBuilder, limit: ULong, nextCursorOffset: Int, hasMore: Boolean, totalBlocks: ULong) : Int {
            builder.startTable(4)
            addTotalBlocks(builder, totalBlocks)
            addLimit(builder, limit)
            addNextCursor(builder, nextCursorOffset)
            addHasMore(builder, hasMore)
            return endFeedPage(builder)
        }
        fun startFeedPage(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addLimit(builder: FlatBufferBuilder, limit: ULong) = builder.addLong(0, limit.toLong(), 0)
        fun addNextCursor(builder: FlatBufferBuilder, nextCursor: Int) = builder.addOffset(1, nextCursor, 0)
        fun addHasMore(builder: FlatBufferBuilder, hasMore: Boolean) = builder.addBoolean(2, hasMore, false)
        fun addTotalBlocks(builder: FlatBufferBuilder, totalBlocks: ULong) = builder.addLong(3, totalBlocks.toLong(), 0)
        fun endFeedPage(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
