// automatically generated by the FlatBuffers compiler, do not modify

package nmp.feed

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FeedWindowMetrics : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FeedWindowMetrics {
        __init(_i, _bb)
        return this
    }
    val makeWindowUs : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsFeedWindowMetrics(_bb: ByteBuffer): FeedWindowMetrics = getRootAsFeedWindowMetrics(_bb, FeedWindowMetrics())
        fun getRootAsFeedWindowMetrics(_bb: ByteBuffer, obj: FeedWindowMetrics): FeedWindowMetrics {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFeedWindowMetrics(builder: FlatBufferBuilder, makeWindowUs: ULong) : Int {
            builder.startTable(1)
            addMakeWindowUs(builder, makeWindowUs)
            return endFeedWindowMetrics(builder)
        }
        fun startFeedWindowMetrics(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addMakeWindowUs(builder: FlatBufferBuilder, makeWindowUs: ULong) = builder.addLong(0, makeWindowUs.toLong(), 0)
        fun endFeedWindowMetrics(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
