import SwiftUI

// OWNER: Phase-2 Agent B (Profile screen). Init fixed by nav: ProfileView(pubkey:).
//
// Thin-shell rule: no business logic in Swift. Rust authors the flat author
// feed membership under `nmp.feed.author.<pubkey>`; Swift formats raw
// profile/count fields for presentation (ADR-0032).

struct ProfileView: View {
    let pubkey: String

    @EnvironmentObject private var model: KernelModel
    @EnvironmentObject private var router: ChirpRouter

    @State private var isEditingProfile = false

    private var profileConsumerID: String { "profile-screen-\(pubkey)" }
    /// ADR-0063 Lane E (#1671): the profile screen reads the unified
    /// `refs.profile` keyed-ref cache (`profileCard(forPubkey:)`) — NOT the
    /// legacy `claimedProfiles` / `resolvedProfileCards` maps. The screen claims
    /// `.profileCard` + `.live`, so the full card flows in and reactive
    /// profile-edit updates land here. `refresher` re-evaluates the body when
    /// this pubkey's row commits (per-key observation, no whole-map invalidation).
    @StateObject private var refresher = KeyedRefRowObserver()
    private var profile: ProfileCard? { model.profileCard(forPubkey: pubkey) }
    private var items: [ChirpRootCard] { model.authorFeed(pubkey: pubkey)?.cards ?? [] }

    /// Rust-authored wire for the shared `NostrUserCard` primitive. Built from
    /// the same `ProfileCard` the header already reads (claimed → resolved);
    /// Swift never resolves display name / NIP-05 / avatar URL itself.
    private var profileWire: ProfileWire {
        let card = profile
        return ProfileWire(
            pubkey: pubkey,
            displayName: (card?.displayName?.isEmpty == false) ? card?.displayName : nil,
            about: (card?.about.isEmpty == false) ? card?.about : nil,
            pictureUrl: card?.pictureUrl,
            nip05: (card?.nip05.isEmpty == false) ? card?.nip05 : nil,
            npub: nil,
            npubShort: pubkey.shortHex
        )
    }

    /// True when the screen shows the signed-in account's own profile.
    private var isOwnProfile: Bool { model.activeAccount == pubkey }

    /// True when the active account's NIP-02 follow set already contains
    /// `pubkey`. Reads the same `FollowListStore` the kernel snapshot feeds
    /// (`model.followList.follows`); the shell never recomputes graph state.
    private var isFollowing: Bool {
        model.followList.follows.contains { $0.pubkey == pubkey }
    }

    /// The single primary button rendered over the profile header. Own profile
    /// ⇒ local edit chrome (no Rust write); another account ⇒ Follow / Unfollow,
    /// carrying the typed `ProfileWrite` the shell maps to `model.follow` /
    /// `model.unfollow` (which build the generated bytes). The shell authors
    /// only the label/icon for presentation; it never builds namespaces or
    /// bodies.
    private var primaryAction: ProfileAction? {
        if isOwnProfile {
            return ProfileAction(
                label: "Edit Profile",
                iconName: "pencil",
                write: nil
            )
        }
        if isFollowing {
            return ProfileAction(
                label: "Following",
                iconName: "checkmark",
                write: .unfollow(pubkey: pubkey)
            )
        }
        return ProfileAction(
            label: "Follow",
            iconName: "person.badge.plus",
            write: .follow(pubkey: pubkey)
        )
    }

    /// Render context fed to each `ProfileNoteRow`. ADR-0063 Lane E (#1671):
    /// the whole-map `mentionProfiles` dictionary is gone — inline mention
    /// labels read the per-key keyed-ref cache inside `NoteContentView`.
    private var noteRenderContext: NoteRenderContext {
        NoteRenderContext(
            eventCards: Dictionary(uniqueKeysWithValues: items.map { ($0.card.id, $0.card) })
        )
    }

    var body: some View {
        ScrollView {
            VStack(spacing: 0) {
                profileHeader
                Divider()

                notesSection
            }
        }
        .accessibilityIdentifier("profile-detail-list")
        .chirpScreenBackground()
        .navigationTitle(profile?.displayLabel ?? "Profile")
        .navigationBarTitleDisplayMode(.inline)
        .task {
            model.openAuthor(pubkey: pubkey)
            // ADR-0063 Lane E (#1671): profile screen → `resolve_ref(Profile,
            // …, .profileCard, .live)`. `.profileCard` requests the full card
            // shape; `.live` opens a Tailing kind:0 interest so a profile edit
            // by this author updates the screen reactively.
            refresher.observe(model.profileRowChanged, pubkey: pubkey)
            model.resolveProfile(
                pubkey: pubkey, consumerID: profileConsumerID,
                shape: .profileCard, liveness: .live)
        }
        .onDisappear {
            // T152: release the author sub on nav-away (wire_subs baseline).
            model.closeAuthor(pubkey: pubkey)
            model.releaseProfile(pubkey: pubkey, consumerID: profileConsumerID)
        }
        .animation(.smooth(duration: 0.3), value: profile)
        .animation(.smooth(duration: 0.25), value: items.count)
        .sheet(isPresented: $isEditingProfile) {
            ProfileEditSheet(profile: profile) { name, about, picture in
                model.publishProfile(name: name, about: about, picture: picture)
            }
        }
    }

    // MARK: – Header

    @ViewBuilder
    private var profileHeader: some View {
        VStack(alignment: .leading, spacing: 0) {
            // Neutral banner the avatar overlaps. A flat surface fill (no
            // decorative gradient) keeps the screen monochrome; a real banner
            // image can replace this once the projection carries one.
            Rectangle()
                .fill(ChirpColor.surface)
                .frame(height: 84)
                .overlay(alignment: .bottom) {
                    Divider()
                }

            VStack(alignment: .leading, spacing: 10) {
                // Shared NMP primitive: avatar + display name + NIP-05 badge.
                // The actions overlay floats on top so it tracks the banner edge.
                NostrUserCard(profile: profileWire, avatarSize: 82)
                    .padding(.top, -41)
                    .overlay(alignment: .topTrailing) {
                        profileActions
                            .padding(.top, 8)
                    }

                // Screen-specific chrome: npub copy + about.
                profileChrome
            }
            .padding(.horizontal, 16)
            .padding(.bottom, 16)
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    @ViewBuilder
    private var profileActions: some View {
        if let primaryAction {
            HStack(spacing: 8) {
                Button {
                    perform(primaryAction)
                } label: {
                    // label + iconName are presentation only; writes are
                    // carried by the typed Rust action intent.
                    Label(primaryAction.label, systemImage: primaryAction.iconName)
                        .font(.subheadline.weight(.semibold))
                        .labelStyle(.titleAndIcon)
                }
                // Secondary treatment: a quiet gray chip, not a solid-black
                // block. Black is reserved for the rare assertive CTA; an
                // edit/follow affordance on your own profile should recede.
                .buttonStyle(.bordered)
                .buttonBorderShape(.roundedRectangle(radius: 10))
                .controlSize(.small)
                .tint(.primary)
                .accessibilityLabel(primaryAction.label)
            }
        }
    }

    /// Genuinely screen-specific chrome kept outside `NostrUserCard`: the about
    /// blurb. Avatar, display name, NIP-05 badge, and npub copy now come from
    /// shared primitives (issues #995 and #993).
    private var profileChrome: some View {
        VStack(alignment: .leading, spacing: 4) {
            // ADR-0032 / V-115: bech32 no longer in projection. Provide the
            // host-encoded copy value to the shared chip; pubkey is always available.
            NostrNpubChip(
                npub: model.encodeProfile(pubkey: pubkey) ?? pubkey,
                npubShort: pubkey.shortHex
            )
            .frame(minHeight: 44, alignment: .leading)

            if let about = profile?.about, !about.isEmpty {
                Text(about)
                    .font(.body)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
                    .padding(.top, 4)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    // MARK: – Notes list

    @ViewBuilder
    private var notesSection: some View {
        if items.isEmpty {
            ChirpPlaceholder(
                systemImage: "note.text",
                title: "No posts yet",
                subtitle: "Posts by this person will appear here."
            )
            .frame(minHeight: 260)
        } else {
            let context = noteRenderContext
            LazyVStack(spacing: 0) {
                // Left-aligned section header — no decorative centered
                // underline; the divider below carries the separation.
                HStack(spacing: 8) {
                    Text("Posts")
                        .font(.headline)
                        .foregroundStyle(.primary)
                    Text("\(items.count)")
                        .font(.callout)
                        .foregroundStyle(.secondary)
                        .accessibilityIdentifier("profile-notes-count-value")
                    Spacer(minLength: 0)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.horizontal, 16)
                .padding(.top, 16)
                .padding(.bottom, 8)

                Divider()

                ForEach(items) { root in
                    let card = root.card
                    ProfileNoteRow(
                        card: card,
                        renderContext: context,
                        onAvatarTap: {
                            router.push(.profile(pubkey: card.authorPubkey))
                        },
                        onRowTap: {
                            router.push(.thread(eventID: card.id))
                        },
                        onLike: {
                            model.react(targetEventID: card.id, reaction: "❤")
                        },
                        onRepost: {
                            model.repost(eventID: card.id, authorPubkey: card.authorPubkey)
                        }
                    )

                    if root.id != items.last?.id {
                        Divider()
                            .padding(.leading, 68)
                    }
                }
            }
        }
    }

    // MARK: – Helpers

    /// Performs the typed write carried by the button via the matching model
    /// call (which builds the generated builder bytes). A `nil` `write` is local
    /// UI chrome (the edit-profile sheet).
    private func perform(_ action: ProfileAction) {
        switch action.write {
        case .follow(let pubkey):
            model.follow(pubkey)
            UIImpactFeedbackGenerator(style: .medium).impactOccurred()
        case .unfollow(let pubkey):
            model.unfollow(pubkey)
            UIImpactFeedbackGenerator(style: .medium).impactOccurred()
        case nil:
            isEditingProfile = true
        }
    }
}

private struct ProfileEditSheet: View {
    let profile: ProfileCard?
    let onSave: (String, String, String) -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var name: String
    @State private var about: String
    @State private var picture: String

    init(profile: ProfileCard?, onSave: @escaping (String, String, String) -> Void) {
        self.profile = profile
        self.onSave = onSave
        // ADR-0032: edit sheet seeds the name with the kind:0 display name
        // (raw, may be `nil`) — NOT the abbreviated-hex fallback, which
        // would corrupt the published profile on save.
        _name = State(initialValue: profile?.displayName ?? "")
        _about = State(initialValue: profile?.about ?? "")
        let pictureUrl = profile?.pictureUrl ?? ""
        _picture = State(initialValue: pictureUrl.hasPrefix("http") ? pictureUrl : "")
    }

    var body: some View {
        NavigationStack {
            Form {
                TextField("Name", text: $name)
                TextField("About", text: $about, axis: .vertical)
                    .lineLimit(3...6)
                TextField("Picture URL", text: $picture)
                    .textInputAutocapitalization(.never)
                    .keyboardType(.URL)
            }
            .navigationTitle("Edit Profile")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .cancellationAction) {
                    Button("Cancel") { dismiss() }
                }
                ToolbarItem(placement: .confirmationAction) {
                    Button("Save") {
                        onSave(
                            name.trimmingCharacters(in: .whitespacesAndNewlines),
                            about.trimmingCharacters(in: .whitespacesAndNewlines),
                            picture.trimmingCharacters(in: .whitespacesAndNewlines)
                        )
                        dismiss()
                    }
                    .disabled(name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                }
            }
        }
    }
}
