// automatically generated by the FlatBuffers compiler, do not modify

package nmp.nip02

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FollowListSnapshot : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FollowListSnapshot {
        __init(_i, _bb)
        return this
    }
    fun follows(j: Int) : nmp.nip02.FollowEntry? = follows(nmp.nip02.FollowEntry(), j)
    fun follows(obj: nmp.nip02.FollowEntry, j: Int) : nmp.nip02.FollowEntry? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val followsLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsFollowListSnapshot(_bb: ByteBuffer): FollowListSnapshot = getRootAsFollowListSnapshot(_bb, FollowListSnapshot())
        fun getRootAsFollowListSnapshot(_bb: ByteBuffer, obj: FollowListSnapshot): FollowListSnapshot {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun FollowListSnapshotBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "NF02")
        fun createFollowListSnapshot(builder: FlatBufferBuilder, followsOffset: Int) : Int {
            builder.startTable(1)
            addFollows(builder, followsOffset)
            return endFollowListSnapshot(builder)
        }
        fun startFollowListSnapshot(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addFollows(builder: FlatBufferBuilder, follows: Int) = builder.addOffset(0, follows, 0)
        fun createFollowsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startFollowsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endFollowListSnapshot(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishFollowListSnapshotBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "NF02")
        fun finishSizePrefixedFollowListSnapshotBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "NF02")
    }
}
