// automatically generated by the FlatBuffers compiler, do not modify

package nmp.embed

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EmbedKindProjection : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EmbedKindProjection {
        __init(_i, _bb)
        return this
    }
    val kind : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val shortNote : nmp.embed.ShortNoteProjection? get() = shortNote(nmp.embed.ShortNoteProjection())
    fun shortNote(obj: nmp.embed.ShortNoteProjection) : nmp.embed.ShortNoteProjection? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val article : nmp.embed.ArticleProjection? get() = article(nmp.embed.ArticleProjection())
    fun article(obj: nmp.embed.ArticleProjection) : nmp.embed.ArticleProjection? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val highlight : nmp.embed.HighlightProjection? get() = highlight(nmp.embed.HighlightProjection())
    fun highlight(obj: nmp.embed.HighlightProjection) : nmp.embed.HighlightProjection? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val profile : nmp.embed.ProfileProjection? get() = profile(nmp.embed.ProfileProjection())
    fun profile(obj: nmp.embed.ProfileProjection) : nmp.embed.ProfileProjection? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val unknown : nmp.embed.UnknownProjection? get() = unknown(nmp.embed.UnknownProjection())
    fun unknown(obj: nmp.embed.UnknownProjection) : nmp.embed.UnknownProjection? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsEmbedKindProjection(_bb: ByteBuffer): EmbedKindProjection = getRootAsEmbedKindProjection(_bb, EmbedKindProjection())
        fun getRootAsEmbedKindProjection(_bb: ByteBuffer, obj: EmbedKindProjection): EmbedKindProjection {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEmbedKindProjection(builder: FlatBufferBuilder, kind: UByte, shortNoteOffset: Int, articleOffset: Int, highlightOffset: Int, profileOffset: Int, unknownOffset: Int) : Int {
            builder.startTable(6)
            addUnknown(builder, unknownOffset)
            addProfile(builder, profileOffset)
            addHighlight(builder, highlightOffset)
            addArticle(builder, articleOffset)
            addShortNote(builder, shortNoteOffset)
            addKind(builder, kind)
            return endEmbedKindProjection(builder)
        }
        fun startEmbedKindProjection(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addKind(builder: FlatBufferBuilder, kind: UByte) = builder.addByte(0, kind.toByte(), 0)
        fun addShortNote(builder: FlatBufferBuilder, shortNote: Int) = builder.addOffset(1, shortNote, 0)
        fun addArticle(builder: FlatBufferBuilder, article: Int) = builder.addOffset(2, article, 0)
        fun addHighlight(builder: FlatBufferBuilder, highlight: Int) = builder.addOffset(3, highlight, 0)
        fun addProfile(builder: FlatBufferBuilder, profile: Int) = builder.addOffset(4, profile, 0)
        fun addUnknown(builder: FlatBufferBuilder, unknown: Int) = builder.addOffset(5, unknown, 0)
        fun endEmbedKindProjection(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
