// automatically generated by the FlatBuffers compiler, do not modify

package nmp.embed

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EmbeddedEventEnvelope : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EmbeddedEventEnvelope {
        __init(_i, _bb)
        return this
    }
    val primaryId : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field primaryId")
            }
        }
    val primaryIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun primaryIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val uri : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val uriAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun uriInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val depth : UByte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val maxDepth : UByte
        get() {
            val o = __offset(10)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 4u
        }
    val collapsed : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hasCollapseReason : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val collapseReason : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val collapseReasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(16, 1)
    fun collapseReasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 16, 1)
    val projection : nmp.embed.EmbedKindProjection? get() = projection(nmp.embed.EmbedKindProjection())
    fun projection(obj: nmp.embed.EmbedKindProjection) : nmp.embed.EmbedKindProjection? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    override fun keysCompare(o1: Int, o2: Int, _bb: ByteBuffer) : Int {
         return compareStrings(__offset(4, o1, _bb), __offset(4, o2, _bb), _bb)
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsEmbeddedEventEnvelope(_bb: ByteBuffer): EmbeddedEventEnvelope = getRootAsEmbeddedEventEnvelope(_bb, EmbeddedEventEnvelope())
        fun getRootAsEmbeddedEventEnvelope(_bb: ByteBuffer, obj: EmbeddedEventEnvelope): EmbeddedEventEnvelope {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEmbeddedEventEnvelope(builder: FlatBufferBuilder, primaryIdOffset: Int, uriOffset: Int, depth: UByte, maxDepth: UByte, collapsed: Boolean, hasCollapseReason: Boolean, collapseReasonOffset: Int, projectionOffset: Int) : Int {
            builder.startTable(8)
            addProjection(builder, projectionOffset)
            addCollapseReason(builder, collapseReasonOffset)
            addUri(builder, uriOffset)
            addPrimaryId(builder, primaryIdOffset)
            addHasCollapseReason(builder, hasCollapseReason)
            addCollapsed(builder, collapsed)
            addMaxDepth(builder, maxDepth)
            addDepth(builder, depth)
            return endEmbeddedEventEnvelope(builder)
        }
        fun startEmbeddedEventEnvelope(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addPrimaryId(builder: FlatBufferBuilder, primaryId: Int)  {
            builder.addOffset(primaryId)
            builder.slot(0)
        }
        fun addUri(builder: FlatBufferBuilder, uri: Int) = builder.addOffset(1, uri, 0)
        fun addDepth(builder: FlatBufferBuilder, depth: UByte) = builder.addByte(2, depth.toByte(), 0)
        fun addMaxDepth(builder: FlatBufferBuilder, maxDepth: UByte) = builder.addByte(3, maxDepth.toByte(), 4)
        fun addCollapsed(builder: FlatBufferBuilder, collapsed: Boolean) = builder.addBoolean(4, collapsed, false)
        fun addHasCollapseReason(builder: FlatBufferBuilder, hasCollapseReason: Boolean) = builder.addBoolean(5, hasCollapseReason, false)
        fun addCollapseReason(builder: FlatBufferBuilder, collapseReason: Int) = builder.addOffset(6, collapseReason, 0)
        fun addProjection(builder: FlatBufferBuilder, projection: Int) = builder.addOffset(7, projection, 0)
        fun endEmbeddedEventEnvelope(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
        fun __lookup_by_key(obj: EmbeddedEventEnvelope?, vectorLocation: Int, key: String, bb: ByteBuffer) : EmbeddedEventEnvelope? {
            val byteKey = key.toByteArray(java.nio.charset.StandardCharsets.UTF_8)
            var span = bb.getInt(vectorLocation - 4)
            var start = 0
            while (span != 0) {
                var middle = span / 2
                val tableOffset = __indirect(vectorLocation + 4 * (start + middle), bb)
                val comp = compareStrings(__offset(4, bb.capacity() - tableOffset, bb), byteKey, bb)
                when {
                    comp > 0 -> span = middle
                    comp < 0 -> {
                        middle++
                        start += middle
                        span -= middle
                    }
                    else -> {
                        return (obj ?: EmbeddedEventEnvelope()).__assign(tableOffset, bb)
                    }
                }
            }
            return null
        }
    }
}
