// automatically generated by the FlatBuffers compiler, do not modify

package nmp.embed

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class HighlightProjection : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : HighlightProjection {
        __init(_i, _bb)
        return this
    }
    val id : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val idAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun idInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val authorPubkey : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authorPubkeyAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun authorPubkeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val hasAuthorDisplayName : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val authorDisplayName : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val authorDisplayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun authorDisplayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val createdAt : ULong
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val highlightedText : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val highlightedTextAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun highlightedTextInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val hasSourceEventId : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val sourceEventId : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceEventIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(18, 1)
    fun sourceEventIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 18, 1)
    val hasSourceEventAddr : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val sourceEventAddr : String?
        get() {
            val o = __offset(22)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceEventAddrAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(22, 1)
    fun sourceEventAddrInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 22, 1)
    val hasSourceUrl : Boolean
        get() {
            val o = __offset(24)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val sourceUrl : String?
        get() {
            val o = __offset(26)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceUrlAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(26, 1)
    fun sourceUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 26, 1)
    val hasContext : Boolean
        get() {
            val o = __offset(28)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val context : String?
        get() {
            val o = __offset(30)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val contextAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(30, 1)
    fun contextInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 30, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsHighlightProjection(_bb: ByteBuffer): HighlightProjection = getRootAsHighlightProjection(_bb, HighlightProjection())
        fun getRootAsHighlightProjection(_bb: ByteBuffer, obj: HighlightProjection): HighlightProjection {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createHighlightProjection(builder: FlatBufferBuilder, idOffset: Int, authorPubkeyOffset: Int, hasAuthorDisplayName: Boolean, authorDisplayNameOffset: Int, createdAt: ULong, highlightedTextOffset: Int, hasSourceEventId: Boolean, sourceEventIdOffset: Int, hasSourceEventAddr: Boolean, sourceEventAddrOffset: Int, hasSourceUrl: Boolean, sourceUrlOffset: Int, hasContext: Boolean, contextOffset: Int) : Int {
            builder.startTable(14)
            addCreatedAt(builder, createdAt)
            addContext(builder, contextOffset)
            addSourceUrl(builder, sourceUrlOffset)
            addSourceEventAddr(builder, sourceEventAddrOffset)
            addSourceEventId(builder, sourceEventIdOffset)
            addHighlightedText(builder, highlightedTextOffset)
            addAuthorDisplayName(builder, authorDisplayNameOffset)
            addAuthorPubkey(builder, authorPubkeyOffset)
            addId(builder, idOffset)
            addHasContext(builder, hasContext)
            addHasSourceUrl(builder, hasSourceUrl)
            addHasSourceEventAddr(builder, hasSourceEventAddr)
            addHasSourceEventId(builder, hasSourceEventId)
            addHasAuthorDisplayName(builder, hasAuthorDisplayName)
            return endHighlightProjection(builder)
        }
        fun startHighlightProjection(builder: FlatBufferBuilder) = builder.startTable(14)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addOffset(0, id, 0)
        fun addAuthorPubkey(builder: FlatBufferBuilder, authorPubkey: Int) = builder.addOffset(1, authorPubkey, 0)
        fun addHasAuthorDisplayName(builder: FlatBufferBuilder, hasAuthorDisplayName: Boolean) = builder.addBoolean(2, hasAuthorDisplayName, false)
        fun addAuthorDisplayName(builder: FlatBufferBuilder, authorDisplayName: Int) = builder.addOffset(3, authorDisplayName, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: ULong) = builder.addLong(4, createdAt.toLong(), 0)
        fun addHighlightedText(builder: FlatBufferBuilder, highlightedText: Int) = builder.addOffset(5, highlightedText, 0)
        fun addHasSourceEventId(builder: FlatBufferBuilder, hasSourceEventId: Boolean) = builder.addBoolean(6, hasSourceEventId, false)
        fun addSourceEventId(builder: FlatBufferBuilder, sourceEventId: Int) = builder.addOffset(7, sourceEventId, 0)
        fun addHasSourceEventAddr(builder: FlatBufferBuilder, hasSourceEventAddr: Boolean) = builder.addBoolean(8, hasSourceEventAddr, false)
        fun addSourceEventAddr(builder: FlatBufferBuilder, sourceEventAddr: Int) = builder.addOffset(9, sourceEventAddr, 0)
        fun addHasSourceUrl(builder: FlatBufferBuilder, hasSourceUrl: Boolean) = builder.addBoolean(10, hasSourceUrl, false)
        fun addSourceUrl(builder: FlatBufferBuilder, sourceUrl: Int) = builder.addOffset(11, sourceUrl, 0)
        fun addHasContext(builder: FlatBufferBuilder, hasContext: Boolean) = builder.addBoolean(12, hasContext, false)
        fun addContext(builder: FlatBufferBuilder, context: Int) = builder.addOffset(13, context, 0)
        fun endHighlightProjection(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
