// automatically generated by the FlatBuffers compiler, do not modify

package nmp.embed

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RefEventEnvelopes : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RefEventEnvelopes {
        __init(_i, _bb)
        return this
    }
    fun entries(j: Int) : nmp.embed.EmbeddedEventEnvelope? = entries(nmp.embed.EmbeddedEventEnvelope(), j)
    fun entries(obj: nmp.embed.EmbeddedEventEnvelope, j: Int) : nmp.embed.EmbeddedEventEnvelope? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val entriesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    fun entriesByKey(key: String) : nmp.embed.EmbeddedEventEnvelope? {
        val o = __offset(4)
        return if (o != 0) {
            nmp.embed.EmbeddedEventEnvelope.__lookup_by_key(null, __vector(o), key, bb)
        } else {
            null
        }
    }
    fun entriesByKey(obj: nmp.embed.EmbeddedEventEnvelope, key: String) : nmp.embed.EmbeddedEventEnvelope? {
        val o = __offset(4)
        return if (o != 0) {
            nmp.embed.EmbeddedEventEnvelope.__lookup_by_key(obj, __vector(o), key, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRefEventEnvelopes(_bb: ByteBuffer): RefEventEnvelopes = getRootAsRefEventEnvelopes(_bb, RefEventEnvelopes())
        fun getRootAsRefEventEnvelopes(_bb: ByteBuffer, obj: RefEventEnvelopes): RefEventEnvelopes {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun RefEventEnvelopesBufferHasIdentifier(_bb: ByteBuffer) : Boolean = __has_identifier(_bb, "NEMB")
        fun createRefEventEnvelopes(builder: FlatBufferBuilder, entriesOffset: Int) : Int {
            builder.startTable(1)
            addEntries(builder, entriesOffset)
            return endRefEventEnvelopes(builder)
        }
        fun startRefEventEnvelopes(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addEntries(builder: FlatBufferBuilder, entries: Int) = builder.addOffset(0, entries, 0)
        fun createEntriesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startEntriesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endRefEventEnvelopes(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishRefEventEnvelopesBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset, "NEMB")
        fun finishSizePrefixedRefEventEnvelopesBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset, "NEMB")
    }
}
